jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/people_detection.launch
jsk_pr2_robot/jsk_pr2_startup/pr2.launch

[jsk_pr2_startup] rename hydro_recognition.launch to people_detection.launch and start it up default

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/people_detection.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/tilt_self_filter.yaml
jsk_pr2_robot/jsk_pr2_startup/pr2.launch

1. remove torso_lift_link from self-filtering links. It markss a lot of points as shadow points..
2. increase padding parameter of shoulder links to avoid veiling noise caused by should links.
* before
* after

[jsk_pr2_startup] Update self filter parameter for tilt laser

---

jsk_nao_robot/naoeus/euslisp/nao-interface.l
jsk_nao_robot/naoeus/manifest.xml

nao-interface.lの中で使われているメッセージのパッケージを、新しい名前に変更しました。
よろしくお願い致します。

change to naoqi_msgs from nao_msgs

---

jsk_pepper_robot/pepper.rosinstall

Fix uri of nao_interaction

---

jsk_pepper_robot/README.md

Fix README.md

---

jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/openni_self_filter.yaml
jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/self_filter.launch

Hand-made parameter tuning for padding.
Is there any way to publish colorized pointcloud?

add self_filter launch and config to jsk_baxter

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/lasers_and_filters.xml

From #241 . Make laser_and_filter.xml same as pr2_navigation_perception setting

add tilt_scan_interpolated topic

---

jsk_pr2_robot/jsk_pr2_startup/catkin.cmake
jsk_pr2_robot/jsk_pr2_startup/package.xml

this is nessesary for `jsk_pr2_startup/jsk_pr2_move_base/look-forward-in-nav.l`

add move_base_msgs, roseus to build dependencies

---

jsk_pr2_robot/jsk_pr2_startup/catkin.cmake
jsk_pr2_robot/jsk_pr2_startup/package.xml

this is necessary for launching move_base

Add move base deps

---

jsk_baxter_robot/baxtereus/baxter-interface.l

With this
```
(send *ri* :angle-vector (send *baxter* :angle-vector))
```
will send to head action server too.

[baxtereus] add head action client for baxter

---

jsk_baxter_robot/jsk_baxter_startup/baxter.launch
jsk_robot_common/jsk_robot_startup/lifelog/active_user.l

- add machine tag for #270 
- add launch_user_name param to baxter.launch
- repair active_user.l to check type of diff-position

[jsk_baxter_startup] modify to prevent baxter.launch fail

---

jsk_baxter_robot/jsk_baxter_startup/baxter.launch
jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/kinect2.launch
jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/self_filter.launch

Because kinect2_bridge is not released as deb, I didn't add dependency to package.xml, but this requeire to prepare iai_kinect2.

[jsk_baxter_startup] Shift to use kinect2 from kinect

---

jsk_baxter_robot/jsk_baxter_startup/config/baxter_default.rviz

Add kinect2 point cloud config

update rviz config

---

jsk_pepper_robot/jsk_pepper_startup/launch/jsk_pepper_startup.launch
jsk_pepper_robot/jsk_pepper_startup/sample/sample.l
jsk_pepper_robot/peppereus/pepper-interface.l

I change the name of the launch file to solve some errors.
And I change the msgs' name from nao_msgs to naoqi_msgs.

modify msg name and launch file name

---

jsk_baxter_robot/baxtereus/baxter-interface.l
jsk_baxter_robot/jsk_baxter_startup/baxter.launch

-  [baxter-interface.l] notify this warning is ok

- [baxter-interface.l] overwrite :angle-vector-seuqnce for tm = :fast

---

jsk_baxter_robot/baxtereus/baxter-interface.l

TODO need travis test to find this type of failrue

- [baxter-interface.l] fix typo

---

jsk_pepper_robot/peppereus/pepper-interface.l

I added "pepper-init" , which is similar to "nao-init", to make robot instances more easily.

pepper-init added

---

jsk_pepper_robot/README.md
jsk_pepper_robot/jsk_201504_miraikan/package.xml
jsk_pepper_robot/jsk_pepper_startup/nodes/joy-client.l
jsk_pepper_robot/jsk_pepper_startup/package.xml
jsk_pepper_robot/pepper.rosinstall
jsk_pepper_robot/peppereus/.gitignore
jsk_pepper_robot/peppereus/CMakeLists.txt
jsk_pepper_robot/peppereus/package.xml
jsk_pepper_robot/peppereus/pepper.yaml

- [CMakeLists.txt, pepper.yaml] generate pepper model from pepper_description
- [package.xml] add more depends
- [.gitignore] ignore dae file too
- [pepper.rosinstall] use ros-naoqi from deb, just to download jsk_robot
- [package.xml] add depends to nao_apps
- [package.xml] add depends to jsk_pepper_startup and peppereus
- remove pepper_bringup and pepper_description, which is now avilable from ros-naoqi
- [jsk_pepper_robot/README.md] add to install pepper-meshes

udpate package to use pepper_robot from ros-naoqi

---

jsk_baxter_robot/baxtereus/baxter-interface.l

[baxtereus] add Baxter Safe Interface

---

jsk_robot_common/roseus_remote/launch/roseus_eusclient.launch
jsk_robot_common/roseus_remote/launch/roseus_eusserver.launch

to use ports which require super user permission

[roseus_remote] Add LAUNCH_PREFIX argument to roseus_eusserver.launch an.d  roseus_eusclient.launch

---

jsk_robot_common/roseus_remote/euslisp/remote-roseus-client.l
jsk_robot_common/roseus_remote/launch/roseus_eusclient.launch
jsk_robot_common/roseus_remote/launch/roseus_eusserver.launch

You can use $ like:
```
(setq awesome-code-result ($ (awesome-code)))
```

    [roseus_remote] Remove null characters from the strings from server and     return result from $ macro.

---

jsk_pepper_robot/peppereus/CMakeLists.txt

because the package is not yet released

[peppereus] Compilation does not fail even though pepper_urdf is not installed

---

jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_lifelog/baxter_tweet.launch
jsk_baxter_robot/jsk_baxter_startup/package.xml

Remove unneeded and unused nodes.

[jsk_baxter_startup] remove face_recognition from baxter.launch

---

jsk_pepper_robot/peppereus/pepper-interface.l

this requires https://github.com/ros-naoqi/naoqi_bridge/pull/37
@kochigami

- [pepper-interface.l] add error-vector method,

---

jsk_baxter_robot/baxtereus/baxter-interface.l

[baxter-interface.l] :angle-vector-sequence use default if nil ctype was passed

---

jsk_baxter_robot/baxtereus/baxter-interface.l
jsk_baxter_robot/baxtereus/test/test-baxter.l

- [baxtereus/test/test-baxter.l] add test code for baxter-interface
- [baxtereus] overwrite ros-state-callback in baxter-interface.l for suppress torso warning

fix ros-state-callback for supress torso warning

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_warning/battery_warning.l

fixed a bug.
force update the minimum if it has not been updated more then 30 sec

solve not updating problem after recharge

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/local_costmap_params.yaml

In PR https://github.com/jsk-ros-pkg/jsk_robot/pull/358 , I mistook topic name of base_scan.

[jsk_pr2_startup/jsk_pr2_move_base] fix topic name /base_scan_filtered -> /base_scan

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_image_transport/pr2_image_transport.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_image_transport/pr2_roi_transport.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/check_openni_node.py
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/kinect_head.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/openni_cloud_self_filter_color.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/openni_remote.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/people_detection.launch
jsk_pr2_robot/jsk_pr2_startup/pr2.launch

also add jsk_topic_tools/deprecated_relay for image_rect_color and depth_registered of openni_c2 namespace

[jsk_pr2_startup] use kinect_head(_c2) namespace instead of open(_c2) as pr2 default

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/db_client.launch
jsk_pr2_robot/jsk_pr2_startup/pr2.launch
jsk_pr2_robot/jsk_pr2_startup/pr2_gazebo.launch

With this feature, we can change map_frame with launch argument:
```bash
roslaunch jsk_pr2_startup pr2.launch # map_frame:=eng2
roslaunch jsk_pr2_startup pr2.launch map_frame:=eng8
roslaunch jsk_pr2_startup pr2_gazebo.launch map_frame:=eng8
```

[jsk_pr2_startup] add option map_frame to change eng2/eng8

---

jsk_baxter_robot/baxtereus/package.xml

this will fixes https://github.com/start-jsk/2014-semi/issues/816

[package.xml] add roseus pr2eus to baxtereus/package.xml

---

.rosinstall

can we remove pr2 repo from .rosinstall ?

.rosinstall remove pr2 deb files

---

jsk_pepper_robot/jsk_pepper_startup/CMakeLists.txt
jsk_pepper_robot/jsk_pepper_startup/package.xml
jsk_pepper_robot/jsk_pepper_startup/test/check_launch.test

update .travis for https://github.com/jsk-ros-pkg/jsk_travis/pull/110

[jsk_pepper_startup] add test_code to check if pepper launch is valid

---

.travis.yml
jsk_pepper_robot/peppereus/CMakeLists.txt
jsk_pepper_robot/peppereus/package.xml
jsk_pepper_robot/peppereus/test/peppereus.test
jsk_pepper_robot/peppereus/test/test-peppereus.l

test/test-peppereus.l: add test codes

---

jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_lifelog/baxter_tweet.launch
jsk_pr2_robot/jsk_pr2_startup/README.md
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/db_client.launch
jsk_pr2_robot/jsk_pr2_startup/pr2_bringup.launch

This PR changes the usage of database
**before**
```
PR2:
database: jsk_pr2_lifelog
collection: move_base_db
collection: object_detection_db
collection: action_result_db
...
baxter: none
```
**after**
```
database: jsk_robot_lifelog
collection: pr1012
collection: pr1040
collection: baxter
...
```

[jsk_robot] unified database

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/lasers_and_filters.xml
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/people_detection.launch
jsk_pr2_robot/jsk_pr2_startup/package.xml

this PR enables people tracking using face/leg detection

[jsk_pr2_startup/people_detection.launch] add people tracker

---

jsk_robot_common/jsk_robot_startup/launch/gmapping.launch
jsk_robot_common/jsk_robot_startup/launch/pointcloud_to_laserscan.launch
jsk_robot_common/jsk_robot_startup/package.xml
jsk_robot_common/jsk_robot_startup/scripts/ConstantHeightFramePublisher.py

Add launch scripts for gmapping, 2D SLAM using scan data converted from point cloud.
cf. http://wiki.ros.org/gmapping , http://wiki.ros.org/pointcloud_to_laserscan

[jsk_robot_startup] Add scripts and launch files for gmapping

---

jsk_pr2_robot/jsk_pr2_startup/sample/pr2_gazebo_73b2.launch

Just adding the simple launch to show how to use eus model related environment

[jsk_pr2_startup] add 73b2 sample launch file

---

jsk_robot_common/jsk_robot_startup/launch/gmapping.launch
jsk_robot_common/jsk_robot_startup/launch/pointcloud_to_laserscan.launch
jsk_robot_common/jsk_robot_startup/scripts/ConstantHeightFramePublisher.py

Add angle_min/max and respawn option

Modify pointcloud to laserscan params

---

jsk_pepper_robot/peppereus/CMakeLists.txt
jsk_pepper_robot/peppereus/package.xml
jsk_pepper_robot/peppereus/pepper-interface.l

- use 0.0.7 of jsk_travis
- roseus/CMakeLists.txt: add rostest to find_pakcage

fix to pass jenkins

---

jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_lifelog/baxter_tweet.launch
jsk_pr2_robot/jsk_pr2_startup/README.md
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/action_result_db.py
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/db_client.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/move_base_db.py
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/objectdetection_db.py
jsk_pr2_robot/jsk_pr2_startup/pr2_bringup.launch
jsk_robot_common/jsk_robot_startup/README.md
jsk_robot_common/jsk_robot_startup/lifelog/mongodb.launch
jsk_robot_common/jsk_robot_startup/lifelog/mongodb_replication_params.yaml
jsk_robot_common/jsk_robot_startup/lifelog/periodic_replicator_client.py

Reverts jsk-ros-pkg/jsk_robot#387

Revert "[jsk_robot] unified database" and use param "robot/name"

---

jsk_pr2_robot/jsk_pr2_startup/package.xml

reported at https://github.com/jsk-ros-pkg/jsk_robot/issues/409

[jsk_pr2_startup/package.xml] add social_navigation_layers to run_depends

---

jsk_robot_common/jsk_robot_startup/config/gmapping.rviz

Visualize slam related topics and integrated heightmap

[jsk_robot_startup] Add gmapping.rviz for gmapping.launch

---

jsk_pr2_robot/jsk_pr2_startup/pr2_gazebo.launch

This PR covers almost all image topics which are published on real robot.
Using new pr2_gazebo.launch, we can access to following topics:
```bash
/head_mount_kinect/depth/camera_info
/head_mount_kinect/depth/image_raw
/head_mount_kinect/depth/image_raw/compressed
/head_mount_kinect/depth/image_raw/compressed/parameter_descriptions
/head_mount_kinect/depth/image_raw/compressed/parameter_updates
/head_mount_kinect/depth/image_raw/compressedDepth
/head_mount_kinect/depth/image_raw/compressedDepth/parameter_descriptions
/head_mount_kinect/depth/image_raw/compressedDepth/parameter_updates
/head_mount_kinect/depth/image_raw/theora
/head_mount_kinect/depth/image_raw/theora/parameter_descriptions
/head_mount_kinect/depth/image_raw/theora/parameter_updates
/head_mount_kinect/depth/points …
```

[jsk_pr2_startup/pr2_gazebo.launch] use relay/republish instead of rgbd_launch for creating rectified images

---

jsk_pr2_robot/jsk_pr2_startup/sample/pr2_heightmap.launch

[jsk_pr2_startup] add pr2 heightmap sample launch

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/action_result_db_config.yaml
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/db_client.launch
jsk_pr2_robot/jsk_pr2_startup/package.xml

This will fails test with mongodb_store deb version.

[jsk_pr2_startup/jsk_pr2_lifelog/db_client.launch] enable logging more detail information

---

jsk_pepper_robot/jsk_pepper_startup/launch/jsk_pepper_startup.launch

set robot/name, robot/type as pr2 have
```
$ rosparam get robot/name
pr1012
$ rosparam get robot/type
pr2
```

set robot/type, robot/name

---

jsk_robot_common/jsk_robot_startup/lifelog/tweet.launch
jsk_robot_common/jsk_robot_startup/lifelog/tweet_client.l

fix for issue https://github.com/jsk-ros-pkg/jsk_3rdparty/issues/14

[jsk_robot_startup/lifelog/tweet.launch] use image_saver instead of extract_images for tweeting with image

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/global_costmap_params.yaml

[jsk_pr2_startup] update global costmap params

---

.rosinstall
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2.rosinstall
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/face_recognition_starter.py
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/people_detection.launch
jsk_pr2_robot/jsk_pr2_startup/package.xml

temporally use `furushchev/face_recognition` (fix-show-screen-flag branch) forked from `procrob/face_recognition` until merge https://github.com/procrob/face_recognition/pull/6 to work PR2.

[jsk_pr2_startup] add face_recognition

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/db_client.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/mongodb_log.py
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/pr2-tweet-log.l
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/pr2_tweet.launch
jsk_pr2_robot/jsk_pr2_startup/package.xml

`mongodb_log.py` is ported from `mongodb_log` repository.
The change is arguments to support name convention `robot/name` `robot/database`.

[jsk_pr2_startup/jsk_pr2_lifelog/mongodb_log.py] fix mongodb_log.py to support logging with jsk name convention

---

.rosinstall
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2.rosinstall

fix to use upstream repos since merged procrob/face_recognition#6

[.rosinstall] fix face_recognition to upstream

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/db_client.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/visualization/pr2_log_visualization.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/visualization/transform_utils.py
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/visualization/visualization_utils.py
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/visualization/visualize_move_base.py
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/visualization/visualize_objectdetection.l
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/visualization/visualize_objectdetection.py

[jsk_pr2_startup/jsk_pr2_lifelog/visualization] add visualization nodes for database

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/db_client.launch

This PR fixes excluding options of recording topics for avoiding duplicated record.

[jsk_pr2_startup/jsk_pr2_lifelog/db_client.launch] fix excluding topics for db record

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/db_client.launch

please merge after #447 if no problem

[jsk_pr2_startup/jsk_pr2_lifelog/db_client.launch] add result of face recognition data for recording to db

---

jsk_robot_common/jsk_robot_startup/lifelog/mongodb.launch
jsk_robot_common/jsk_robot_startup/lifelog/mongodb_replication_params.yaml
jsk_robot_common/jsk_robot_startup/lifelog/periodic_replicator_client.py

It is no problem to merge this PR, even if before https://github.com/strands-project/mongodb_store/pull/144 is merged,  cancellation feature is enabled after merging.

[jsk_robot_startup/lifelog/periodic_replicator_client.py] cancel replication when no wired network connection

---

jsk_pr2_robot/jsk_pr2_startup/pr2.launch

[jsk_pr2_startup] add db client params and map_frame in pr2.launch

---

jsk_robot_common/jsk_robot_startup/launch/odometry_integration.launch
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/OdometryFeedbackWrapper.py

Initialize odometry wrappers when odom_init_trigger is published

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/db_client.launch
jsk_pr2_robot/jsk_pr2_startup/pr2_bringup.launch
jsk_robot_common/jsk_robot_startup/lifelog/mongodb.launch

also changed machine from c1 to c2

[jsk_pr2_startup&jsk_robot_startup] add machine option for mongodb client

---

jsk_pr2_robot/jsk_pr2_startup/pr2.launch
jsk_pr2_robot/jsk_pr2_startup/pr2_bringup.launch

need this for https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/176

[jsk_pr2_startup] remap sound_play nodes to robotsound

---

jsk_robot_common/jsk_robot_startup/lifelog/mongodb.launch

ref: https://github.com/strands-project/mongodb_store/pull/151

[jsk_robot_startup/lifelog/mongodb.launch] use machine attribute for mongodb server/client

---

jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/OdometryFeedbackWrapper.py

Add option to change covariance model of odometry

Add velocity proportional sigma

---

jsk_naoqi_robot/README.md

Small change of the url in README.md. (jsk_pepper_robot -> jsk_naoqi_robot)

change url to jsk_naoqi_robot

---

jsk_robot_common/jsk_robot_startup/config/OdometryFeedbackWrapperReconfigure.cfg
jsk_robot_common/jsk_robot_startup/launch/odometry_integration.launch
jsk_robot_common/jsk_robot_startup/launch/particle_odometry.launch
jsk_robot_common/jsk_robot_startup/scripts/SlamMapTfToOdometry.py
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/OdometryFeedbackWrapper.py
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/OdometryOffset.py
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/ParticleOdometry.py

Use map information from slam (gmapping) as feedback to the viso to prevent it drifting.
Please merge after https://github.com/jsk-ros-pkg/jsk_robot/pull/486

Feedback slam map to odom

---

jsk_robot_common/jsk_robot_startup/config/OdometryFeedbackWrapperReconfigure.cfg
jsk_robot_common/jsk_robot_startup/launch/biped_localization.launch
jsk_robot_common/jsk_robot_startup/launch/gmapping.launch
jsk_robot_common/jsk_robot_startup/launch/odometry_integration.launch
jsk_robot_common/jsk_robot_startup/launch/particle_odometry.launch
jsk_robot_common/jsk_robot_startup/launch/pointcloud_to_laserscan.launch
jsk_robot_common/jsk_robot_startup/launch/viso.launch
jsk_robot_common/jsk_robot_startup/scripts/OdomDiffTransformPublisher.py
jsk_robot_common/jsk_robot_startup/scripts/SlamMapTfToOdometry.py
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/OdometryFeedbackWrapper.py
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/OdometryOffset.py
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/ParticleOdometry.py

[jsk_robot_startup] Add launch file to launch full SLAM and odometry system for biped robot

---

jsk_robot_common/jsk_robot_startup/launch/biped_localization.launch
jsk_robot_common/jsk_robot_startup/launch/particle_odometry.launch
jsk_robot_common/jsk_robot_startup/launch/slam_laser_nodelets.launch

Please merge after https://github.com/jsk-ros-pkg/jsk_robot/pull/494
This PR is needed to use new odom system in real robot.

Changes to use new odometry system in real robot 

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_rocon/README.md
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_rocon/cameraman_sample/cameraman_pr1012_rocon.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_rocon/cameraman_sample/cameraman_pr1040_rocon.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_rocon/cameraman_sample/pr1012_config.yaml
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_rocon/cameraman_sample/pr1012_tracker.l
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_rocon/cameraman_sample/pr1040_config.yaml
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_rocon/chatter_sample/chatter_pr1012_rocon.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_rocon/chatter_sample/chatter_pr1040_rocon.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_rocon/chatter_sample/pr1012_config.yaml
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_rocon/chatter_sample/pr1040_config.yaml
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_rocon/look_sample/look_pr1012_rocon.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_rocon/look_sample/look_pr1040_rocon.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_rocon/look_sample/pr1012_config.yaml
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_rocon/look_sample/pr1012_pose_publisher.l
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_rocon/look_sample/pr1012_pose_subscriber.l
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_rocon/look_sample/pr1040_config.yaml
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_rocon/pr2s_rocon_common/pr1012_rocon.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_rocon/pr2s_rocon_common/pr1040_rocon.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_rocon/pr2s_rocon_common/pr2s_common_rocon.launch

add the chatter sample for two pr2 communication.
This need the third machine to execute.
Please make the environment like below.
I didn't confirm but if you try to communicate with pr2s, topic might not come even when node is copied. (Because of VPN?)
If you successed to launch, the below will be shown in terminal for chatter_pr1012_rocon.launch
```
core service [/rosout] found
process[zeroconf/zeroconf-1]: started with pid [28166]
process[gateway-2]: started with pid [28167]
process[talker_pr1012-3]: started with pid [28171]
[INFO] [WallTime: 1449067598.154576] Gateway : generated unique hash name [jsk_pr1012_ece95d2b544747649998290766aba3de]
[INFO] [WallTime: 1449067598.159295] Gateway : adding rule to public watchlist [publisher][/hoge][]
[WARN] [WallTime: 1449067598.161820] Interface …
```

add rocon chatter sample between pr1012/pr1040 launch/configs

---

jsk_robot_common/jsk_robot_startup/config/HRP2JSKNT_odometry_params.yaml
jsk_robot_common/jsk_robot_startup/config/default_odometry_params.yaml
jsk_robot_common/jsk_robot_startup/launch/biped_localization.launch
jsk_robot_common/jsk_robot_startup/launch/particle_odometry.launch
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/OdometryOffset.py
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/ParticleOdometry.py

Please merge after https://github.com/jsk-ros-pkg/jsk_robot/pull/508

[jsk_robot_startup] Cancel noise of velocity using median filter in odometry offset

---

jsk_pr2_robot/jsk_pr2_startup/package.xml

ref: https://github.com/jsk-ros-pkg/jsk_robot/issues/512

[jsk_pr2_startup/package.xml] add missing run dependencies

---

jsk_naoqi_robot/jsk_pepper_startup/CMakeLists.txt
jsk_naoqi_robot/jsk_pepper_startup/package.xml
jsk_naoqi_robot/jsk_pepper_startup/test/check_launch.test

This will fix recent error
https://github.com/jsk-ros-pkg/jsk_robot/pull/526#issuecomment-164995158

[.travis] update to latest

---

jsk_robot_common/jsk_robot_startup/config/HRP2JSKNT_odometry_params.yaml
jsk_robot_common/jsk_robot_startup/launch/biped_localization.launch
jsk_robot_common/jsk_robot_startup/launch/particle_odometry.launch
jsk_robot_common/jsk_robot_startup/scripts/CameraToBaseOffset.py
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/ParticleOdometry.py

Please merge after https://github.com/jsk-ros-pkg/jsk_robot/pull/522

Fix calculation of imu orientation when imu parent link was moved

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/check_openni_node.py
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/kinect_head.launch

- cleanup codes
- add `speak` parameter for enabling/disabling speaking feature
- add `sleep_cycle` for setting rate of check if openni node is alive
- add service advertise `~restart` to force invoke restarting openni node from service call

[jsk_pr2_startup/jsk_pr2_sensors/check_openni_node.py] refactor check_openni_node.py

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/costmap_common_params.yaml
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/global_costmap_params_hydro.yaml
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/local_costmap_params.yaml
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/move_base.xml

- revert nice value of move_base_node to default
- remove duplicated param
- small local costmap size

[jsk_pr2_startup/jsk_pr2_move_base] revert nice value of move_base_node to default

---

jsk_robot_common/roseus_remote/CMakeLists.txt
jsk_robot_common/roseus_remote/package.xml

Modified:
- jsk_robot_common/roseus_remote/package.xml

Fix genjava problem caused by not listed message_generation

---

jsk_pr2_robot/jsk_pr2_startup/package.xml

ref: https://github.com/jsk-ros-pkg/jsk_robot/issues/512

[jsk_pr2_startup/package.xml] add eusurdf to run_depend

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/costmap_common_params.yaml

This is enough for navigation on indoor environment

[jsk_pr2_startup/jsk_pr2_move_base/costmap_common_params.yaml] fix: initial inflation range

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/objectdetection_db.py

This prevents to increase subscriber count of object detection nodes.
@h-kamada This may fix the problem of pointpose_extractor

[jsk_pr2_startup/jsk_pr2_lifelog/objectdetection_db.py] unsubscribe objectdetection topics which has no other subscribers

---

jsk_robot_common/jsk_robot_startup/launch/slam_octomap.launch

Added:
- jsk_robot_common/jsk_robot_startup/launch/slam_octomap.launch

[jsk_robot_startup] Add octomap launch using slam

---

jsk_robot_common/jsk_robot_startup/config/JAXON_RED_odometry_params.yaml

Update JAXON_RED parameters according to the velocity measurement

Tune jaxon red odom param

---

jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/ParticleOdometry.py
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/odometry_utils.py

Prevent biped_particle_odom oscilation at around 180[deg] by referencing previous rpy in transformation from quaternion to euler

Fix oscillation when turn backward

---

jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_tools/xdisplay_image_topic.py

Added:
- jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_tools/xdisplay_image_topic.py

Add tool to relay image topic to display on xdisplay

---

jsk_naoqi_robot/naoeus/nao.yaml
jsk_naoqi_robot/naoqieus/cmake/compile_naoqi_model.cmake

-  add end-coords for nao robot
- naoqieus/cmake/compile_naoqi_model.cmake: .l depends on .yaml

fix leg end-coords for nao robot

---

jsk_naoqi_robot/naoqieus/naoqi-interface.l

I added ```:animated-speak method```. 
A robot can make a gesture while speaking.
It requires this pull-request [naoqi_driver: add subscribers/animated_speech.cpp/hpp] (https://github.com/ros-naoqi/naoqi_driver/pull/65).

[naoqieus] add animated-speak method

---

jsk_naoqi_robot/naoeus/nao-interface.l
jsk_naoqi_robot/naoqieus/naoqi-interface.l
jsk_naoqi_robot/peppereus/pepper-interface.l

#570 でご相談したように，３つの共通メソッドをnaoqi-interface.lに移しました．
ナオでまだ試せていません．　（#578　に書きました．）

[naoqieus] move send-stiffness-controller, servo-on/ off methods to naoqi-interface

---

jsk_pr2_robot/jsk_pr2_startup/package.xml

https://github.com/jsk-ros-pkg/jsk_robot/issues/576

[jsk_pr2_startup/package.xml] add run_dependency.

---

jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_tools/xdisplay_image_topic.py

to handle mono and rgba images

Convert to BGR image

---

jsk_fetch_robot/fetcheus/fetch-interface.l

Demo: https://drive.google.com/uc?id=0B9P1L--7Wd2vQ3lUdXk4cXVIa1k

[fetcheus] Control gripper from robot interface

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2.rosinstall

for applying the fix in #539 
CC: @h-kamada 
Not yet be tested on PR2 real robot.

[jsk_pr2_startup/jsk_pr2.rosinstall] update jsk_robot to 1.0.2

---

jsk_robot_common/jsk_robot_startup/launch/biped_localization.launch
jsk_robot_common/jsk_robot_startup/launch/particle_odometry.launch

Related with https://github.com/jsk-ros-pkg/jsk_robot/pull/401#issuecomment-167803804

[jsk_robot_startup] Use parameter_yaml arg instead of ROBOT environmental value for odometry params

---

jsk_baxter_robot/baxtereus/test/test-baxter.l
jsk_baxter_robot/baxtereus/test/test-baxter.test

 [baxtereus] add ik check test for apc

---

jsk_robot_common/jsk_robot_startup/package.xml
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/ParticleOdometry.py

For debug of particle odometry

Add publish_histogram option to visualize particles

---

jsk_naoqi_robot/README.md

I'd like to explain that installing nao_meshes from source is not recommendable. (IRT model making seems to fail.)

[jsk_naoqi_robot/README.md] add explanation on how to make nao model for euslisp

---

jsk_naoqi_robot/README.md

- explanation on adding PYTHONPATH
- add comment on NAO_IP
- add more information on how to execute sample  related to #614

[jsk_naoqi_robot] update README for nao and pepper

---

jsk_fetch_robot/fetcheus/CMakeLists.txt
jsk_fetch_robot/fetcheus/fetch-interface.l
jsk_fetch_robot/fetcheus/package.xml
jsk_fetch_robot/fetcheus/test/fetch-moveit.test
jsk_fetch_robot/fetcheus/test/fetcheus.test
jsk_fetch_robot/fetcheus/test/test-fetch-moveit.l
jsk_fetch_robot/fetcheus/test/test-fetcheus.l

This is the rebasead version of #610

feteus-interface.l : always use moveit within :angle-vector

---

jsk_robot_common/jsk_robot_startup/config/JAXON_RED_odometry_params.yaml
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/EKFGPFOdometry.py

Limit sampling time and increase particle number

Prevent particle degeneration

---

jsk_robot_common/jsk_robot_startup/scripts/SlamMapTfToOdometry.py

[jsk_robot_startup] Fix transformation from odom to map in slam_odom topic

---

jsk_robot_common/jsk_robot_startup/launch/particle_odometry.launch
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/EKFGPFOdometry.py
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/ParticleOdometry.py

Publish diagnostics in odometry

---

jsk_robot_common/jsk_robot_startup/launch/particle_odometry.launch
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/EKFGPFOdometry.py
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/ParticleOdometry.py

to fix large y direction error bag

Apply ekf update in source odom callback

---

.travis.yml

All tests including tests using gazebo passed in my personal branch
https://travis-ci.org/furushchev/jsk_robot/builds/151137407

[.travis.yml] use travis for building all distro

---

jsk_pr2_robot/jsk_pr2_startup/package.xml

https://github.com/ros/catkin/issues/824

[jsk_pr2_startup] remove meta package from dependencies

---

jsk_naoqi_robot/jsk_pepper_startup/package.xml

https://github.com/ros/catkin/issues/824

[jsk_pepper_startup] remove meta package dependencies

---

jsk_naoqi_robot/naoqieus/naoqi-interface.l

I tried to modify conflicts in https://github.com/jsk-ros-pkg/jsk_robot/pull/661, but I failed.
I re-wrote same methods with new naoqi-interface update. 
I'm very sorry for my trouble.

[naoqieus] add set (get) move arms enabled

---

jsk_fetch_robot/jsk_fetch_startup/scripts/warning.py

to fix:
```
[ERROR] [WallTime: 1475047567.560302] [147.195000] bad callback: <bound method Warning.cmd_vel_callback of <__main__.Warning instance at 0x7fa7df108cb0>>
Traceback (most recent call last):
File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
cb(msg)
File "/home/furushchev/ros/indigo/src/jsk-ros-pkg/jsk_robot/jsk_fetch_robot/jsk_fetch_startup/scripts/warning.py", line 92, in cmd_vel_callback
breaker_status = filter(lambda n: n.name=='base_breaker', self.robot_state_msgs.breakers)[0]
AttributeError: Warning instance has no attribute 'robot_state_msgs'
```

[jsk_fetch_startup/scripts/warning.py] bugfix: error with no robot_state msg is subscribed

---

jsk_naoqi_robot/README.md

[jsk_naoqi_robot] add comment on ROS_DISTRO

---

jsk_robot_common/jsk_robot_startup/scripts/ImuRootlinkCalculator.py

I misundersood specifications of transformQuaternion and transformVector3.

[jsk_robot_startup] Fix imu_rootlink calculation bug

---

jsk_fetch_robot/jsk_fetch_startup/README.md

- add how to sync clocks (@wkentaro)
I'm not sure why we can not connect rviz this afternoon, but now it works ok after install chrony on my computer...not sure.

add more admin docs

---

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch

add moveit to fetch_bringup, forget at https://github.com/jsk-ros-pkg/jsk_robot/pull/610

fetch_bringup.launch: add launch_moveit args

---

jsk_naoqi_robot/jsk_nao_startup/launch/jsk_nao_startup.launch

[jsk_nao_startup] same as #675

---

jsk_fetch_robot/jsk_fetch_startup/README.md

For https://github.com/jsk-ros-pkg/jsk_robot/pull/691#issuecomment-257469817

[jsk_fetch_startup] add network instruction to fetch README

---

jsk_fetch_robot/README.md

Update README.md
Add gazebo simulation; inverse kinematics; moving the robot; speak   explanations to readme file

update version of #708

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2.rosinstall

For https://github.com/jsk-ros-pkg/jsk_robot/issues/704#issuecomment-258115280

Update jsk_pr2.rosinstall with actual rosinstall on real robots

---

jsk_fetch_robot/fetcheus/fetch.yaml

```
send *fetch* :torso :waist-z :joint-angle 20
```
moveit need more space between base and `elbow_flex_link`

 [fetcheus] modify :reset-pose

---

jsk_fetch_robot/README.md

updated version of #725
Close #735

jsk_fetch_robot : fixed version of update readme #735

---

jsk_baxter_robot/baxtereus/baxter-util.l

c.f. https://github.com/start-jsk/jsk_apc/pull/1990

add ik-prepared-poses in baxter class

---

.travis.yml

- update `.travis` to 0.4.23
- cleanup `.travis.yml`

[.travis] update travis to 0.4.25

---

jsk_baxter_robot/jsk_baxter_startup/baxter.launch
jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_moveit/moveit.launch

launch baxter moveit from `jsk_baxter_startup/baxter.launch`

[jsk_baxter_moveit] modify jsk_baxter_moveit moveit.launch

---

jsk_baxter_robot/baxtereus/baxter-interface.l

add `:wait` key as `:stop-grasp`

[baxtereus] add wait key in :start-grasp

---

jsk_fetch_robot/fetcheus/fetch.yaml
jsk_fetch_robot/fetcheus/package.xml
jsk_fetch_robot/fetcheus/test/test-fetcheus.l

with test code
- test/test-fetcheus.l: add test to check #771
- package.xml: add depends to pr2eus_moveit

[fetch] Correct head orientation for look-at #771

---

jsk_fetch_robot/fetcheus/test/fetch-moveit.test

- use simulation.launch instead of playground.launch
- disable gui in fetch-moveit.test

[fetcheus] disable gui in fetch-moveit.test

---

.travis.yml
jsk_baxter_robot/baxtereus/CMakeLists.txt
jsk_baxter_robot/baxtereus/package.xml
jsk_baxter_robot/baxtereus/test/baxter-moveit.test
jsk_baxter_robot/baxtereus/test/test-baxter-moveit.l
jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_tools/initialize_baxter.py

- add `initialiaze_baxter.py` 
- originally from `jsk_2015_05_baxter_apc`
- modify to launch `move_group.launch`
- add `baxter-moveit.test`
- add `test-baxter-moveit.l`

[baxtereus][jsk_baxter_startup] add baxter moveit test

---

jsk_baxter_robot/baxtereus/baxter-interface.l

add `:robot` key in `baxter-interface` `:init`

[baxtereus] add key :robot in baxter-interface :init

---

jsk_pr2_robot/jsk_pr2_startup/pr2.launch

addressed at https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/101

[jsk_pr2_startup][pr2.launch] update voice_text launch

---

jsk_fetch_robot/README.md

fixed version of #767
Closes #767

add how to know grasp result

---

jsk_naoqi_robot/README.md

- add information of joint order when accessing pepper by euslisp

[jsk_naoqi_robot/README] add joint information of peppereus

---

.travis.rosinstall
.travis.rosinstall.kinetic
jsk_fetch_robot/fetcheus/CMakeLists.txt
jsk_naoqi_robot/naoqieus/CMakeLists.txt
jsk_pr2_robot/jsk_pr2_startup/CMakeLists.txt

- remove CMakeLists.txt: pr2_* from CATKIN_DEPENDS
- add .travis.rosinstall.kinetic

enable to pass travis on kinetic

---

jsk_fetch_robot/fetcheus/fetch-interface.l

confirmed on real robot
Closes #831

[fetcheus] Simple unsafe base movement for fetch robot

---

.travis.yml
jsk_baxter_robot/baxtereus/test/baxter-moveit.test

running two gazebo instance on test???

travis.yaml: set ROS_PARALLEL_TEST_JOBS to 1

---

jsk_fetch_robot/jsk_fetch_startup/CMakeLists.txt
jsk_fetch_robot/jsk_fetch_startup/config/install_upstart.sh
jsk_fetch_robot/jsk_fetch_startup/env-hooks/99.jsk_fetch_startup.bash
jsk_fetch_robot/jsk_fetch_startup/env-hooks/99.jsk_fetch_startup.sh
jsk_fetch_robot/jsk_fetch_startup/env-hooks/99.jsk_fetch_startup.zsh

- enabled USB speaker
- enabled bash command for setting up fetch

jsk_fetch_startup: update util scripts

---

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_teleop.xml
jsk_fetch_robot/jsk_fetch_startup/scripts/warning.py

- Launch nodes for auto docking / undocking on `fetch_bringup.launch`
- Avoid disabling base breaker on auto undocking

jsk_fetch_startup: support auto dock / undock

---

jsk_fetch_robot/fetcheus/fetch-interface.l

`(send *ri* :speak "hello")`
でfetchがしゃべるようにしました。

Load speak.l in fetch-interface.l

---

jsk_fetch_robot/README.md

コントローラのどのボタンを押せばどの行動が出来るのかを表にまとめました。

[fetch] コントローラの使い方

---

jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_tools/xdisplay_image_topic.py

Baxter's new display size is 1920 x 1200

---

jsk_robot_common/jsk_robot_startup/scripts/CameraToBaseOffset.py
jsk_robot_common/jsk_robot_startup/scripts/OdometryTfManager.py
jsk_robot_common/jsk_robot_startup/scripts/SlamMapTfToOdometry.py
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/CalculateOdomInitToBaseLinkTransform.py
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/OdometryFeedbackWrapper.py
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/OdometryIIRFilter.py
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/OdometryOffset.py
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/ParticleOdometry.py
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/odometry_utils.py
jsk_robot_common/jsk_robot_startup/util/mux_selector.py

numpy 1.14以降ではarrayを ==演算子で Noneと比較すると
```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
というエラーが出ます。
numpy 1.11ではFutureWarningしか出なかったのですが、1.14以降でもエラーが出ないようにするべきだと思い
比較演算子を==からisに、!=からis notに変更しました。
これで1.11でも1.14でもエラーが出なくなります。

Changed comparison operator for None

---

jsk_robot_common/jsk_robot_utils/scripts/marker_msg_from_indigo_to_kinetic.py

We can use /spots_marker_array topic of PR2 on kinetic

add marker_msg_from_indifo_to_kinetic.py

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/kinect_head_self_filter.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/lasers_and_filters.xml
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/tilt_self_filter.yaml
jsk_pr2_robot/jsk_pr2_startup/package.xml

jsk_pr2_startup: fix self_filter to work in indigo

---

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_lifelog.xml

Without this, database size in fetch robot never decrease.

fetch: enable replication

---

jsk_naoqi_robot/README.md
jsk_naoqi_robot/jsk_pepper_startup/README.md

I added some tips related to issue #926 when people use Pepper.

[jsk_naoqi_robot] add tablet information related to #926

---

jsk_robot_common/jsk_robot_startup/lifelog/common_logger.launch
jsk_robot_common/jsk_robot_startup/package.xml

Merge this after #919 
Replaces `jsk_topic_tools/LightweightThrottle` with `jsk_topic_tools/SynchronizedThrottle`.

jsk_robot_startup: use synchronized_throttle for camera

---

jsk_fetch_robot/jsk_fetch_startup/README.md

Add app usage to README.md

---

jsk_naoqi_robot/jsk_pepper_startup/launch/jsk_pepper_startup.launch

I modified Pepper's speed slower when we use a joystick controller.
(I referenced wiki page of teleop_twist_joy.)
I also added a comment about a stop button.

[jsk_pepper_startup] modify teleop twist joy parameter: scale_linear and scale_linear_turbo

---

jsk_naoqi_robot/jsk_nao_startup/launch/jsk_nao_startup.launch

I'd like to use common packages as for jsk_nao/pepper_startup.
- quit using nao_interaction_launchers
- add launch_twitter param name
What I will do in a few days:
- add joy package

[jsk_nao_startup] use common packages as jsk_pepper_startup

---

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
jsk_fetch_robot/jsk_fetch_startup/scripts/correct_position.py

`Fetch`が`dock`または`undock`した時に、自己位置を充電dockに移動させるプログラムを書きました。

correct position of fetch when dock/undock

---

jsk_pr2_robot/jsk_pr2_startup/package.xml
jsk_robot_common/jsk_robot_startup/lifelog/common_logger.launch

- added `cmd_vel_smoother` as run_depend since the package is now released
- added option to switch `approximate_sync` on logging images into DB

update on launch files

---

jsk_fetch_robot/jsk_fetch_startup/README.md

fetchが台所に行ってドックに帰ってくるプログラムを作った(#961)ので、
これを平日の朝10時に実行するようにcrontabに書きました。

[fetch] Update README of jsk_fetch_startup about crontab

---

jsk_robot_common/jsk_robot_startup/lifelog/README.md

Fix lifelog README.md

---

jsk_fetch_robot/README.md
jsk_fetch_robot/jsk_fetch.rosinstall.kinetic

fix bug in `jsk_fetch.rosinstall.kinetic` and update `README.md` for kinetic user.

[jsk_fetch_robot] Update README.md and .rosinstall for kinetic user

---

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
jsk_fetch_robot/jsk_fetch_startup/package.xml

fetchを起動する際に、自動的にrespeakerとjuliusを立ち上げるようにしました。
これにより、fetchが音声認識出来るようになります。

[fetch] Launch respeaker and julius when booting fetch

---

jsk_aero_robot/aeroeus/README.md

fix README.md for generate eus model from urdf.

[aero] update aeroeus README

---

jsk_naoqi_robot/naoeus/README.md

0, 1 are not head angle (22, 23 are correct).
I confirmed it with 
```
roscore
roseus nao-interface.l
nao-init
send *nao* :reset-pose
#f(110.0 10.0 -90.0 -40.0 0.0 110.0 -10.0 90.0 40.0 0.0 0.0 0.0 -30.0 60.0 -30.0 0.0 0.0 0.0 -30.0 60.0 -30.0 0.0 0.0 0.0)
2.irteusgl$ send *nao* :larm :shoulder-p :joint-angle 
110.0
3.irteusgl$ send *nao* :larm :shoulder-r :joint-angle 
10.0
4.irteusgl$ send *nao* :larm :elbow-y :joint-angle 
-90.0
5.irteusgl$ send *nao* :larm :elbow-p :joint-angle 
-40.0
6.irteusgl$ send *nao* :larm :wrist-y :joint-angle 
0.0
7.irteusgl$ send *nao* :rarm :shoulder-p :joint-angle 
110.0
8.irteusgl$ send *nao* :rarm :shoulder-r :joint-angle 
-10.0
9.irteusgl$ send *nao* :rarm :elbow-y :joint-angle 
90.0
10.irteusgl$ send *nao* :rarm :elbow-p :joint-angle 
40.0
11.irteusgl$ …
```

[naoeus/README] modify joints of NAO: fix order

---

jsk_naoqi_robot/naoqieus/doc/error_vector.md

This method can be available in `naoqi_driver (kochigami-develop)`.  
I updated a doc.

[naoqieus/doc] update :error-vector method

---

jsk_naoqi_robot/naoqieus/README.md

I forgot to add menu for #1023 .
Sorry for my mistake.

[naoqieus/README] add missing method (:speak-action) to method menu

---

jsk_robot_common/jsk_robot_startup/util/finish_launch_sound.py
jsk_robot_common/jsk_robot_startup/util/start_launch_sound.py

Suppress warning on not setting queue_size

---

jsk_fetch_robot/README.md

add admin tips for fetch15, reported at https://github.com/jsk-ros-pkg/jsk_robot/issues/859#issuecomment-341269420

add admin tips for fetch15

---

jsk_naoqi_robot/naoeus/README.md

```
(call-empty-service "/nao_robot/pose/life/disable)
(send *ri* :servo-on)
```

[WIP] update how to use nao

---

jsk_fetch_robot/jsk_fetch_startup/README.md
jsk_fetch_robot/jsk_fetch_startup/config/install_upstart.sh

- launch jsk-fetch-startup by fetch user
- update README
now fetch15 is running with this config.
cc. @708yamaguchi

[Fetch] launch jsk-fetch-startup by fetch user 

---

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_tweet.launch
jsk_robot_common/jsk_robot_startup/lifelog/active_user.l
jsk_robot_common/jsk_robot_startup/lifelog/tweet_client.l
jsk_robot_common/jsk_robot_startup/lifelog/tweet_client_uptime.l
jsk_robot_common/jsk_robot_startup/lifelog/tweet_client_warning.l

[jsk_robot_startup] Fix tweet nodes to support fetch

---

jsk_naoqi_robot/jsk_pepper_startup/nodes/list_up_ros_node.py

This PR is for #1077 
I followed the comment here: https://github.com/jsk-ros-pkg/jsk_robot/pull/1073#discussion_r281475763

[jsk_pepper_startup/list_up_ros_node.py] kill /naoqi_driver_node by killing another required node (#1077)

---

jsk_naoqi_robot/README.md
jsk_naoqi_robot/jsk_pepper_startup/config/jsk_pepper_startup.rviz

- requires: https://github.com/kochigami/naoqi_driver/pull/7, https://github.com/kochigami/naoqi_dashboard/pull/1 => merged in kochigami-develop
- ~need to study more how to transform raw diagnostics to  diagnostics_agg~
- ~need to try this with NAO~
- CPU temperature
- power system
- joints
- network connection
- camera
- joystick
- tf
```
roslaunch jsk_pepper_startup jsk_pepper_startup.launch network_interface:=xxx
cd config
rviz -d jsk_pepper_startup.rviz
```

[jsk_pepper_startup/config] add rviz config

---

jsk_robot_common/jsk_robot_startup/lifelog/time-signal.l

Fix `time-signal.l` in `jsk_robot_startup`
current implementation does not work because of API change.

Fix time signal

---

jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_tools/xdisplay_image_topic.py

add `max_height` and `max_width` parameter for `baxter` `xdisplay_image_topic` node.

add max_height and max_width parameter for xdisplay_image_topic

---

jsk_robot_common/jsk_robot_startup/util/finish_launch_sound.py
jsk_robot_common/jsk_robot_startup/util/start_launch_sound.py

set volume=1.0 for launch sound.
default volume is 0.0.

[jsk_robot_startup] set volume=1.0 for launch sound

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_warning/battery_logger.py

add voltage, current and temperature info for pr2 battery logger
cc. @YutoUchimi @Affonso-Gui

add voltage, current and temperature info for pr2 battery logger

---

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch

we need to set sound_play respawn=true for audio_common bug.
cc. @708yamaguchi @itohdak

[jsk_fetch_startup] respawn fetch sound_play for audio_common bug

---

jsk_robot_common/jsk_robot_startup/lifelog/tweet_client.l

with this PR, the robot wait until a robot finish speaking.
with this PR, fetch can correctly tweet photo by running jsk_fetch_startup/tweet app.

[jsk_robot_startup] wait until speech ends

---

jsk_fetch_robot/fetcheus/fetch-interface.l
jsk_fetch_robot/fetcheus/test/test-fetcheus.l

[fetcheus] Fix :go-velocity to reject non-zero y correctly

---

jsk_fetch_robot/fetcheus/test/test-fetcheus.l

[fetcheus] Add test of :go-velocity

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_warning/cable_warning.l

With this PR, pr2s speaks if they can move.

[jsk_pr2_startup/cable_warning.l] Add moving is OK voice

---

jsk_fetch_robot/jsk_fetch_startup/scripts/battery_warning.py

do not speak often when `is_charging` is `True`.

[jsk_fetch_startup] do not speak often when is_charging is True

---

jsk_fetch_robot/jsk_fetch_startup/config/install_upstart.sh

add ROSCONSOLE_FORMAT for more detailed logging for fetch

[jsk_fetch_startup] add ROSCONSOLE_FORMAT in install_upstart.sh

---

.travis.rosinstall.kinetic
.travis.rosinstall.melodic
.travis.yml

`.travis.rosintall.melodic`
- Baxter repos: https://discourse.ros.org/t/baxter-release-permissions/8705
- app_manager: https://github.com/PR2/app_manager/issues/12
- pepper_robot: https://github.com/ros-naoqi/pepper_robot/issues/50
- naoqi_bridge: https://github.com/ros-naoqi/naoqi_bridge/issues/94
- pr2_robot: https://github.com/PR2/pr2_robot/issues/261

add melodic travis test

---

jsk_robot_common/jsk_robot_startup/lifelog/common_logger.launch

add `debug` arg for `common_logger.launch`
this is useful for debugging common_loggers

[jsk_robot_startup] add debug arg in common_logger

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/move_base.xml
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/pr2_2dnav.launch
jsk_pr2_robot/jsk_pr2_startup/pr2.launch

this PR enables us to use keepout maps for PR2.

[jsk_pr2_startup] add use_map_keepout arg in pr2.launch

---

jsk_pr2_robot/jsk_pr2_startup/pr2_bringup.launch

this PR change `launch_network_detector:=true` for PR2.
we can get network connection information in `/network/connected` topic.

[jsk_pr2_startup] set launch_network_detector true for default

---

jsk_fetch_robot/fetcheus/fetch-utils.l
jsk_fetch_robot/jsk_fetch_startup/euslisp/fetch-look-at-human.l
jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/pr2-look-at-human.l
jsk_pr2_robot/jsk_pr2_startup/pr2.launch
jsk_robot_common/jsk_robot_startup/lifelog/look-at-human.l

Based on [this advice](https://github.com/jsk-ros-pkg/jsk_robot/pull/1297#issuecomment-747180855), I created robot-independent look-at-human program.

[jsk_robot_startup] Look at human for Fetch and PR2

---

jsk_pr2_robot/jsk_pr2_startup/pr2.launch

launch `virtual_force_publisher` in `pr2.launch` by default.
cc. @ishiguroJSK

[jsk_pr2_startup] add virtual_force_publisher to pr2.launch

---

.travis.yml

update .travis to 0.5.21

---

jsk_fetch_robot/jsk_fetch.rosinstall.melodic

I add `jsk_fetch.rosinstall.melodic`.
this .rosinstall is copied from https://github.com/jsk-ros-pkg/jsk_robot/pull/1316
related to: https://github.com/jsk-ros-pkg/jsk_robot/pull/1148

add jsk_fetch.rosinstall.melodic

---

jsk_pr2_robot/jsk_pr2_startup/config/jsk_startup.rviz

this PR update pr2 default rviz config.

[jsk_pr2_startup] update pr2 rviz config

---

jsk_robot_common/jsk_robot_startup/lifelog/automated_logger.py
jsk_robot_common/jsk_robot_startup/lifelog/test/lazy_publisher.py
jsk_robot_common/jsk_robot_startup/lifelog/test/lazy_subscriber.py
jsk_robot_common/jsk_robot_startup/lifelog/test/simulate_lazy.launch

Add automated_logger

---

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
jsk_fetch_robot/jsk_fetch_startup/launch/fetch_teleop.xml
jsk_fetch_robot/jsk_fetch_startup/scripts/battery_warning.py
jsk_fetch_robot/jsk_fetch_startup/scripts/warning.py
jsk_robot_common/jsk_robot_startup/scripts/nav_speak.py

we add `volume` param to change the volume in fetch speaking nodes.
- `nav_speak.py`
- `battery_warning.py`
- `warning.py`
cc. @708yamaguchi

[jsk_fetch_startup] add volume params in several speaking nodes

---

.travis.rosinstall.noetic
jsk_baxter_robot/baxtereus/CMakeLists.txt
jsk_fetch_robot/fetcheus/CMakeLists.txt
jsk_kinova_robot/kinovaeus/CMakeLists.txt
jsk_naoqi_robot/jsk_nao_startup/CMakeLists.txt
jsk_naoqi_robot/naoeus/CMakeLists.txt
jsk_naoqi_robot/naoqieus/CMakeLists.txt
jsk_naoqi_robot/peppereus/CMakeLists.txt
jsk_pr2_robot/jsk_pr2_calibration/CMakeLists.txt
jsk_robot_common/jsk_robot_startup/CMakeLists.txt
jsk_robot_common/roseus_remote/CMakeLists.txt

https://github.com/fetchrobotics/fetch_ros/pull/144, https://github.com/fetchrobotics/fetch_ros/pull/144  are merged in ros1 branch (https://github.com/fetchrobotics/fetch_ros/blob/ros1/fetch_navigation/CHANGELOG.rst) and released as 0.9.0

remove fetch_ros repo from .travis.rosinstall.noetic

---

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch

remove unnecessary robot_localization in `fetch_bringup.launch` because `robot_localization` is in `fetch.launch`.

[jsk_fetch_startup] remove unnecessary robot_localization in fetch_brinup.launch

---

jsk_fetch_robot/jsk_fetch_startup/CMakeLists.txt
jsk_fetch_robot/jsk_fetch_startup/launch/fetch.launch
jsk_fetch_robot/jsk_fetch_startup/package.xml
jsk_fetch_robot/jsk_fetch_startup/robots/base_camera_mount.urdf.xacro
jsk_fetch_robot/jsk_fetch_startup/robots/head_box.urdf.xacro
jsk_fetch_robot/jsk_fetch_startup/robots/jsk_fetch.urdf.xacro

move from #1205
add missing `base_camera_mount.urdf.xacro` and `head_box.urdf.xacro`.
cc. @sktometometo @708yamaguchi

[jsk_fetch_startup] make base_camera_mount and head_box xacro

---

jsk_pr2_robot/jsk_pr2_startup/pr2.launch

this PR launch `dialogflow_task_executive.launch` in `pr2.launch`.

[jsk_pr2_startup] launch dialogflow task executive in pr2.launch

---

.travis.rosinstall

I hope this PR fix travis failure.
https://github.com/jsk-ros-pkg/jsk_robot/pull/1213#issuecomment-929304356

Add :bodies check to fix travis failure

---

jsk_robot_common/jsk_robot_startup/README.md
jsk_robot_common/jsk_robot_startup/euslisp/email-topic-client.l
jsk_robot_common/jsk_robot_startup/euslisp/sample-email-topic-client.l
jsk_robot_common/jsk_robot_startup/launch/sample_email_topic.launch
jsk_robot_common/jsk_robot_startup/msg/Email.msg
jsk_robot_common/jsk_robot_startup/scripts/email_topic.py
jsk_robot_common/jsk_robot_startup/scripts/sample_email_topic_client.py
jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/email_topic_client.py

- Support multiple attachments
- Add client library, example and demo launch
- Update README

Update email topic node

---

jsk_kinova_robot/kinovaeus/kinova-utils.l

Duplicate of https://github.com/sktometometo/jsk_robot/pull/113
Coloring kinova eusmodel with this PR.
|**gen3_lite_gen3_lite_2f**|**gen3_robotiq_2f_85**|**gen3_robotiq_2f_140**|
|:---:|:---:|:---:|
|<img src="https://user-images.githubusercontent.com/67531577/148562723-7b9f1e6c-4e22-4828-8a84-a5570f469ca4.png" width=100%>|<img src="https://user-images.githubusercontent.com/67531577/148562471-605a44cb-cca5-48f7-aaf1-3e0cf651171d.png" width=110%>|<img src="https://user-images.githubusercontent.com/67531577/148562605-c1ad43dc-503a-428b-b14e-ebb3b72c0dad.png" width=100%>|
I also colored the spotkinova model for my thesis in https://github.com/sktometometo/jsk_robot/pull/112

[kinovaeus] Coloring kinova eusmodel

---

jsk_fetch_robot/jsk_fetch_startup/scripts/warning.py

The sound of Fetch's breaker warning was not working these days.
I ffixed it by this PR,

[jsk_fetch_startup] Fix Fetch's breaker warning sound

---

jsk_fetch_robot/jsk_fetch_startup/apps/hello_world/hello_world.xml

`boot_sound.py` is in jsk_robot_startup

[fetch] Fix boot_sound.py package in hello_world app

---

jsk_fetch_robot/jsk_fetch_startup/launch/navigation/fetch_move_base_common_params.yaml
jsk_fetch_robot/jsk_fetch_startup/package.xml

From https://github.com/knorth55/jsk_robot/pull/79
For fetch's move_base improvement.

[jsk_fetch_startup] change global_planner to global_planner/GlobalPlanner

---

jsk_fetch_robot/README.md

Duplicate of knorth55/jsk_robot#109
I add several explanations in Mobile base section and Speak section of Readme.
This PR is an addition to what I thought was missing from the Fetch readme when I was first assigned to the lab.

[jsk_fetch_startup] Add explanation of navigation and speaking of Fetch README

---

jsk_fetch_robot/fetcheus/package.xml

euscollada should be added to build dependency.
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_fetch_robot/fetcheus/CMakeLists.txt#L32-L35

add euscollada and urdf_collada as build dependencies

---

jsk_fetch_robot/jsk_fetch_startup/euslisp/navigation-utils.l

Add local/global-costmap-inflation-radius key.

[jsk_fetch_startup/navigation-utils] Add inflation key

---

jsk_fetch_robot/jsk_fetch_startup/apps/welcome_to_jsk/welcome_to_jsk.app
jsk_fetch_robot/jsk_fetch_startup/apps/welcome_to_jsk/welcome_to_jsk.xml

Cherry-pick https://github.com/knorth55/jsk_robot/pull/257
I update welcome to jsk app.
- Update welcome to jsk code (https://github.com/jsk-ros-pkg/jsk_demos/pull/1354)
- Record demo data and send email
Demo result is sent by email.
```
Welcome to JSK demo: 2022/06/07 (17:11:51)
```

[jsk_fetch_startup] Update welcome to jsk app

---

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_rosserial.launch

Merge after https://github.com/jsk-ros-pkg/jsk_robot/pull/1533
Cherry-pick https://github.com/knorth55/jsk_robot/pull/297
I reset logger level to info for debugging.
I will reset the level to error if there is no problem with rosserial

[jsk_fetch_startup] Reset rosserial logger level for debuging

---

jsk_fetch_robot/jsk_fetch_startup/euslisp/navigation-utils.l

~~Please merge after jsk-ros-pkg#1458.~~
I cherry-picked https://github.com/knorth55/jsk_robot/pull/142 and https://github.com/knorth55/jsk_robot/pull/153.
I updated trashcan front position for Fetch to move faster around the trashcan than before.

[jsk_fetch_startup] Update trashcan front position in kitchen demo

---

.travis.rosinstall.melodic
jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
jsk_fetch_robot/jsk_fetch_startup/launch/fetch_gazebo_bringup.launch
jsk_fetch_robot/jsk_fetch_startup/package.xml

this PR adds `switchbot` in `fetch_bringup.launch`.
this is a part of #1236

[jsk_fetch_startup] add switchbot in fetch_bringup.launch

---

jsk_robot_common/jsk_robot_startup/lifelog/active_user.l

[jsk_robot_startup] fix typo in active_user.l

---

jsk_baxter_robot/jsk_baxter_startup/baxter.launch
jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_lifelog/baxter_tweet.launch
jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_lifelog/db_client.launch

when `spherical_stereo` is enabled, use the camera topic for twitter.

[jsk_baxter_startup] change twitter image in baxter.launch

---

.github/workflows/config.yml

run sudo apt update before debconf

Fix GihubAction

---

jsk_robot_common/jsk_robot_startup/scripts/smach_to_mail.py

This PR enables us to send `INFO` tag to email.
`INFO`  is sent as a message to developers.

[jsk_robot_startup/smach_to_mail] Enable to send INFO tag 

---

jsk_baxter_robot/jsk_baxter_startup/README.md
jsk_baxter_robot/jsk_baxter_startup/baxter_rosbag_play.launch
jsk_baxter_robot/jsk_baxter_startup/baxter_rosbag_record.launch

add baxter rosbag play and record launch for baxter

[jsk_baxter_startup] add baxter rosbag play and record launch

---

jsk_fetch_robot/jsk_fetch_startup/udev_rules/80-arduino.rules

someone left the local change in `fetch1075`, so I commit.
maybe @nakane11 ? or @708yamaguchi ?

[develop/fetch] add new arduino udev rules

---

jsk_fetch_robot/README.md

Update the way to create workspace, as knorth55 -> jsk-ros-pkg migration

[jsk_fetch_robot] update wstool info in readme

---

jsk_robot_common/jsk_robot_startup/config/dualsense_joystick_teleop.yaml

forget to add dock button/axes to jsk_robot_common/jsk_robot_startup/config/dualsense_joystick_teleop.yaml

followup of #1620 (support dock/undock + tuck/untuck)

---

jsk_fetch_robot/jsk_fetch_startup/scripts/update_workspace.sh
jsk_pr2_robot/jsk_pr2_startup/scripts/update_workspace.sh
jsk_robot_common/jsk_robot_startup/scripts/update_workspace_main.sh

[develop/fetch] move update_workspace_main.sh to jsk_robot_startup and use it for fetch and pr2

---

jsk_unitree_robot/cross/build_ros1.sh
jsk_unitree_robot/cross/build_ros1_dependencies.sh
jsk_unitree_robot/cross/install.sh
jsk_unitree_robot/cross/repos/ros1_dependencies.repos
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1001-urdfdom-headers
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1002-urdfdom
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1003-assimp
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1004-colladadom
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1005-yaml-cpp
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1007-snappy
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1008-opencv
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1009-python-sip
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1024-liblcm
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1025-alsa-lib
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1027-jack-audio-connection-kit
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1028-libportaudio2
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1030-flac
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1031-libncurses
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1037-mailutils
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1038-tcl
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1039-expect
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1040-openssl
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1041-libsasl
jsk_unitree_robot/cross/ros1_dependencies_build_scripts/1042-postfix

split from https://github.com/k-okada/jsk_robot/pull/69
add script to install mailutils

[update jsk_unitree_robot/cross/ros1_dependencies_build_scripts] install tcl/expectpostfix/mailutils

---

jsk_fetch_robot/jsk_fetch_startup/apps/go_to_kitchen/go_to_kitchen.xml
jsk_fetch_robot/jsk_fetch_startup/euslisp/navigation-utils.l

originally from @708yamaguchi 
publish co2 concentration in kitchen demo.

Publish CO2 concentration in go-to-kitchen app

---

jsk_fetch_robot/jsk_fetch_startup/scripts/time_signal.py

this PR change `time_signal` app to speak `minute` info, too.
I also chage the schedule a little bit.

update time_signal schedule and speak minute info

---

jsk_fetch_robot/README.md

I tried to setup the environment (For Remote PC) following the README, but I could not connect to the real robot (kinematic simulator launched).
I solved this problem by checking out the branch from `master` to `develop/fetch`.
(@mqcmd196  Thank you for helping me!)

[jsk_fetch_robot] update README for develop/fetch branch

---

jsk_fetch_robot/jsk_fetch_startup/scripts/time_signal.py

this PR fix typo and also speak date when midtime in time_signal

[jsk_fetch_startup] fix typo and speak date when midnight in time signal

---

jsk_fetch_robot/jsk_fetch_startup/euslisp/navigation-utils.l

This is a bug-fix PR.
I made mistakes of report messges and usege of `let*`.

[jsk_fetch_startup] [bugfix] Fix report in kitchen demo

---

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
jsk_fetch_robot/jsk_fetch_startup/launch/fetch_gazebo_bringup.launch

- refactor and add launch_* args in fetch_bringup.launch 
- fix fetch_gazebo_bringup.launch
```bash
roslaunch jsk_fetch_startup fetch_gazebo_bringup.launch
```

fix fetch_gazebo_bringup.launch and refactor & add launch_* args in fetch_bringup

---

jsk_fetch_robot/jsk_fetch_startup/launch/navigation/fetch1075/fetch_move_base_common_params.yaml

- Add https://github.com/jsk-ros-pkg/jsk_robot/pull/1585 and https://github.com/jsk-ros-pkg/jsk_robot/pull/1597
- Update move_base parameter to use them.

[Fetch1075] Add update_move_base_parameter_recovery and complex_recovery

---

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
jsk_robot_common/jsk_robot_startup/scripts/smach_to_mail.py

this PR adds more params for `smach_to_mail` in `fetch_bringup.launch`.
- add more params
- change node name of `smach_to_mail`
- fix typo

[develop/fetch] [jsk_fetch_startup] add more params in fetch_bringup.launch

---

jsk_fetch_robot/jsk_fetch_startup/euslisp/navigation-utils.l

This PR add `(ros::spin-once)` before `(set-alist)` to update the latest photo.
With this PR, the photos matches with the descriptions
|Description| Before | This PR |
|-----------|----------|------------|
|電気がついていたよ|![before_0](https://user-images.githubusercontent.com/9300063/197340687-7588733c-b8b4-4154-b586-50ee71f93688.png)|![after_0](https://user-images.githubusercontent.com/9300063/197341045-354fa927-b47b-4ff3-a860-78f9b05f7c4b.png)|
|電気がついていたよ|![before_1](https://user-images.githubusercontent.com/9300063/197340686-cf1ddea8-b451-44ad-a6a1-4b554dbfdbfb.png)|![after_1](https://user-images.githubusercontent.com/9300063/197341044-cbff3568-92d2-4693-bda3-1f89701c4362.png)|
|ドックの前に移動したよ|![before_2](https://user-images.githubusercontent.com/9300063/197340684-65401933-ee08-4695-9078-31e67e7 …

[develop/feetch][jsk_fetch_startup] add spin-once before image set-alist

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2.rosinstall

this PR update jsk_pr2.rosinstall.
this `jsk_pr2.rosinstall` is copied from `origin/develop/pr2` branch.

[jsk_pr2_startup] update jsk_pr2.rosinstall

---

jsk_fetch_robot/jsk_fetch.rosinstall.melodic

this PR update `jsk_fetch.rosinstall.melodic`.
`jsk_fetch.rosinstall.melodic` is copied from `origin/develop/fetch` branch.

[jsk_fetch_robot] update jsk_fetch.rosinstall.melodic

---

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/check_openni_node.py
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/kinect_head.launch
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/manager.launch.xml
jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/openni.launch

- fix volueme in `check_openni_node.py`
- comment out subprocess of `roslaunch`.
we are testing on pr1040

[WIP] [develop/pr2] fix check_openni_node.py

---

jsk_naoqi_robot/naoqieus/naoqi-interface.l

add speak-jp and speak method

---

jsk_fetch_robot/jsk_fetch_startup/robots/side_hook.urdf.xacro

[Fetch] Update side hook model

---

jsk_robot_common/jsk_robot_startup/lifelog/tweet_client.l

dont play shutter sound when `speak` is `nil`.
we also control the shutter sound by `volume`.

[develop/fetch] camera shutter volume control ad sound only when speak is t 

---

jsk_fetch_robot/jsk_fetch_startup/euslisp/go-to-kitchen.l

I want to process the image in Smach Containers with Large Vision-Language model. For doing it, I want to use clean image, which no information is overlayed.

[jsk_fetch_startup] Change smach image topic in kitchen-demo

---

jsk_fetch_robot/jsk_fetch_startup/config/fetch1075_app_schedule.yaml
jsk_fetch_robot/jsk_fetch_startup/config/fetch15_app_schedule.yaml
jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch

this PR moves `app_schedule.yaml` in `jsk_fetch_startup` and manage the file by git.

[develop/fetch]  move app_schedule.yaml in jsk_fetch_startup

---

jsk_robot_common/jsk_robot_startup/CMakeLists.txt
jsk_robot_common/jsk_robot_startup/cfg/SmachNotificationReconfigure.cfg
jsk_robot_common/jsk_robot_startup/scripts/smach_to_mail.py

This PR supports sending notification for every state transition.
I updated notification parmeter as dynamic reconfigure.

[develop/fetch] [jsk_robot_startup] Support dynamic reconfigure in smach_to_mail to send google chat for every state transition

---

jsk_panda_robot/jsk_panda_teleop/package.xml

this PR add python3 deps for jsk_panda_teleop.
this PR also changes to use format 3.

[jsk_panda_teleop] change python3 deps in jsk_panda_teleop

---

jsk_robot_common/jsk_robot_startup/lifelog/common_logger.launch

tested in https://github.com/jsk-ros-pkg/jsk_robot/pull/1701

add save_faces save_dialogflow save_google_chat to common_logger.launch

---

.github/labeler_conf/develop_fetch_labeler.yml
.github/workflows/develop_fetch_labeler.yml

This PR add a workflow which automatically add `develop/fetch` label to PR if the PR is created to `develop/fetch`.

Add labeler action for develop/fetch

---

.github/labeler_conf/main_labeler.yml
.github/workflows/main_labeler.yml

Add https://github.com/actions/labeler in order to add labels for each robot based on changed directories.
See https://github.com/jsk-ros-pkg/jsk_robot/pull/1814 to check how it works.

Add labeler action

---

jsk_fetch_robot/jsk_fetch.rosinstall.melodic
jsk_fetch_robot/jsk_fetch_startup/config/config.bash
jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch

Use https://github.com/sktometometo/esp_now_ros in fetch1075 by default

[WIP][jsk_fetch_startup][jsk_fetch_robot] add esp_now_ros to launch

---

jsk_fetch_robot/jsk_fetch.rosinstall.melodic

This PR closes #1831.
Until https://github.com/ros-visualization/executive_smach_visualization/pull/54 is merged.

[Fetch] Use bugfix branch of executive_smach_visualization

---

jsk_unitree_robot/cross/build_ros1.sh
jsk_unitree_robot/cross/build_ros1_dependencies.sh

This is the one solution of https://github.com/jsk-ros-pkg/jsk_robot/issues/1857 with reflecting the comment https://github.com/jsk-ros-pkg/jsk_robot/issues/1857#issuecomment-1749862073.
I increased vcs import retry number from 3 to 10 (Is it too many?).

[unicree/cross] Increase retry number of vcs import

---

jsk_fetch_robot/jsk_fetch.rosinstall.melodic

Update esp_now_ros version to 0.4.0

[jsk_fetch_robot] update esp_now_ros version to v0.4.0

---

jsk_unitree_robot/cross/install.sh

Fix https://github.com/jsk-ros-pkg/jsk_robot/issues/1870

[cross] add LANG=C for ping reachability check

---

jsk_robot_common/jsk_robot_startup/launch/robot_database_mongo_server.launch
jsk_robot_common/jsk_robot_startup/lifelog/README.md
jsk_robot_common/jsk_robot_startup/scripts/robot_database_mongo_dump.py
jsk_robot_common/jsk_robot_startup/scripts/robot_database_mongo_example.py

adbe52f1e (Kei Okada, 10 seconds ago)
add information based on   https://github.com/jsk-ros-pkg/jsk_robot/issues/1706
af53a852a (Kei Okada, 19 minutes ago)
add example launch/script for mongo db

add more info on mongodb
