jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/tilt_scan_cloud.launch
it's out of date
We can find collider [here](https://github.com/willowgarage/arm_navigation_experimental), but in order
to re-work it, we need to exert a lot of effort.
=> [jsk_pr2_startup] Disable collider node

jsk_baxter_robot/baxtereus/baxter-interface.l
This will solve the problem of jsk-ros-pkg/jsk_visualization#268.
The segmentation fault was in the actionlib.l's wait-for-result.(I didn't trace under this)
When the spin-once without groupname is called in the CALLBACK(At that time, bax-movemnt-callback), there seems to have something wrong with wait-for-result and crushed. So I added groupname.
=> add groupname for baxter-interface.l

jsk_robot_common/jsk_robot_startup/lifelog/active_user.l, jsk_robot_common/jsk_robot_startup/lifelog/tweet_client_uptime.l, jsk_robot_common/jsk_robot_startup/lifelog/tweet_client_worktime.l
PR2 tweets many times. But it seems to be because the joint moving judge threshold was too low...
The value PR2 always got was around 0.035, but the threshold was 0.0001 so the all time the time was judged as " move".
(This threshold might be different depending on robot)
=> repair tweet lifelog

jsk_robot_common/jsk_robot_startup/CMakeLists.txt, jsk_robot_common/jsk_robot_startup/package.xml
this is necessary for `jsk_robot_startup/lifelog/active_user.l`
=> add diagnostic_msgs, pr2_mechanism_controllers, sensor_msgs to build dependencies

jsk_baxter_robot/baxtereus/CMakeLists.txt, jsk_baxter_robot/baxtereus/baxter-interface.l, jsk_baxter_robot/baxtereus/baxter-util.l, jsk_baxter_robot/baxtereus/package.xml, jsk_baxter_robot/baxtereus/test/test-baxter.l, jsk_baxter_robot/baxtereus/test/test-baxter.test
@aginika, please review this code and merge if this is ok
- [test/test-baxter.{l,test}] add test code for baxter model  (:self-collision-check)
- [baxter-util.l] use :collision-check-paris to get collision link pair,  instaed of combination
- [baxter-util.l] (length args) always retruns non nil, so it never goes to self-collision-check with pairs
- [baxter-interface.l, baxter-util.l] move baxter-robot-safe class definition to baxter-util.l
=> move baxter-robot-safe class to baxter-util.l, fix :self-collision-check and add test code

jsk_baxter_robot/baxtereus/baxter-interface.l
For larm
```
(baxter-init :type :larm-controller)
```
For rarm
```
(baxter-init :type :rarm-controller)
```
For normal
```
(baxter-init)
```
=> [baxtereus] Add type option for baxter-init in baxtereus

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_warning/battery_warning.l
pr2 currently look at average of relative charge, but pr1040 shutdown when there is 6x% left.
so i think using the min of absolute charge is more reliable.
=> speak the percentage of the battery with min charge and it's id 

jsk_baxter_robot/baxtereus/baxter-interface.l
@aginika please confirm if this is ok with real robot
=> [baxter-interface.l] fix wrong joint name in head_controller head-neck-y -> head_pan

jsk_nao_robot/jsk_nao_startup/launch/jsk_nao_startup.launch
ros-naoqi/nao_apps/launch (https://github.com/ros-naoqi/nao_robot/tree/master/nao_apps/launch) を元にして、
nao_apps/launch/speech.launch に名前が変わっているため直しました。
よろしくお願い致します。
=> change name of nao_speech.launch to speech.launch

jsk_pepper_robot/peppereus/pepper-interface.l
I deleted "/" of speech topic in speak method 
in order to keep consistency with advertise topic "speech"
That's because when I executed ```send *ri* :speak "こんにちは"```, this error occurred.
```
[ERROR] [1435115396.024964819]: attempted to publish to topic /speech, which was not previously advertised. call (ros::advertise "/speech") first.
```
Sorry for not finding this error in the first commit.
=> modify speak method

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/costmap_common_params.yaml, jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/global_costmap_params.yaml, jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/local_costmap_params.yaml, jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/move_base.xml, jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/move_base_params.yaml
**NOTE:** please merge after https://github.com/jsk-ros-pkg/jsk_robot/pull/356
This pull req upgrades to hydro-above style move_base params, which contains multi-layered costmap, optional costmap function, and some features.
This was tested to work fine with PR1012.
=> [jsk_pr2_startup/jsk_pr2_move_base] use hydro-after style move_base params

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/db_client.launch, jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/people_detection.launch, jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/pr2_remote_startup.launch, jsk_pr2_robot/jsk_pr2_startup/pr2.launch, jsk_pr2_robot/jsk_pr2_startup/pr2_gazebo.launch
pr2_gazebo.launch is gazebo version of pr2.launch with disabling hardware dependent nodes
Now it works at the development level like image below:
=> [jsk_pr2_startup/pr2_gazebo.launch] add pr2_gazebo.launch

jsk_pepper_robot/peppereus/pepper-interface.l
According to http://doc.aldebaran.com/2-1/naoqi/motion/control-stiffness.html#control-stiffness,
stiffness of joints of the Pepper can be changed in only Head, LArm, RArm, LHand and RHand.
I wrote modified method of ```:send-stiffness-controller```   to change stiffness of one of these joints.
I checked all of them are changed by using this new method, but if there is a problem, please let me know.
=> modify send-stiffness-controller method for pepper

jsk_pr2_robot/jsk_pr2_startup/pr2.launch
In #368 , 
typo
defualt --> default
=> [jsk_pr2_startup] fix typo in pr2.launch

jsk_robot_common/jsk_robot_startup/README.md, jsk_robot_common/jsk_robot_startup/lifelog/mongodb.launch, jsk_robot_common/jsk_robot_startup/lifelog/mongodb_replication_params.yaml
- This feature enables to launch mongodb interfaces for ros using existing mongod instead of launching `mongodb_server.py`(which launches `mongod` as subprocess. this seems to be troublesome on multiusers environment.)
This feature is assumed to be used with `mongodb_store` after merged https://github.com/strands-project/mongodb_store/pull/139
- automatically replicate to jsk robot-database server when launching `mongo.launch`
=> [jsk_robot_startup] support daemon mode mongod; enable replication to jsk robot-database

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2.rosinstall
This PR adds .rosinstall to install packages needed for executing below:
- `robot start`
- `roslaunch jsk_pr2_startup pr2.launch`
- `roslaunch detect_cans_in_fridge201202 startup.launch`
- `rosrun detect_cans_in_fridge201202 main.l`
This rosinstall file includes some packages added temporally for various reason, which should be removed after resolving problems.
=> [jsk_pr2_startup] add rosinstall for jsk pr2

jsk_nao_robot/jsk_nao_startup/CMakeLists.txt, jsk_pepper_robot/peppereus/CMakeLists.txt
this is blonking , for example , https://travis-ci.org/jsk-ros-pkg/jsk_robot/jobs/75220393
```
[peppereus] -- Found Threads: TRUE                                              
[peppereus] -- Found gtest sources under '/usr/src/gtest': gtests will be built 
[peppereus] -- Using Python nosetests: /usr/bin/nosetests-2.7                   
[peppereus] -- catkin 0.6.14                                                    
[peppereus] -- Using these message generators: gencpp;geneus;genlisp;genpy      
[peppereus] CMake Error at /opt/ros/indigo/share/naoqi_driver/cmake/naoqi_driverConfig.cmake:141 (message): 
[peppereus]   Project 'peppereus' tried to find library 'naoqi_driver_node'.  The library 
[peppereus]   is neither a target nor built/installed properly.  Did you compile project …
```
=> do not add naoqi_driver in find_package

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/local_costmap_params.yaml
As we can see in https://github.com/search?q=costmap+plugins+name&type=Code&utf8=%E2%9C%93 and http://wiki.ros.org/hydro/Migration#Navigation_-_Costmap2D,
costmap plugin's inflation should be after the obstacles.
This will change the below (Only Obstacles you can see)
To (You can see both obstacles and costmap)
=> [jsk_pr2_startup] change the order of local costmap plugin

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/objectdetection_db.py
for support applications that publish msgs without "_agg" topic
=> [jsk_pr2_startup/jsk_pr2_lifelog/objectdetection_db.py] store NOT '_agg' topics instead of '_agg'

jsk_pr2_robot/jsk_pr2_startup/pr2_bringup.launch
because dump-ing replication data on /tmp exceeds pr2 internal hdd.
=> [jsk_pr2_startup/pr2_bringup.launch] use replication dump temp path on /removable instead of /tmp

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/action_result_db.py
This PR supresses a lot of warning
=> [jsk_pr2_startup/jsk_pr2_lifelog/action_result_db.py] fix: ignore useless type subscription

jsk_pr2_robot/jsk_pr2_startup/plugin.xml
Without this PR, on the top level of the list of all rqt plugins there's `Hoge`.
=> [jsk_pr2_startup] Wording in plugin description

jsk_pepper_robot/README.md, jsk_pepper_robot/jsk_pepper_startup/launch/jsk_pepper_startup.launch, jsk_pepper_robot/jsk_pepper_startup/nodes/joy-client.l, jsk_pepper_robot/jsk_pepper_startup/package.xml, jsk_pepper_robot/peppereus/pepper-interface.l
@kochigami since pepper_bringup has been updated we have to change jsk_pepper_startup.launch, please check if your demo program is running with this new environment.
=> fix to include pepper_full.launch for pepper_bringup > 0.1.4

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_warning/battery_debug_log.py, jsk_pr2_robot/jsk_pr2_startup/pr2.launch
This will create **/var/ros/battery_debug_log/battery_debug.log**
which mark down info of battery with minimum charge in each battery set before every shutdown.
(replace existed data if the started date of the system does not change)
FYI
There is an other log similar which contains info of all times created by **pr2_power_drivers** in /var/ros/power_monitor/power.log
```
system started date(s)|date|ID|Rel.(%)|Abs.(%)|Voltage(mV)|Temperture(C)|
1443500604 Sun Oct 18 08:26:51 PDT 2015 0.2 97 71 16588 38.55
1443500604 Sun Oct 18 08:26:49 PDT 2015 1.0 96 96 16517 41.85
1443500604 Sun Oct 18 08:26:50 PDT 2015 2.0 100 67 16433 31.85
0443500604 Sun Oct 18 08:26:49 PDT 2015 3.0 98 99 16543 36.95
system started date(s)|date|ID|Rel.(%)|Abs.(%)|Voltage(mV)|Temperture(C)|
1443500604 Sun Oct 18 …
```
=> Record battery info before power go off

jsk_robot_common/jsk_robot_startup/config/OdometryFeedbackWrapperReconfigure.cfg, jsk_robot_common/jsk_robot_startup/launch/odometry_integration.launch, jsk_robot_common/jsk_robot_startup/launch/particle_odometry.launch, jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/OdometryFeedbackWrapper.py, jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/OdometryOffset.py, jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/ParticleOdometry.py
I'm sorry for large PR.
- Use odometry integration when feedback odometry
- simple overwrite caused particle degeneracy in ParticleOdometry.
- Calculate transformation instead of integrate velocity from odometry sources.
- accumulating errors of velocity integration was not small enough to be ignored.
- Fix calculation method for rotation
- previous method used euler angle but its singularity causes angle jump around pi rotation in yaw angle.
=> Integrate odometry when feedback

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/initialpose_publisher.l, jsk_pr2_robot/jsk_pr2_startup/sample/pr2_gazebo_610.launch, jsk_pr2_robot/jsk_pr2_startup/sample/pr2_gazebo_73b2.launch
assumes merge after #516 
This informs initial pose of spawned pr2 model to `amcl` module.
=> [jsk_pr2_startup] add initial pose publisher for gazebo

jsk_robot_common/jsk_robot_startup/CMakeLists.txt, jsk_robot_common/jsk_robot_startup/config/HRP2JSKNT_odometry_params.yaml, jsk_robot_common/jsk_robot_startup/config/OdometryFeedbackWrapperReconfigure.cfg, jsk_robot_common/jsk_robot_startup/config/OdometryOffsetReconfigure.cfg, jsk_robot_common/jsk_robot_startup/config/default_odometry_params.yaml, jsk_robot_common/jsk_robot_startup/launch/biped_localization.launch, jsk_robot_common/jsk_robot_startup/launch/particle_odometry.launch, jsk_robot_common/jsk_robot_startup/launch/viso.launch, jsk_robot_common/jsk_robot_startup/scripts/CameraToBaseOffset.py, jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/OdometryFeedbackWrapper.py, jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/OdometryOffset.py, jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/ParticleOdometry.py, jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/odometry_utils.py
Related to https://github.com/jsk-ros-pkg/jsk_common/issues/1284
Please merge after #523
=> Remove unnecessary tf to reduce tf execution rate

jsk_pr2_robot/README.md
* ln ではjsk_robotが更新されず、wstool updateを行っても新しいtagなどが反映されないので、直接cp
=> ln -> cp in README

jsk_naoqi_robot/naoqieus/naoqi-interface.l
I added three methods related to AutonomousLife.
<example>
```
roslaunch jsk_pepper_startup jsk_pepper_startup.launch 
roseus pepper-interface.l
(send *ri* :enable-life) => ALife is set to solitary
(send *ri* :disable-life) => ALife is set to disabled
(send *ri* :get-life) => "[INFO] [WallTime: 1456383415.933722] Current Life State: solitary" appeared in the launched terminal
```
前のプルリクエストで☓がついているのに顧みず，新しいものを送ってしまい申し訳ございません．
=> [naoqieus] :enable-life, :disable-life, :get-life are added

jsk_naoqi_robot/jsk_nao_startup/launch/jsk_nao_startup.launch
jsk_nao_startup.launch を，
jsk_pepper_startup.launchのように変更しました．
立ち上がるノードは以下です．
```
/image_saver
/nao_audio
/nao_robot/naoqi_driver_node
/nao_robot/pose/pose_controller
/nao_robot/pose/pose_manager
/nao_speech
/nao_twitter
/nao_vision
/rosout
/rostwitter
```
=> [jsk_nao_startup] Delete force_python option and add new parameters for naoqi_driver.launch

jsk_naoqi_robot/naoqieus/naoqi-interface.l
#581 での問題を解決しました．
```
send *ri* :start-grasp :rarm 0.7 => 範囲は0.0~0.5ですと出て，0.5が代入される．
send *ri* :start-grasp 0.7 :rarm => 今回のプルリクエストで，この場合も範囲の警告が出て，0.5が代入されるようになった
```
=> [naoqieus] fixed program when the order of two optional params is upside down

jsk_fetch_robot/fetcheus/fetch.yaml
**before**
**after**
Modified:
- jsk_fetch_robot/fetcheus/fetch.yaml
=> [fetcheus] Fix arm end coords of 'fetch.l'

jsk_robot_common/jsk_robot_startup/config/JAXON_RED_odometry_params.yaml, jsk_robot_common/jsk_robot_startup/launch/particle_odometry.launch, jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/ParticleOdometry.py
for more constant pointcloud integration
=> Use only important partilces when estimating output distribution of particle odom 

jsk_naoqi_robot/jsk_pepper_startup/sample/sample.l
```
roscd jsk_pepper_startup/sample
roseus sample.l
```
returns 
```
ERROR th=0 no such package "NAOQI_MSGS""NAOQI_MSGS" in #<compiled-code #X4e77910>E:
```
Therefore I changed ```naoqi_msgs``` to ```naoqi_bridge_msgs```.
% I tried this sample with my pretty Pepper and
```
roslaunch jsk_pepper_startup jsk_pepper_startup.launch 
roslaunch nao_apps speech.launch nao_ip:=NAO_IP
roslaunch nao_interaction_launchers  nao_vision_interface.launch  nao_ip:=NAO_IP
roslaunch nao_apps behaviors.launch nao_ip:=NAO_IP
roscd jsk_pepper_startup/sample & roseus sample.l
```
=> I'll update README.
=> [jsk_pepper_startup/sample] change from naoqi_msgs to naoqi_bridge_msgs

jsk_pr2_robot/jsk_pr2_startup/CMakeLists.txt, jsk_pr2_robot/jsk_pr2_startup/package.xml
c.f. : https://github.com/jsk-ros-pkg/jsk_robot/pull/591 
this cause failing on deb builder -> http://build.ros.org/view/Ibin_uT64/job/Ibin_uT64__jsk_pr2_startup__ubuntu_trusty_amd64__binary/90/console
=> fix too long file name in deb build

jsk_fetch_robot/fetcheus/fetch-interface.l
need to use collisions free-path when we send arbitary pose to :reset-pose in fetch robot
=> feteus-interface.l : always use moveit within :angle-vector

jsk_baxter_robot/baxtereus/baxter-interface.l, jsk_baxter_robot/baxtereus/test/test-baxter.l
fixes https://github.com/jsk-ros-pkg/jsk_robot/issues/621
baxterは`:ros-state-callback`の中で，
joint_statesトピックで受け取ったデータから`torso_t0`ジョイントを除去していますが，
そこにバグがあるようなので修正しました．
スロット変数の`robot-state`はいらないように思います．
実機でエラーなく正しく`torso_t0`ジョイントが除去されることを確認しました．
BaxterユーザのどなたかにReviewいただいた上でマージして欲しいです．
=> [baxter-interface.l] fix removing torso joint in :ros-state-callback

jsk_baxter_robot/baxtereus/CMakeLists.txt, jsk_baxter_robot/baxtereus/baxter-interface.l, jsk_baxter_robot/baxtereus/test/test-baxter.l
@pazeshun #627
```
Thanks to #622 
This PR is for baxter joint trajectory action server which needs the initial joint states.
Without this PR, arms sometimes move suddenly when several types of /robot/joint_states exist.
```
This PR should fail for all distro since robot-state is not update until we explicitly 
call :robot-interface-simulation-callback within :wait-until-update-all-joints (https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/238)
- baxtereus: run test only for hydro
- Wait until all joint states are updated before moving
=> [baxter-interface.l] Wait until all joint states are updated before moving #627

jsk_robot_common/jsk_robot_startup/launch/multisense_local.launch
https://github.com/start-jsk/rtmros_hrp2/pull/414 の変更で，台車型のロボットについても
multisense_localを上げられるようにUSE_BIPED_LOCALIZATIONの変数を加えました．
=> [jsk_robot_startup/multisense_local.launch] Add biped_localization flag

jsk_robot_common/jsk_robot_startup/util/finish_launch_sound.py, jsk_robot_common/jsk_robot_startup/util/start_launch_sound.py
`PLAY_START` means starting repeating.
Current codes in `sound_play` does not support repeating, so it plays only once at now. 
I fixed the upstream, so this code should also be fixed.
https://github.com/ros-drivers/audio_common/pull/77
=> [jsk_robot_common/jsk_robot_startup/util/start_launch_sound.py] PLAY_START -> PLAY_ONCE

jsk_baxter_robot/baxtereus/baxter-interface.l
This will generate smoother motion, expecting not to produce jerkey motion specially the end of the trajectory
this code is introduced in https://github.com/jsk-ros-pkg/jsk_robot/pull/289, and @wkentaro said `I think this works. why don't you merge this?` so may be no longer need this code at some point...
Only tested on the gazebo, need to test on the real robot
=> adding new point just befor the final point produce jerkey motion

jsk_baxter_robot/baxtereus/baxter-interface.l
this requries https://github.com/RethinkRobotics/baxter_interface/pull/73, if you run JTA with this feature, this procedure is done within joint_trajectory_action_server.py
see https://github.com/jsk-ros-pkg/jsk_robot/pull/635 for more detail
=> JTA insert current position to the first point,

jsk_naoqi_robot/peppereus/pepper.yaml
https://github.com/jsk-ros-pkg/jsk_roseus/issues/470
使ったリンクは CameraTop_frame, r_gripper, l_gripper, base_footprint
base_footprint と CameraTop_frameの座標の向きは同じなため、座標系回転も同じにしました。
手先 end-coords の平行移動は目分量です。
=> [peppereus] add head, larm, rarm, rleg end coords to yaml file

jsk_robot_common/jsk_robot_startup/launch/biped_localization.launch, jsk_robot_common/jsk_robot_startup/launch/multisense_local.launch, jsk_robot_common/jsk_robot_startup/launch/particle_odometry.launch, jsk_robot_common/jsk_robot_startup/launch/rtabmap.launch
integrate https://github.com/start-jsk/rtmros_choreonoid/pull/194
=> [jsk_robot_startup] Add launch files for rtabmap

jsk_naoqi_robot/README.md
When I ran the command in "for developers" below, it returned the error.
```
wstool set pepper_robot --git pepper_robot http://github.com/ros-naoqi/pepper_robot
=>
Error: Too many arguments.
wstool set [localname] [[SCM-URI] --(svn|hg|git|bzr) [--version=VERSION]?]?
```
I changed it as follows.
```
wstool set pepper_robot --git http://github.com/ros-naoqi/pepper_robot
=>
Add new elements:
pepper_robot   	git  http://github.com/ros-naoqi/pepper_robot   
Continue: (y)es, (n)o: y
Overwriting /home/kochigami/catkin_ws/src/.rosinstall
Config changed, remember to run 'wstool update pepper_robot' to update the folder from git
```
=> [jsk_naoqi_robot/README.md] delete unnecessary local name "pepper_robot"

jsk_naoqi_robot/peppereus/pepper.yaml
#637 のrlegのendcoordsをz軸上向きに直しました。
ただ、
``` (send *pepper* :fix-leg-to-coords (make-coords) :rleg)```
``` (send *pepper* :fix-leg-to-coords (make-coords))```
``` (send *pepper* :fix-leg-to-coords (make-coords :pos #f(100 0 0)))```
``` (send *pepper* :fix-leg-to-coords (make-coords :pos #f(100 0 0)) :rleg)```
等してもIRT viewerは更新されず、どうすれば直るのかはこれから考えます。
```
send *pepper* :arms :shoulder-p :joint-angle 10
load "models/arrow-object.l"
setq *arrow1* (arrow)
setq *arrow2* (arrow)
setq *arrow3* (arrow)
setq *arrow4* (arrow)
send *arrow1* :move-to (send (send *pepper* :head :end-coords) :worldcoords)
send *arrow2* :move-to (send (send *pepper* :larm :end-coords) :worldcoords)
send *arrow3* :move-to (send (send *pepper* :rarm :end-coords) :worldcoords)
send *arrow4* :move-to (send (send *pepper* :rleg …
```
=> [peppereus] rotation of rleg endcoords modified

jsk_naoqi_robot/naoqieus/naoqi-interface.l
This is euslisp method for https://github.com/ros-naoqi/naoqi_bridge/pull/48
(enable/disable safety reflex of some body parts)
how to use
```
roslaunch jsk_pepper_startup jsk_pepper_startup.launch
roslaunch naoqi_apps externalCollisionAvoidance.launch nao_ip:=<Pepper's IP>
roseus pepper-interface.l
(send *ri* ::set-external-collision-protection-status 2 nil) ;; 2: Arms nil: disabled
```
related msg and srv files
https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/6
(Note: for ```:get-external-collision-protection-status``` I'll change the pull-request of naoqi_bridge.)
=> [naoqieus] add set-external-collision-protection-status method

jsk_robot_common/jsk_robot_startup/CMakeLists.txt
removed roseus from find_package in CMakeLists.txt in order to build successfully.
=> [jsk_robot_startup] removed unnecessary packages from find_package in CMakeLists.txt

jsk_naoqi_robot/naoeus/nao-interface.l, jsk_naoqi_robot/naoqieus/naoqi-interface.l, jsk_naoqi_robot/peppereus/pepper-interface.l
```
send *pepper* :head :neck-p :joint-angle 20
send *ri* :angle-vector (send *pepper* :angle-vector)
```
でgazeboでもペッパーを動かすようにしました。手と、ホイールはまだ非対応です。
やり方が正しい自信がなく、何かご意見を頂けるとありがたいです。
問題：
１．実装の仕方について
そもそも``` :angle-vector``` をオーバーライドするので良いのか。他のロボットではどうしているのでしょうか。
２．gazeboを立ち上げていることをどうやって判断するのか
今は ```*ri*``` としてシミュレータが上がっていたら、gazeboのトピックも無条件に出すようになっています。
行ったこと：
``` send *pepper* :head :neck-p :joint-angle 10 ```などで
角度列 ```send *pepper* :angle-vector``` は上書きされていくが、
```send *ri* :angle-vector (send *pepper* :angle-vector) ``` がシミュレーションモードで呼び出された時点で、角度列の要素を各コントローラのトピックを出すメソッド ( ```:gazebo-head-controller``` など) に渡す
（参考）コントローラで担当する関節名の並び
```
rosparam get /pepper_dcm/Head_controller/joints　[HeadYaw, HeadPitch]
rosparam get /pepper_dcm/LeftArm_controller/joints  [LShoulderPitch, LShoulderRoll, …
```
=> [peppereus] add gazebo controller method

jsk_naoqi_robot/pepper.rosinstall
Based on the changing history of pepper.rosinstall, I think ```http``` is typo.
If it is not necessary, I'll close this. Sorry for my trouble.
=> [jsk_naoqi_robot] change http to https

jsk_naoqi_robot/naoeus/CMakeLists.txt, jsk_naoqi_robot/peppereus/CMakeLists.txt
I'd like to have manifest.l of peppereus by just executing ```catkin b peppereus```. (reference: #678)
(Even though I can't test it on Nao (jsk_nao_startup) because Nao goes to travel now, I added same change like peppereus.)
If there is any problem, please let me know. Sorry for my trouble.
=> [jsk_naoqi_robot] add roseus in find_package

jsk_naoqi_robot/jsk_nao_startup/launch/jsk_nao_startup.launch, jsk_naoqi_robot/jsk_nao_startup/package.xml, jsk_naoqi_robot/jsk_pepper_startup/launch/jsk_pepper_startup.launch, jsk_naoqi_robot/jsk_pepper_startup/package.xml, jsk_robot_common/jsk_robot_startup/lifelog/speaking-program-is-started-or-terminated.l
This is what I want in https://github.com/jsk-ros-pkg/jsk_robot/issues/664
I think this should be written by a simple way in the future though...
- prepare jsk_naoqi_startup package 
- prepare node about speech
- add function which speaks when launch is killed to ```rospy.on_shutdown```
I tested this with Nao and Pepper
```
roslaunch jsk_nao(pepper)_startup jsk_nao(pepper)_startup.launch 
(press C-c)
Nao (Pepper) speaks "launch is killed" in Japanese
```
=> [jsk_naoqi_robot] speak when launch is killed

jsk_pr2_robot/jsk_pr2_startup/pr2_gazebo.launch
`<env name="NAME" value="$(optenv NAME default_value)" />` do the trick if you want to set default value to environment variables.
=> [jsk_pr2_startup/pr2_gazebo.launch] add default environment variables for launching pr2 gazebo

jsk_naoqi_robot/jsk_nao_startup/package.xml
I think the problem below may be solved by the pull request.
```
roslaunch jsk_nao_startup jsk_nao_startup.launch 
... logging to /home/kochigami/.ros/log/218f6800-9a78-11e6-8cbd-507b9d20c4fb/roslaunch-kochigami-ThinkPad-T450-20314.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.
Traceback (most recent call last):
File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/__init__.py", line 307, in main
p.start()
File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
self._start_infrastructure()
File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/parent.py", line 217, in _start_infrastructure
self._load_config()
File …
```
=> [jsk_nao_startup] add nao_bringup to run depend

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch, jsk_fetch_robot/jsk_fetch_startup/launch/fetch_gazebo_bringup.launch, jsk_fetch_robot/jsk_fetch_startup/launch/gazebo/fetch_gazebo_73b2.launch, jsk_fetch_robot/jsk_fetch_startup/package.xml
this is rewrited version of #671, 
still depends on https://github.com/fetchrobotics/fetch_gazebo/pull/16 and https://github.com/jsk-ros-pkg/jsk_demos/pull/1206
```
roslaunch jsk_fetch_startup fetch_gazebo_73b2.launch
```
(you need to run rviz manually)
- add gazebo/fetch_gazebo_73b2.launch
- add fetch_gazebo_bringup.launch
- fetch_bringup.launch: cleanup launch file
- fetch_bringup.launch: add launch_move_base args
- fetch_bringup.launch: add launch_moveit args
- add fetch_driver_msgs to package.xml
=> [jsk_fetch_startup] add fetch bringup launch files for gazebo

jsk_naoqi_robot/naoqieus/naoqi-interface.l
`:move-hand` にgazeboの場合の処理を追加しました。
手の関節は `send *ri* :angle-vector` で指令角が送られる関節角のリストに入っていないので、
- `~A/Right(Left)Hand_controller/command (pepper_dcm, nao_dcm)` のトピックで手を開閉できるように
- 手のコントローラを削除 (:dcm-lhand-controller, :dcm-rhand-controller)
するようにしました。
=> [naoqieus] add grasp method in gazebo

jsk_baxter_robot/baxtereus/baxter-interface.l
it succeeded in both simulation and real world. 
in simulation https://drive.google.com/open?id=0B5DV6gwLHtyJVEc4SnhxTjVzOG8
In real robot https://drive.google.com/open?id=0B5DV6gwLHtyJR0hpaDBoWVFMeE0
=> [baxtereus] add moveit in baxter-interface

jsk_baxter_robot/baxtereus/baxter-interface.l
- add srdf description
- add baxter config init option in baxter-interface
this option is needed for customize baxter like jsk_baxter_apc
```
$ roscd jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc
$ roseus baxter-interface.l
configuring by "/opt/ros/indigo/share/euslisp/jskeus/eus//lib/eusrt.l"
;; readmacro ;; object ;; packsym ;; common ;; constants ;; stream ;; string ;; loader ;; pprint ;; process ;; hashtab ;; array ;; mathtran ;; eusdebug ;; eusforeign ;; coordinates ;; tty ;; history ;; toplevel ;; trans ;; comp ;; builtins ;; par ;; intersection ;; geoclasses ;; geopack ;; geobody ;; primt ;; compose ;; polygon ;; viewing ;; viewport ;; viewsurface ;; hid ;; shadow ;; bodyrel ;; dda ;; helpsub ;; eushelp ;; xforeign ;; Xdecl ;; Xgraphics ;; Xcolor ;; Xeus ;; Xevent ;; Xpanel …
```
=> [baxtereus] add moveit init option in baxter-interface

jsk_fetch_robot/fetcheus/fetch-interface.l
Increase default effort to 40, avoiding malfunction due to lack of grasping power.
=> [fetch-robot] set effort to 40 in :go-grasp

jsk_baxter_robot/baxtereus/baxter-interface.l
MERGE AFTER #719 
Before                       After
`:angle-vector`             -> `:angle-vector-raw`
`:angle-vector-sequence`    -> `:angle-vector-sequence-raw`
`:angle-vector-motion-plan` -> `:angle-vector`
related to https://github.com/jsk-ros-pkg/jsk_robot/pull/716#issuecomment-259861725 and https://github.com/jsk-ros-pkg/jsk_robot/pull/716#issuecomment-259869688
it works with simulation and real robot
=> [baxtereus] override :angle-vector and rename existing methods

jsk_baxter_robot/baxtereus/baxter-interface.l
- fix bug in `angle-vector` 
use :move-arm as key and pass other args to other methods
currently args passing was not proper (actually `tm` was not passed properly)
usage of angle-vector in robot-interface is as below.
`(send *ri* :angle-vector tm)`
Therefore, for compatibility, set `:move-arm` as key.
`(send *ri* :angle-vector av tm :move-arm :rarm)`
and we can use existing usage of `:angle-vector` as below
`(send *ri* :angle-vector av 3000 nil 0)`
- refine warning messages
- remove tab and use space in baxter-interface
- fix typo in `baxter-interfacel.l`
=> [baxtereus] Fix bug to pass args in :angle-vector

jsk_baxter_robot/baxtereus/baxter-interface.l
- add moveit-environment configuration `:arms` for baxter_moveit_config "both_arms"
```lisp
(send *ri* :angle-vector av 3000 nil 0 :move-arm :arms)
(send *ri* :angle-vector-sequence avs :fast nil 0 :move-arm :arms)
;; both arms are planned by move_group "both_arms"
```
=>  [baxtereus] add :arms for baxter_moveit_config "both_arms"

jsk_baxter_robot/baxtereus/baxter-interface.l, jsk_baxter_robot/baxtereus/baxter-util.l
Requires https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/259
- add `:angle-vector-sequence` for moveit
`:angle-vector-sequence` -> `:angle-vector-sequence-motion-plan`
- fix typo in `baxter-util.l`
=> [baxtereus] add :angle-vector-sequence for moveit

jsk_baxter_robot/baxtereus/baxter-interface.l
- add ctype in angle-vector for moveit
- add ctype in angle-vector-sequence for moveit
- use &key instead of &rest in baxter `angle-vector` methods
=> [baxtereus] add ctype in angle-vector methods for moveit

jsk_baxter_robot/baxtereus/baxter-interface.l
Merge after #730
What Changed
- execure angle-vector-raw in case tm is not number
- execure angle-vector-sequence-raw in case tm is not number
common case is:
```
(send *ri* :angle-vector-sequence avs :fast nil 0)
```
=> [baxtereus] execute raw angle-vector methods in case tm is not number

jsk_baxter_robot/baxtereus/baxter-interface.l
What changed
-  pass `args` to `angle-vector-motion-plan` in baxtereus
we can pass constraints (i.e. `path_constraints`) from `:angle-vector` methods
- add `moveit` option in baxter-init
=> [baxtereus] pass args to angle-vector-motion-plan

jsk_baxter_robot/baxtereus/baxter-interface.l
- pass arm as symbol in `:commamd-grasp`
```lisp
(send *ri* :command-grasp "calibrate" :arms :pos 100)
```
- pass pos in `calib-grasp`
- this is a typo
=> [baxtereus] fix bug in :command-grasp and :calib-grasp

jsk_baxter_robot/baxtereus/baxter-interface.l
To use ~~https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/244~~ https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/273
=> [baxtereus] Use end-coords-interpolation

jsk_baxter_robot/baxtereus/baxter-interface.l, jsk_baxter_robot/baxtereus/test/test-baxter-moveit.l
Requires https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/297
- support tm `:fast` in moveit `:angle-vector` and `:angle-vector-sequence` methods
- update doc
=> [baxtereus] support tm :fast in moveit angle-vector methods

jsk_fetch_robot/fetcheus/fetch-interface.l
this is rewrited version of #791 
related to https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/302, some people like old `:angle-vector` API, like
```
:angle-vector av tm :use-torso t
```
currently we have to use
```
:angle-vector av tm nil 0 :use-torso t
```
=> [Fetch] jsk_fetch_robot/fetcheus/fetch-interface.l :angle-vector, :angle-vector-sequence supports old API

jsk_naoqi_robot/peppereus/pepper.yaml
- move head end coords to depth camera side from top camera side (located at forehead)
- reference: http://doc.aldebaran.com/2-5/family/pepper_technical/kinematics_pep.html#pepp-urdf-files
it says
```
<joint name="CameraTop_sensor_fixedjoint" type="fixed">                                                      
<origin xyz="0.0868 0 0.1631" rpy="0 -0 0" />  
<joint name="CameraDepth_sensor_fixedjoint" type="fixed">                                                    
<origin xyz="0.05138 0.039 0.1194" rpy="0 -0 0" />                                                           
```
Therefore I just calculated 0.1631 - 0.1194 = 0.0437
result:
=> [peppereus] move head end coords to depth camera side

jsk_baxter_robot/baxtereus/baxter-util.l
too many ros::ros-info output when using baxter
=> [baxtereus] suppress ros-info output in baxter ik

jsk_fetch_robot/fetcheus/fetch-interface.l
fetchの`/joint_states`にはグリッパに関するトピックが多く、
`(send *ri* :state :potentio-vector)`
としても、現在の実機の`angle-vector`が取得できないことがあったので、
デフォルトで`:wait-until-update t`がつくようにしました。
=> fetchの:state :potentio-vector

jsk_fetch_robot/fetcheus/fetch-interface.l, jsk_fetch_robot/fetcheus/test/test-fetcheus.l
Fixes https://github.com/jsk-ros-pkg/jsk_robot/issues/839
rewrited versoin of https://github.com/jsk-ros-pkg/jsk_robot/pull/841
fetch interface have problems on trajectory interpolation after cancel , (maybe) when the original trajectory goes over 180 degree ( https://github.com/fetchrobotics/robot_controllers/issues/33 )
This PR fixes by sending interpolated angle-vector-sequence within :angle-vector-raw
=> add interpolation in :angle-vector-raw

jsk_fetch_robot/fetcheus/fetch-interface.l, jsk_fetch_robot/fetcheus/test/test-fetcheus.l
`(send *ri* :wait-interpolation)`がないと、
```
(setq diff-av (v- (send *ri* :state :potentio-vector) (send *fetch* :angle-vector)))
```
の`(send *ri* :state :potentio-vector)`が正しく更新されない気がします。
=> add :wait-interpolation in test

jsk_naoqi_robot/README.md
add trouble shooting based on the discussion of #842
=> [jsk_naoqi_robot/README] add trouble shooting

jsk_fetch_robot/jsk_fetch.rosinstall
we need PR: https://github.com/fetchrobotics/fetch_ros/pull/66
`ApplyPlanningScene` is now required for `pr2eus_moveit`.
=> [jsk_fetch_robot] use fetch_moveit_config 0.7.13

jsk_fetch_robot/fetcheus/fetch-interface.l
シミュレーションモードで
```
(send *ri* :start-grasp)
```
とすると関数から帰ってきません。間違えているようにお思います。
返り値はtですが、なにか
```
(instance control_msgs::GripperCommandActionResult :init)
```
とか埋めたほうがいいでしょうか。
=> enable to run go-grasp on kinematic simulation mode

jsk_baxter_robot/baxtereus/baxter-interface.l
- use ros::load-ros-manifest in baxtereus
- remove unnecessary speak.l load
=> [baxtereus] use ros::load-ros-manifest

jsk_fetch_robot/fetcheus/CMakeLists.txt, jsk_fetch_robot/fetcheus/fetch-interface.l, jsk_fetch_robot/fetcheus/package.xml
[robot-interface.l](https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/robot-interface.l#L1038-L1042) states clearly that `:gripper` method should be defined in child classes, but `fetch-interface` had none defined.
Wrote based on `pr2-interface.l`, with the difference that it doesn't take `arm` argument, since fetch only has `:rarm`.
**Known problem:** fetch's gazebo simulation does not support /gripper_state topic. Currently inquiring fetch-robotics about this.
@708yamaguchi
=> Add :gripper method to fetch-interface

jsk_fetch_robot/fetcheus/fetch-interface.l
#883 をうけて、`:go-grasp`のデフォルトのeffortを50にしました。
=> [fetch] set default effort 50 in :go-grasp

jsk_naoqi_robot/README.md, jsk_naoqi_robot/jsk_pepper_startup/README.md, jsk_naoqi_robot/naoeus/README.md, jsk_naoqi_robot/naoqieus/README.md, jsk_naoqi_robot/peppereus/README.md
I split the contents of README under jsk_naoqi_robot because they are hard to read it.
In addition, I added the explanation of package configuration because the relationship of each package seems to be complicated.
What I did is below:
1. split README of jsk_naoqi_robot to
- naoeus
- jsk_pepper_startup
- peppereus
2. added README of naoqieus
3. modified README of jsk_naoqi_robot (wrote package configurration)
=> [jsk_naoqi_robot] split README because the contents are large

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_lifelog.xml, jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/db_client.launch, jsk_robot_common/jsk_robot_startup/lifelog/action_logger.py, jsk_robot_common/jsk_robot_startup/lifelog/common_logger.launch, jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/lifelog/action_logger.py, jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/lifelog/base_trajectory_logger.py, jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/lifelog/logger_base.py, jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/lifelog/mongo_record.py, jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/lifelog/object_detection_logger.py, jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/lifelog/tf_logger.py
This PR includes the features as follows:
- Enabling an option to log action for PR2 / fetch robots
- Add option to throttle action topics
- Use `update_rate` param for adjusting throttling for logging nodes (previously, various names are used in each node)
And this PR also includes some fixes:
- Bugfixes (typo)
- Add option to use `amcl` for logging base trajectory in order to support logging covariances of robots
=> Action logging with throttling topics

jsk_naoqi_robot/naoqieus/naoqi-interface.l
[what I did]
added naoqieus method: 
(1) set background movement(*) status (set enabled or disabled)
(2) get background movement status (Is it set or not set?)
(*) slight arm movements while a robot is standing
[related programs]
naoqi api: ALBackgroundMovement
http://doc.aldebaran.com/2-5/naoqi/interaction/autonomousabilities/albackgroundmovement-api.html#albackgroundmovement-api
naoqi_apps program: https://github.com/ros-naoqi/naoqi_bridge/pull/82 (merged)
=> [naoqieus] add 'set/get background movement method'

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/shadow_filter.yaml, jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/shadow_filter_for_gazebo.yaml, jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/tilt_laser_filters_for_gazebo.yaml
According to https://github.com/PR2/pr2_navigation/pull/27
=> jsk_pr2_startup: specify prefix for laser_filters plugins

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_teleop.xml, jsk_fetch_robot/jsk_fetch_startup/package.xml
最近のfetchのプログラムアップデートにより、これまでunsafe teleopに割り当てていたボタンが腕の操作に割り当てられてしまっていたので、それを無効にして今までどおりunsafe teleop出来るようにしました。
=> Change teleop button assignment and enable unsafe teleop

jsk_robot_common/jsk_robot_startup/CMakeLists.txt
Build failed.
`jsk_robot_startup/lightweight_logger` requires `c++11` compiler.
```bash
$ catkin bt
==> Expanding alias 'bt' from 'catkin bt' to 'catkin b --this'
==> Expanding alias 'b' from 'catkin b --this' to 'catkin build --this'
-------------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/kinetic
Workspace:                   /home/shingo/ros/kinetic
-------------------------------------------------------------
Source Space:       [exists] /home/shingo/ros/kinetic/src
Log Space:          [exists] /home/shingo/ros/kinetic/logs
Build Space:        [exists] /home/shingo/ros/kinetic/build
Devel Space:        [exists] /home/shingo/ros/kinetic/devel
Install Space:      [unused] /home/shingo/ros/kinetic/install …
```
=> set std=c++11 as default compiler for jsk_robot_startup

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
fetchをnavigationする際、globalな経路を作れないことが多かったので、inflation radiusを小さくしました。
=> reduce inflation radius parameter for global costmap

.travis.rosinstall.kinetic, .travis.yml, jsk_fetch_robot/fetcheus/fetch-interface.l, jsk_fetch_robot/jsk_fetch.rosinstall, jsk_fetch_robot/jsk_fetch.rosinstall.kinetic
merge #913 and #872
- pass catkin build at fetcheus on kinetic
- Consistency in jsk_fetch_robot.rosinstall and .travis.rosinstall
- Cleanup jsk_fetch_robot.rosinstall
- Remove unused env for jsk_travis
- delete white space
- add .rosinstall for fetch on kinetic
- test in docker on travis
=> add .rosinstall for fetch on kinetc

jsk_naoqi_robot/naoeus/package.xml, jsk_naoqi_robot/peppereus/package.xml
1. why I deleted the dependencies of `nao_apps` from `naoeus package.xml`
I don't think `naoeus` depends on `nao_apps`.
In addtion, `naoeus` depends on `naoqi_bridge`, which causes an error below.
% `naoqi_bridge` is a meta package. I have to learn why this dependency generates an error when compiling. I will send a pull-request to `nao_apps` when I find what is wrong. => updated: I sent a pull-request to https://github.com/ros-naoqi/nao_robot/pull/37
```
Abandoned <<< nao_apps                            [ Depends on unknown jobs: naoqi_bridge ]
Abandoned <<< naoeus                              [ Depends on unknown jobs: naoqi_bridge ]
```
whole log is below:
```
kochigami@kochigami-ThinkPad-T450:~/catkin_ws/src/jsk_robot/jsk_naoqi_robot/naoeus$ catkin bt
==> Expanding alias 'bt' from …
```
=> [jsk_naoqi_robot] modify dependency of package.xml

jsk_naoqi_robot/jsk_nao_startup/launch/jsk_nao_startup.launch, jsk_naoqi_robot/jsk_pepper_startup/launch/jsk_pepper_startup.launch
After this change, the CPU temperature of a PC which naoqi-ros is working becomes around 50.
(Before this change, it becomes over 80...)
I executed `roslaunch jsk_nao(pepper)_startup jsk_nao(pepper)_startup.launch`
I used this command to check the temperature: `cat /sys/class/thermal/thermal_zone0/temp`
Note:
After the node is killed, NAO speaks good night, but Pepper doesn't.
I don't know why. I couldn't have solved the issue yet.
=> [jsk_naoqi_robot] add ros::sleep to speaking node

jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/lifelog/base_trajectory_logger.py
This PR fixed the threshold of base_trajectory update.
Before this PR, calculating threshold become large value,
because ```dt``` is small.
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/lifelog/base_trajectory_logger.py#L129
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/lifelog/base_trajectory_logger.py#L131
Also, we should use threshold value that easy to understand.
Before this PR, the function ```diff_pose``` returns  the difference postion in mm order and absolute distance of quaternion (this value's unit is not intuitive) .
Therefore, I modified ```diff_pose``` to return angle[rad] of two poses, changed ```diff_pos``` in mm order, changed ```diff_theta``` in …
=> [jsk_robot_startup/base_trajectory_logger.py] Modified threshold of pos and theta.

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
particle filterを更新する頻度を上げたことで、推定自己位置の分布が広がり過ぎないようにしました。
=> Update particle filter more often in amcl

jsk_fetch_robot/fetcheus/fetch-utils.l
`fetch-robot`のクラスに、グリッパを動かす関数を追加しました。
`fetch-interface`のクラスと同じように引数を与えられるようにしました。
`:start-grasp`
`:stop-grasp`
=> [fetch] Add grasp functions to fetch-robot class

jsk_fetch_robot/jsk_fetch_startup/config/fetch_analyzers.yaml, jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch, jsk_fetch_robot/jsk_fetch_startup/package.xml
This Pull Request enables to publish `/diagnostic_agg` topic by default on `fetch` robot.
(This is based on https://github.com/fetchrobotics/fetch_robots/blob/indigo-devel/fetch_bringup/config/analyzers.yaml)
You can view this information by typing the command below:
```
rosrun rqt_robot_monitor rqt_robot_monitor
```
=> [fetch] Enable to use diagnostic aggregator on fetch

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
In pr2_computer_monitor, default value of `load1/5_threshold` is very low, so fetch often says 'CPU usage is too high'. (very noisy)
I reduced the threshold in this Pull Request, and now fetch do not speak too much.
I will keep my eyes on it for a while.
=> [fetch] Change threshold of CPU usage warning

jsk_fetch_robot/README.md, jsk_fetch_robot/jsk_fetch.rosinstall, jsk_fetch_robot/jsk_fetch_user.rosinstall.indigo, jsk_fetch_robot/jsk_fetch_user.rosinstall.kinetic
- In this Pull Request, I made `.rosinstall`  for both robot PC and user PC.
The former is `jsk_fetch.rosinstall` and the latter is `jsk_fetch_user.rosinstall.indigo`  and `jsk_fetch_user.rosintall.kinetic`.
- Before this pull request, tar file of `fetch_ros` is installed to `kinetic` user PC by `wstool`, but tar file is inconvenient because it is not git repository.
After this pull request, git repository of `fetch_ros` will be installed to `kinetic` user PC by `wstool`.
- In `jsk_fetch_user.rosinstall.kinetic`, `fetch_ros` version is `0.7.14` because my commit (fetchrobotics/fetch_ros@c0bc8bc) is merged and fetch's amcl will be improved.
=> [fetch] Make .rosinstall for both robot PC and user PC

jsk_robot_common/jsk_robot_startup/CMakeLists.txt, jsk_robot_common/jsk_robot_startup/include/jsk_robot_startup/lightweight_logger.h, jsk_robot_common/jsk_robot_startup/include/jsk_robot_startup/message_store_singleton.h, jsk_robot_common/jsk_robot_startup/src/lightweight_logger_nodelet.cpp, jsk_robot_common/jsk_robot_startup/src/message_store_singleton.cpp
- Reuse mongodb interface object for nodelets with the same manager
- Add diagnostic for logger
- Deferred initialization of logger on nodelet for non-blocking loading
=> jsk_robot_startup: deferred initialize mongodb interface on nodelet

jsk_naoqi_robot/naoqieus/doc/get_basic_awareness_enabled.md, jsk_naoqi_robot/naoqieus/doc/set_basic_awareness_enabled.md, jsk_naoqi_robot/naoqieus/naoqi-interface.l, jsk_naoqi_robot/naoqieus/test/test-naoqieus.l
requires: 
(1) https://github.com/ros-naoqi/naoqi_bridge/pull/72
(2) https://github.com/ros-naoqi/naoqi_bridge/pull/82
(3) https://github.com/ros-naoqi/naoqi_bridge/pull/83
documentation:
(1) http://doc.aldebaran.com/2-5/naoqi/interaction/autonomousabilities/allisteningmovement.html
(2) http://doc.aldebaran.com/2-5/naoqi/interaction/autonomousabilities/albackgroundmovement-api.html#albackgroundmovement-api
(3) http://doc.aldebaran.com/2-5/naoqi/interaction/autonomousabilities/albasicawareness-api.html#albasicawareness-api
(1)
```
2.irteusgl$ send *ri* :set-listening-movement-enabled t
t
3.irteusgl$ send *ri* :get-listening-movement-enabled
t
4.irteusgl$ send *ri* :set-listening-movement-enabled nil
t
5.irteusgl$ send *ri* :get-listening-movement-enabled
nil
```
(2)
```
2.irteusgl$ send …
```
=> [naoqieus] add methods of basic awareness

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch, jsk_fetch_robot/jsk_fetch_startup/launch/fetch_tweet.launch
With this patch, fetch can tweet by publishing std_msgs/String to  ```/tweet```.
Fetch15's account is here.
https://twitter.com/fetch15jsk
=> [jsk_fetch_startup] Add settings for twitter

jsk_fetch_robot/fetcheus/fetch-utils.l
I added pqp collision detection to grasp functions of `fetch-robot` class. 
This Pull Request is based on https://github.com/jsk-ros-pkg/jsk_robot/pull/964#issuecomment-419281444.
The pqp collision detection with `fetch` is shown below:
[before grasping]
[grasping]
[moving object]
test code is as follows:
```lisp
(load "package://fetcheus/fetch-utils.l")
(defun test()
(let ((cube (make-cube 30 30 30)))
(fetch)
(send *fetch* :stop-grasp)
(send cube :locate (send (send *fetch* :rarm :end-coords) :worldpos))
(send cube :rotate 1.0 :z)
(send cube :set-color #f(1 0 0))
(objects (list *fetch* cube))
(do-until-key
(unix:sleep 1))
(send *fetch* :start-grasp cube)
(send *irtviewer* :draw-objects :flush t)
(do-until-key
(unix:sleep 1))
(send *fetch* :rarm :move-end-pos #f(400 0 100) :world)
(send …
```
=> [fetch] Add pqp collision detection feature to grasp functions

jsk_naoqi_robot/README.md, jsk_naoqi_robot/doc/control_multiple_robots_in_one_pc.md, jsk_naoqi_robot/sample/control_multiple_robots/sample2.l
- fixed wrong path files (README, sample code)
- fixed sample code (`sample2.l` should load `nao-interface.l`, not `pepper-interface.l`)
- add explanation about when this feature is useful (`control_multiple_robots_in_one_pc.md`)
=> [jsk_naoqi_robot] fix wrong file path and typo at #1015

jsk_naoqi_robot/naoqieus/naoqi-interface.l
This change enables us to use `:speak-action` method with multiple naoqi robots separated by group-namespace (ref. #1015).
=> [naoqieus] add group-namespace to speak-action method

jsk_robot_common/jsk_robot_startup/CMakeLists.txt
`image` -> `images`
image directory not found for installation
=> fix install in jsk_robot_startup/CMakeLists.txt

jsk_pr2_robot/jsk_pr2_desktop/CMakeLists.txt
comment out unused jsk_pr2_desktop icons.
these desktop icons are deprecated because PR2 is upgrade to indigo.
=> comment out unused jsk_pr2_desktop icon

jsk_naoqi_robot/jsk_nao_startup/launch/jsk_nao_startup.launch, jsk_naoqi_robot/jsk_nao_startup/nodes/joy-client.l, jsk_naoqi_robot/jsk_pepper_startup/nodes/joy-client.l
I want to include same nodes for nao and pepper, so I added `joy-client.l` to `jsk_nao_startup.launch`.
TODO
~- [ ] create button map of a controller, add it to README~ => #1031
=> [jsk_nao_startup] add joy-client.l to jsk_nao_startup.launch

jsk_fetch_robot/jsk_fetch_startup/config/fetch_analyzers.yaml
In this PR, I change the config file of `diagnostic analyzer`.
I need this change because analyzers' name of vision nodelet has changed in https://github.com/jsk-ros-pkg/jsk_robot/pull/1053 .
=> [Fetch] Fix diagnostics analyzer config for fetch's head camera

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
In this PR, I load all vision `nodelet` into single `nodelet manager` to prevent nodelet crushing.
Before, `/head_camera/depth_registered/points` is published and subscribed in different nodelet manager.
This sometimes causes nodelet crushing.
=> [Fetch] Load all nodelet in one manager in order to avoid nodelet crushing

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch, jsk_fetch_robot/jsk_fetch_startup/scripts/warning.py
In this PR, I add `rosparam` to select which level of `diagnostics` is spoken by Fetch.
Also, I set Fetch not to speak `Warning` because Fetch is too noisy if Fetch speaks `Warning`. 
(e.g. CPU high load warning arises frequently)
=> [Fetch] Enable to select speak logger level

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_teleop.xml
In this PR, I add `respawn="true"` for `/joy` and `/teleop`.
This is because sometimes `/joy` and `/teleop` died when booting Fetch by connection error between Fetch and joy.
This PR prevent this problem.
=> [Fetch] Enable respawn /joy and /teleop

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_teleop.xml
Now in Fetch, `/tuck_arm` is launched in both
- fetch_teleop.xml in `jsk_fetch_startup` (https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_fetch_robot/jsk_fetch_startup/launch/fetch_teleop.xml#L28 )
and
- teleop.launch.xml in `fetch_bringup` (https://github.com/fetchrobotics/fetch_robots/blob/indigo-devel/fetch_bringup/launch/include/teleop.launch.xml#L18 )
In this PR, we remove `/tuck_arm` in `jsk_fetch_startup`.
=> [Fetch] Remove /tuck_arm which is already launched in fetch_bringup/launch/include/teleop.launch.xml

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch, jsk_fetch_robot/jsk_fetch_startup/launch/fetch_lifelog.xml, jsk_robot_common/jsk_robot_startup/include/jsk_robot_startup/lightweight_logger.h, jsk_robot_common/jsk_robot_startup/lifelog/common_logger.launch, jsk_robot_common/jsk_robot_startup/src/lightweight_logger_nodelet.cpp
In this Pull Request, I added an option to ignore `vital_checker_->isAlive`.
Current problem is below:
`joint_states_logger` output error when `joint_states_throttle/output` is not subscribed for long time.
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_robot_common/jsk_robot_startup/lifelog/common_logger.launch#L195-L204
However, `joint_states_throttle/output` is published only when robots move.
Therefore, robots using `joint_states_logger` (fetch or PR2) output error whenever they are not moving.
I think this PR solve this problem.
=> [jsk_robot_startup] Add option to check isAlive for lightweight_logger

jsk_fetch_robot/README.md, jsk_fetch_robot/jsk_fetch_startup/launch/fetch_teleop.xml
Before, we disable fetch's arm teleop, but this causes error (sometimes fetch move base and sometimes move arm).
To prevent this error, we assign arm teleop buttons to unused buttons.
Also, I change button assignment for head control similar to PR2.
=> [fetch] Enable arm teleop and set buttons similar to PR2

jsk_fetch_robot/jsk_fetch_startup/README.md
We disable teleop nodes in `/etc/ros/indigo/robot.launch` because `jsk_fetch_startup/fetch_bringup.launch` have its own teleop nodes.
cc. @708yamaguchi
=> [fetch] update jsk_fetch_startup/README.md to add admin modification info

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_teleop.xml
solving conflict commit in #1062 was incorrect.
I remove duplicated joy node in `fetch_teleop.launch`
=> [jsk_fetch_startup] remove duplicated joy node

jsk_robot_common/jsk_robot_startup/lifelog/common_logger.launch
Related to https://github.com/jsk-ros-pkg/jsk_robot/pull/1048.
Fetch still outputs error of `LightweightLogger`, because we set `vital_check` false only for `/joint_states` in https://github.com/jsk-ros-pkg/jsk_robot/pull/1048.
(e.g. Fetch sometime says that rgb image does not come for 1.00 sec)
In this PR, I enable to set `vital_check` for all `LightweightLogger`.
=> [jsk_robot_startup] Add option to use vital_check to all LightweightLogger in common_logger.launch

jsk_pr2_robot/jsk_pr2_startup/pr2_bringup.launch
We can use nodelet version of prosilica camera.
And in default settings, prosilica's image is not rectified.
This PR makes prosilica to nodelet and add publish ```image_rect``` using ```image_proc/rectify```.
=> [jsk_pr2_startup] Make prosilica to nodelet and rectify image

jsk_baxter_robot/jsk_baxter_startup/baxter.launch
add `arm_control_mode` and `arm_interpolation` args to set `interpolation` and `mode` for arm controller.
=> [jsk_baxter_startup] add arm_control_mode and arm_interpolation in baxter.launch

jsk_fetch_robot/jsk_fetch_startup/launch/rviz.launch, jsk_pr2_robot/jsk_pr2_startup/rviz.launch
In current, Fetch and PR2's ```rviz.launch``` node is not anonymous.
If mutliuser launch this launch file to view robot state, only one node can be launched.
So I modified launch file to launch anonymous node.
=> Make rviz node to anonymous

jsk_fetch_robot/jsk_fetch.rosinstall, jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch, jsk_fetch_robot/jsk_fetch_startup/package.xml, jsk_fetch_robot/jsk_fetch_user.rosinstall.indigo
~Please merge after #1017~
Set Fetch speak action server in `rosparam`.
This PR stops Fetch to recognize audio data when robot himself is speaking.
cc. @708yamaguchi
=> set tts action server name properly

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/pr2_microphone.launch
Related to https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/170
add `robotsound` and `robotsound_jp` in `tts_action_names` in `speech_to_text`.
currently, PR1040 recognize what he says by himself.
with this PR, we can stop this bug.
cc. @sktometometo
=> add robotsound and robotsound_jp in tts_action_names/speech_to_text

jsk_fetch_robot/jsk_fetch.rosinstall
In this Pull Request, I add `jsk_fetch.rosinstall` which can reproduce the workspace in fetch' PC.
This `jsk_fetch.rosinstall` is based on https://github.com/jsk-ros-pkg/jsk_robot/pull/1017, https://github.com/jsk-ros-pkg/jsk_robot/pull/1048, https://github.com/jsk-ros-pkg/jsk_robot/pull/1050. https://github.com/jsk-ros-pkg/jsk_robot/pull/1051, https://github.com/jsk-ros-pkg/jsk_robot/pull/1052, https://github.com/jsk-ros-pkg/jsk_robot/pull/1053, https://github.com/jsk-ros-pkg/jsk_robot/pull/1054, so please merge after these PR are merged.
Currently, workspace in fetch's PC is managed by this `jsk_fetch.rosinstall`
I will keep this setup for several weeks with @sktometometo.
If some problems occur, then I will re-make PR.
=> [Fetch] Manage workspace in Fetch's PC by .rosinstall

jsk_pr2_robot/jsk_pr2_startup/pr2_bringup.launch
The PR2 robot interface have a `:start-mannequin-mode` and `:stop-mannequin-mode`, which are not functional now because they imply a series of preconditions. This PR takes care of such preconditions by default on pr2_bringup.launch and make such methods functional again.
Shouldn't have any consequences when  the mannequin mode is off.
@knorth55
=> [pr2] Add mannequin_mode setup

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch, jsk_fetch_robot/jsk_fetch_startup/scripts/warning.py
In this Pull Request, I set `~speak_warn` param as `False` by default, so that our fetch do not speak too much.
There are many `ROS_WARN` in fetch PC and fetch sometimes speak noisy (e.g. when I use rosserial).
This causes fetch user to kill `sound_play`. 
(fetchのwarningがうるさくて僕がしばしばrosnode killしてしまい、他のfetchユーザに迷惑がかかってしまうので、warningは喋らせないようにしました。)
Cc @knorth55
=> [Fetch] do not speak warning diagnostics to avoid noisy fetch

jsk_fetch_robot/jsk_fetch_user.rosinstall.indigo
Now, `fetch_ros` is not released in Indigo, so we need to install it manually.
I add `fetch_ros` to `jsk_fetch_user.rosinstall.indigo`.
(`jsk_fetch_user.rosinstall.indigo` is needed to build `jsk_fetch_startup` and `fetcheus` in fetch user's PC.)
Related to https://github.com/jsk-ros-pkg/jsk_robot/pull/1148
=> add fetch_ros to jsk_fetch_user.rosinstall.indigo

jsk_fetch_robot/fetcheus/fetch-interface.l
add `min-translation-abs-vel` and `min-rotation-abs-vel` to avoid wheel slipping.
=> [fetcheus] add min abs velocity in :go-pos-unsafe to prevent wheel slipping

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch, jsk_fetch_robot/jsk_fetch_startup/launch/fetch_teleop.xml, jsk_fetch_robot/jsk_fetch_startup/package.xml, jsk_fetch_robot/jsk_fetch_startup/scripts/correct_position.py, jsk_fetch_robot/jsk_fetch_startup/scripts/imu_corrector.py, jsk_fetch_robot/jsk_fetch_startup/scripts/odom_corrector.py
I add nodes which publish correct odom `/odom_corrected` and imu `/imu_corrected`.
Then I use these two corrected topics for `robot_localization` `ukf` for localization.
I wonder this change suppress odometry error.
- add odom_corrector.py
- `/odom` does not have `frame_id`: https://github.com/fetchrobotics/fetch_ros/issues/70
- `/odom` has zero covariance and overwrited in graft: https://github.com/fetchrobotics/fetch_robots/blob/indigo-devel/fetch_bringup/config/graft.yaml
- add imu_corrector.py
- `/imu` has zero covariance and overwrited in graft: https://github.com/fetchrobotics/fetch_robots/blob/indigo-devel/fetch_bringup/config/graft.yaml
- use robot_localization instead of graft
- `graft` is no more maintenanced: https://github.com/ros-perception/graft/issues/29#issuecomment-4612233 …
=> fix fetch robot localization and navigation

.travis.rosinstall.indigo, .travis.yml
Includes #1171 
With #1017, whole jsk_3rdparty is included in workspace on travis (created with `.travis.rosinstall.indigo`) for jsk_fetch_startup.
But actually, we need respeaker_ros only.
Also see https://github.com/jsk-ros-pkg/jsk_robot/pull/1171#issuecomment-554861065
Other minor fix: upload apt-cacher-ng cache to speed up rosdep install (effective from second time)
See https://github.com/jsk-ros-pkg/jsk_robot/pull/1171#issuecomment-554206118
=> Stop building unnecessary packages on indigo to speed up travis

jsk_fetch_robot/jsk_fetch_startup/euslisp/navigation-utils.l
Because of message type difference between melodic and indigo, `go-to-spot` stacks in subscription of `/battery_state`.
I change to skip the subscription in `go-to-spot` when the subscription is timeout.
=> [fetcheus] skip undocking when subscribe timeout in go-to-spot

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/look-forward-in-nav.l
I added  a service interface of start/stop to look-forward-in-nav.l in order to move head from another process without conflicting.
=> Add service interface to look-forward to start/stop from another process

jsk_pr2_robot/jsk_pr2_startup/pr2_bringup.launch
`power_monitor`'s default frequency is 0.1Hz (http://wiki.ros.org/power_monitor)
In current, `cable_warning` node subscribes `power_state` topic and the node looks at the state of the power supply to determine whether pr2 can move.
This PR modifies the frequency to 1Hz to make the check fast.
=> [jsk_pr2_startup] Modified power_monitor frequency

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_sensors.xml
i add `/head_camera/rgb/throttled/image_rect_color/compressed`, which does not exist now.
=> [jsk_fetch_startup] add rgb compressed throttle in fetch

jsk_baxter_robot/jsk_baxter_startup/baxter.launch
`launch_mongodb` and `launch_tweet` should be defined before `launch_db` and `launch_twitter`.
=> [jsk_baxter_startup] fix arg order in baxter.launch

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_warning/pr2_reset_motors.py
add `logwarn` when pr2 reset motors.
we can get when PR2 reset motors in log file.
this is useful for debugging packet drop.
=> [jsk_pr2_startup] add logwarn in pr2_reset_motors.py

jsk_fetch_robot/fetcheus/fetch-interface.l
~waiting upstream https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/418~
this PR skip correction step in `:move-to`, which is not useful for Fetch robot.
=> [fetcheus] override :move-to-wait to set :correction nil

jsk_fetch_robot/fetcheus/fetch-interface.l, jsk_fetch_robot/fetcheus/test/test-fetcheus.l
```
(send *ri* :angle-vector (send *fetch* :angle-vector) 3000 :use-torso t)
```
fails with 
```
Call Stack (max depth: 20):
0: at (apply #'send-message self (class . super) :angle-vector av tm args)
1: at (apply #'send-message self (class . super) :angle-vector av tm args)
2: at (apply #'send-message self (class . super) :angle-vector av tm args)
3: at (send-super* :angle-vector av tm args)
4: at (let* ((prev-av (send self :state :potentio-vector :wait-until-update t)) (diff-av (v- av prev-av))) (when (send self :check-continuous-joint-move-over-180 diff-av) (let* (avs (minjerk (instance minjerk-interpolator :init)) (scale-av (send self :sub-angle-vector av prev-av)) dist div) (setq dist (abs (find-extream (coerce diff-av cons) #'abs #'>=))) (setq div (round (/ dist 120.0))) (send …
```
=> [fetcheus] Fix :use-torso in *ri* :angle-vector and :angle-vector-sequence when simulation mode

jsk_fetch_robot/fetcheus/fetch-interface.l, jsk_fetch_robot/fetcheus/test/test-fetcheus.l
fix #1264 
we need to check if ""apply_planning_scene" service exists before creating `*ci*`
=> add test to check fetch-init

.travis.rosinstall.indigo, .travis.rosinstall.kinetic, .travis.rosinstall.melodic, .travis.yml
- use `jsk_travis` `0.5.17`
- remove released packages from `.travis.rosinstall.$ROS_DISTRO`
- add `fetch_ros` in `.travis.rosinstall.$ROS_DISTRO` (https://github.com/fetchrobotics/fetch_ros/pull/144, https://github.com/fetchrobotics/fetch_ros/pull/146)
=> Update jsk_travis to 0.5.17 and fix travis

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_warning/pr2_reset_motors.py, jsk_pr2_robot/jsk_pr2_startup/pr2.launch
update `watch_duration` to `30` and reset motors more frequently.
=> [jsk_pr2_startup] add watch duration comment for pr2_reset_motors

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch, jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/pr2_2dnav.launch, jsk_robot_common/jsk_robot_startup/scripts/nav_speak.py
- move `nav_speak.py` to `jsk_robot_startup`
- use `nav_speak.py` in pr2
=> move `nav_speak.py` to `jsk_robot_startup` and use it in pr2

jsk_kinova_robot/jsk_kinova_startup/launch/kinova_bringup.launch
In this PR, I set bigger `sample_duration` param to reduce minjerk interpolation calculation time in kinovaeus.
In kortex_ros v2.2.0, `~sample_duration` param is set as 0.001. (default is 0.05)
https://github.com/Kinovarobotics/ros_kortex/blob/v2.2.2/kortex_move_it_config/gen3_lite_gen3_lite_2f_move_it_config/launch/ompl_planning_pipeline.launch.xml#L23
This means that MoveIt! returns trajectory interpolated at 0.001[s] intervals.
http://wiki.ros.org/industrial_trajectory_filters
In kinovaeus, the MoveIt! trajectory is stretched several times, and then minjerk interpolation is performed again to create trajectory interpolated at 0.001[s] intervals.
The more waypoints the MoveIt! trajectory has, the longer the minjerk interpolation calculation time will be.
So, In this PR, I set bigger …
=> Set MoveIt! sample_duration to avoid too dense trajectory in MoveIt!

jsk_kinova_robot/kinova.rosinstall, jsk_kinova_robot/kinovaeus/package.xml
I update jsk_kinova_startup dependencies to reflect kinova upstream
- kortex_ros v2.3.0 is merged, but our kinova arm's firmware is v2.2.0, so I use v2.2.0 kortex_ros in kinova.rosinstall (Note that kortex_ros v2.3.0 is incompatible with kinova arm of firmware v2.2.0)
- https://github.com/Kinovarobotics/ros_kortex/tags
- The following PRs are merged, but the merge is after v2.3.0 tag. I write the details in package.xml
- https://github.com/Kinovarobotics/ros_kortex/pull/140
- https://github.com/Kinovarobotics/ros_kortex/pull/142
=> Update jsk_kinova_startup dependencies to reflect kinova upstream

jsk_fetch_robot/jsk_fetch.rosinstall.melodic, jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch, jsk_fetch_robot/jsk_fetch_startup/scripts/battery_warning.py, jsk_robot_common/jsk_robot_startup/scripts/boot_sound.py
this PR enables fetch to wait speaking until other node is speaking.
cc. @708yamaguchi 
related: https://github.com/ros-drivers/audio_common/pull/173
=> [jsk_fetch_startup] Do not replace sound when other node is speaking

jsk_fetch_robot/jsk_fetch.rosinstall.indigo
remove unnecessary (doubled) entry from `jsk_fetch.rosinstall.indigo`
=> [jsk_fetch_robot] remove double rosinstall entry in jsk_fetch.rosinstall.indigo

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_insta360_indigo.launch, jsk_fetch_robot/jsk_fetch_startup/launch/fetch_insta360_melodic.launch
from https://github.com/jsk-ros-pkg/jsk_robot/pull/1321
cherry-pick https://github.com/jsk-ros-pkg/jsk_robot/commit/f7b5dd4f9eae5cf2c4455985056614cbb46d5a3a
add image_proc/resize for dual_fisheye_to_panorama
This feature is useful when we want to check panorama image with low CPU usage.
=> Publish resized panorama images

jsk_robot_common/speak_and_wait_recovery/CMakeLists.txt, jsk_robot_common/speak_and_wait_recovery/README.md, jsk_robot_common/speak_and_wait_recovery/include/speak_and_wait_recovery/speak_and_wait_recovery.h, jsk_robot_common/speak_and_wait_recovery/launch/demo.launch, jsk_robot_common/speak_and_wait_recovery/package.xml, jsk_robot_common/speak_and_wait_recovery/speak_and_wait_plugin.xml, jsk_robot_common/speak_and_wait_recovery/src/speak_and_wait_recovery.cpp, jsk_robot_common/speak_and_wait_recovery/test/speak_and_wait_recovery.test, jsk_robot_common/speak_and_wait_recovery/test/speak_and_wait_recovery_simple_node.cpp, jsk_robot_common/speak_and_wait_recovery/test/test_speak_and_wait.py
Moved from https://github.com/jsk-ros-pkg/jsk_common/pull/1681
Add a RecoveryBehavior plugin package which enables a robot to speak and wait when get stuck.
https://user-images.githubusercontent.com/9410362/113476175-ce3c1400-94b4-11eb-87fa-8f7cdafb1d62.mp4
=> [speak_and_wait_recovery] add speak_and_wait_recovery package

jsk_robot_common/jsk_robot_startup/package.xml
`jsk_robot_startup`は`jsk_tilt_laser`に依存していますが，package.xmlに書かれていなかったので，追加しました．
https://github.com/jsk-ros-pkg/jsk_robot/blob/b2976cd0dc93b1def1ab80c57be4d2acfba086e5/jsk_robot_common/jsk_robot_startup/launch/multisense_local.launch#L24
この変更が無いと，
https://github.com/start-jsk/rtmros_choreonoid
のサンプルがエラーになります．
=> [jsk_robot_startup] add jsk_tilt_laser to package.xml

jsk_robot_common/jsk_robot_startup/scripts/email_topic.py
This PR has two error handling.
In the default rostopic tab completion, `attached_files` field is list of empty string.
In that case, instead of giving an error and not sending out an email, I send out an email with a warning.
```
$ rostopic pub /email jsk_robot_startup/Email "header:
seq: 0
stamp: {secs: 0, nsecs: 0}
frame_id: ''
subject: ''
body: ''
sender_address: ''
receiver_address: ''                      
smtp_server: ''
smtp_port: ''
attached_files: ['']" 
```
```
[ERROR] [1640613571.408953]: File  is not found.
```
When the `receiver_address` of rostopic was not specified, the `receiver_address` of the argument of _send_mail() was not specified and an error occurred.
This PR will catch such errors.
```
$ rosrun jsk_robot_startup email_topic.py …
```
=> Error handling when the email field is not appropriate.

jsk_fetch_robot/jsk_fetch_diagnosis/node_scripts/check_driver_boards.py, jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
Cherry-picked from https://github.com/knorth55/jsk_robot/pull/180
Recently, fetch1075 board sometimes becomes inaccessible.
After some time, the communication state returned to normal, which made it difficult to debug.
In this pull request, we will always monitor the communication status with the board and print `rospy.logerr` when an error occurs.
Example of logging:
```
[ERROR] [1642931150.336007] [/check_board_info:rosout]: command returned non-zero exit status while read board with id 0x26: shoulder_pan
[ERROR] [1642931150.479744817] [${node}:ros.fetch_drivers]: Error occured while running : No response to readBoardRegisterTable
[ERROR] [1642931150.481028] [/check_board_info:rosout]: command returned non-zero exit status while read board with id 0x27: shoulder_lift
[ERROR] …
```
=> [jsk_fetch_diagnosis] Print board name in addition to board id

jsk_robot_common/jsk_robot_startup/scripts/nav_speak.py
sometimes it calls callback function before we initialized `is_speaking`
```
[ INFO] [1648713664.832008331, 46.397000000]: Goal reached
[ERROR] [1648713664.833388, 46.397000]: bad callback: <bound method NavSpeak.move_base_result_callback of <__main__.NavSpeak object at 0x7f1f4a693450>>
Traceback (most recent call last):
File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
cb(msg)
File "/home/k-okada/catkin_ws/ws_jsk_robot/src/jsk_robot/jsk_robot_common/jsk_robot_startup/scripts/nav_speak.py", line 54, in move_base_result_callback
while self.is_speaking is True:
AttributeError: 'NavSpeak' object has no attribute 'is_speaking'
```
=> move is_speaking to top of __init__ function

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch, jsk_fetch_robot/jsk_fetch_startup/scripts/battery_warning.py, jsk_fetch_robot/jsk_fetch_startup/supervisor_scripts/jsk-shutdown.conf, jsk_fetch_robot/jsk_fetch_startup/tmuxinator_yaml/log.yml, jsk_robot_common/jsk_robot_startup/README.md, jsk_robot_common/jsk_robot_startup/scripts/shutdown.py
From https://github.com/jsk-ros-pkg/jsk_robot/pull/1426#issuecomment-1001838437
- I add rosnode to shut down or reboot robot by rostopic
- In battery_warning.py, I make fetch shut down when the battery level is low.
=> [jsk_fetch_startup] Add node to shut down or reboot robot itself

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch, jsk_fetch_robot/jsk_fetch_startup/scripts/battery_warning.py
From https://github.com/jsk-ros-pkg/jsk_robot/pull/1374
In `battery_warning.py`, fetch send an email when low battery.
I use `/email` topic to send email
https://github.com/jsk-ros-pkg/jsk_robot/tree/master/jsk_robot_common/jsk_robot_startup#scriptsemail_topicpy
Example email:
=> [jsk_fetch_startup] Send an email when fetch is low battery

jsk_fetch_robot/jsk_fetch_startup/apps/go_to_kitchen/go_to_kitchen.app
From https://github.com/knorth55/jsk_robot/pull/97
Record panorama video in `go-to-kitchen` demo.
Please see the mail Fetch kitchen patrol demo: 2021/05/12 (16:55:25)
=> Record panorama video in go_to_kitchen demo

jsk_fetch_robot/jsk_fetch_startup/euslisp/navigation-utils.l
Duplicate of knorth55/jsk_robot#179
Update switchbot device name due to common operation of switchbot token with dialogflow users.
(We have fixed the problem that the lights in the room could not be controlled by switchbot in the morning kitchen demo due to old switchbot token. )
=> [jsk_fetch_startup] Update switchbot device name in navigation-utils.l

jsk_fetch_robot/jsk_fetch_startup/apps/go_to_kitchen/go_to_kitchen.app
From https://github.com/knorth55/jsk_robot/pull/141
Send `/move_base/cancel` when `go-to-kitchen` app is stopped.
Sometimes, `move_base` continues to work though `go-to-kitchen` is stopped.
=> send /move_base/cancel when go-to-kitchen stopped

jsk_fetch_robot/jsk_fetch.rosinstall.melodic
Cherry-pick 
https://github.com/knorth55/jsk_robot/pull/190
https://github.com/knorth55/jsk_robot/pull/191
I use new version `realsense-ros` to supress L515 error 'An error has occurred during frame callback: map::at'
Cherry-pick
https://github.com/knorth55/jsk_robot/pull/192
I add notes about `realsense-ros` version compatibility.
=> [jsk_fetch_startup] Supress L515 ERROR messages

jsk_fetch_robot/jsk_fetch_startup/apps/go_to_kitchen/go_to_kitchen.app, jsk_fetch_robot/jsk_fetch_startup/euslisp/navigation-utils.l, jsk_fetch_robot/jsk_fetch_startup/euslisp/notify-app.l
From https://github.com/knorth55/jsk_robot/pull/133
For `go_to_kitchen` demo, I added app_manager plugin for email notification.
With this PR, fetch can send the following notifications in the dailiy mail.
```
Following object recognition is reported.
- At 2022-04-20T16:43:59, (kettle) is found in kitchen stove.
- At 2022-04-20T16:44:54, (dish chair) is found in trash cans.
```
=> Add roseus code to call app_notification_saver service

jsk_fetch_robot/jsk_fetch_startup/apps/go_to_kitchen/go_to_kitchen.app
From https://github.com/knorth55/jsk_robot/pull/134
Launch smach_notification_saver plugin by default in go-to-kitchen demo
Fetch reports smach states in email.
```
Fetch kitchen patrol demo: 2021/07/30 (16:55:10)
===
Following smach is reported.
- At 2021-07-30T16:52:17, Active states is REPORT-START-GO-TO-KITCHEN
- At 2021-07-30T16:52:22, Active states is GET-LIGHT-ON
- At 2021-07-30T16:52:22, Active states is REPORT-LIGHT-ON
- At 2021-07-30T16:52:26, Active states is MOVE-TO-SINK-FRONT
- At 2021-07-30T16:52:52, Active states is INSPECT-KITCHEN
- At 2021-07-30T16:53:19, Active states is AUTO-DOCK
- At 2021-07-30T16:54:01, Active states is ROOM-LIGHT-OFF
- At 2021-07-30T16:54:01, Active states is FINISH
- At 2021-07-30T16:54:03, Active states is
Following object recognition is reported. …
```
=> Launch smach_notification_saver by default

jsk_fetch_robot/jsk_fetch.rosinstall.melodic, jsk_fetch_robot/jsk_fetch_startup/apps/go_to_kitchen/go_to_kitchen.app
From https://github.com/knorth55/jsk_robot/pull/169
(I don't cherry-pick the first two commits, because these commits are already merged.)
With this PR, fetch shuts down itself when `go-to-kitchen` demo fails by timeout.
The purpose of this PR is to prevent fetch battery degradation.
=> Publish /shutdown topic if go-to-kitchen demo fails

jsk_fetch_robot/README.md, jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
Update README about building a map with Fetch robot.
Duplicate of https://github.com/knorth55/jsk_robot/pull/139
=> Add build map docs

jsk_naoqi_robot/naoqieus/CMakeLists.txt, jsk_naoqi_robot/naoqieus/package.xml, jsk_naoqi_robot/peppereus/CMakeLists.txt, jsk_robot_common/speak_and_wait_recovery/CMakeLists.txt
aabbdfb1a (Kei Okada, 21 seconds ago)
naoqi_msgs becomes naoqi_bridge_msgs since indigo
ac7c04fc5 (Kei Okada, 2 minutes ago)
jsk_naoqi_robot/{peppereus,naoqieus}/CMakeLists.txt: run add_rostest only
CATKIN_ENABLE_TESTING
542f65c75 (Kei Okada, 3 minutes ago)
jsk_robot_common/speak_and_wait_recovery/CMakeLists.txt: fix typo # Testgin
-> # Testing
=> do not run add_rostest when CATKIN_ENABLE_TESTING=OFF, remove depends to naoqi_msgs, we use naoqi_bridge_msgs since indigo

jsk_fetch_robot/jsk_fetch_startup/launch/fetch.launch
Copy https://github.com/knorth55/jsk_robot/pull/221
There are two `diagnostic_aggregator` node in fetch's launch file.
`fetch_bringup.launch`'s aggregator includes `fetch.launch`'s aggregator.
So I remove the `fetch.launch`'s aggregator.
https://github.com/jsk-ros-pkg/jsk_robot/blob/f9cce5aec920ea7c8a96b790fac2af8411b56d94/jsk_fetch_robot/jsk_fetch_startup/launch/fetch.launch#L164-L165
https://github.com/jsk-ros-pkg/jsk_robot/blob/f9cce5aec920ea7c8a96b790fac2af8411b56d94/jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch#L80-L84
=> [jsk_fetch_startup] Remove duplicated diagnostics aggregator

jsk_fetch_robot/jsk_fetch.rosinstall.melodic, jsk_fetch_robot/jsk_fetch_startup/apps/go_to_kitchen/go_to_kitchen.app
~Please merge after https://github.com/jsk-ros-pkg/jsk_robot/pull/1452~
From https://github.com/knorth55/jsk_robot/pull/170
The other day, fetch is stucked during AUTO-DOCK after INSPECT-TRASHCAN.
```
Following smach is reported.
- At 2021-12-25T09:00:22, Active states is REPORT-START-GO-TO-KITCHEN.
- At 2021-12-25T09:00:25, Active states is GET-LIGHT-ON.
- At 2021-12-25T09:00:26, Active states is ROOM-LIGHT-ON.
- At 2021-12-25T09:00:32, Active states is MOVE-TO-SINK-FRONT.
- At 2021-12-25T09:01:07, Active states is INSPECT-KITCHEN.
- At 2021-12-25T09:01:26, Active states is MOVE-TO-TRASHCAN-FRONT.
- At 2021-12-25T09:01:35, Active states is INSPECT-TRASHCAN.
```
From a battery protection point of view, we want fetch to shutdown in this situation.
With PR, fetch shuts down itself when …
=> [jsk_fetch_startup] Shutdown robot if go-to-kitchen timeout or fail

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch, jsk_fetch_robot/jsk_fetch_startup/scripts/correct_position.py
From https://github.com/knorth55/jsk_robot/pull/255
Depends on https://github.com/jsk-ros-pkg/jsk_common/pull/1740
In `correct_position.py`, fetch publishes `initialpose` topic to `amcl` node when the following 2 conditions are met.
- `initialpose` topic is subscribed by `amcl`
- fetch is docking
I this case, even if `initialpose` is subscribed, it does not necessarily mean that publish is performed.
So I manually call `poke()` in callback function in addition to  `publish()`.
cc @iory @knorth55
=> [jsk_fetch_startup] Add poke to correct_position.py to avoid diagnostics error

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/rosbag_record.launch
Other than topics specified by default, you can record any topics including regex. 
You can also add other options as [common_record.launch](https://github.com/jsk-ros-pkg/jsk_common/blob/master/jsk_data/launch/common_record.launch) in jsk_data.
cc: @iory
=> [jsk_pr2_startup] Enable additional topic and options in rosbag_record.launch

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_warning/battery_logger.py
In current, dweet server has down.
https://twitter.com/dweet_io
This PR adds error handling for dweet logging.
cc: @nakane11
=> [jsk_robot_startup/battery_logger.py] Add error handling for dweet

jsk_robot_common/jsk_robot_startup/util/mux_selector.py
In python3, we have to use `_thread` instead of `thread`.
=> [jsk_robot_startup/util] Support python3 in mux_selector.py

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch, jsk_fetch_robot/jsk_fetch_startup/launch/fetch_rosserial.launch, jsk_fetch_robot/jsk_fetch_startup/supervisor_scripts/jsk-rfcomm-bind.conf, jsk_fetch_robot/jsk_fetch_startup/tmuxinator_yaml/log.yml
Please merge after https://github.com/jsk-ros-pkg/jsk_robot/pull/1401
With this PR, fetch1075 can always communicate with m5stacks, which is usually powered by a refrigerator.
- When m5stack is charged, fetch1075 can get the m5stack battery rostopics. (The sensors are not available to save m5stack battery)
- When m5stack is not charged, fetch1075 can get each sensor rostopics in addition to the battery rostopics.
Only fetch1075 uses m5stacks because two robots (fetch15 and fetch1075) cannot use one rosserial device at the same time.
=> [jsk_fetch_startup] Add launch to use m5stack sensors via rosserial + bluetooth

jsk_fetch_robot/jsk_fetch_startup/apps/go_to_kitchen/go_to_kitchen.app, jsk_fetch_robot/jsk_fetch_startup/apps/go_to_kitchen/go_to_kitchen.xml, jsk_fetch_robot/jsk_fetch_startup/launch/rviz_record.launch
Related to https://github.com/knorth55/jsk_robot/pull/284
This PR adds a throttle function for rviz.
I confirmed this PR works on fetch1075.
=> [jsk_fetch_startup/go_to_kitchen.app] Launch rviz's throttle nodes in rviz_record.launch for video record

jsk_fetch_robot/jsk_fetch_startup/euslisp/go-to-kitchen-with-mail-notify.l, jsk_fetch_robot/jsk_fetch_startup/euslisp/go-to-kitchen.l, jsk_fetch_robot/jsk_fetch_startup/euslisp/navigation-utils.l
~Please merge after https://github.com/jsk-ros-pkg/jsk_robot/pull/1449~
I cherry-picked
- https://github.com/knorth55/jsk_robot/commit/bc84ef3c3010adfe569f782cfd9c665edeedc3c1
- https://github.com/knorth55/jsk_robot/commit/3baccbe98c1edddcb0051d14a9697510ae3c8a07
- https://github.com/knorth55/jsk_robot/commit/74c98db263d35292d7f6c184313c3654566d9859
- https://github.com/knorth55/jsk_robot/pull/140
With this PR, 
- fetch goes in front of the trashbox in the go-to-kitchen demo.
- fetch notifies the status by object recognition and email.
=> Fetch notifies trashbox status in go-to-kitchen demo.

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_rosserial.launch
Cherry-pick https://github.com/knorth55/jsk_robot/pull/294
We can always get battery state.
```
rostopic echo /enviii/battery_level
rostopic echo /enviii/is_charging
```
We can get sensor data only when the module is detached from charging station.
```
rostopic echo /enviii/pressure
rostopic echo /enviii/humidity
rostopic echo /enviii/temperature
```
cc @sktometometo
=> [jsk_fetch_startup] Launch ENV III sensor via rosserial + Bluetooth

jsk_fetch_robot/jsk_fetch.rosinstall.melodic
From https://github.com/jsk-ros-pkg/jsk_robot/issues/1531#issuecomment-1188066561
I update rosserial used in fetch to use ArduinoBluetoothHardware.
I cherry-picked the following commits.
[knorth55/jsk_robot@`ad65583` (#157)](https://github.com/knorth55/jsk_robot/pull/157/commits/ad65583e6365de090256385eb34673607e62f5c0)
https://github.com/knorth55/jsk_robot/pull/296
=> Update rosserial used in fetch to use ArduinoBluetoothHardware

jsk_naoqi_robot/jsk_pepper_startup/README.md
When you launch `naoqi_driver.launch`, you may encounter the error below:
```
what():  	ALProxy::ALProxy
Can't find service: ROS-Driver-Audio
```
I added troubleshooting for this issue.
related issue: https://github.com/jsk-ros-pkg/jsk_robot/issues/1474
=> [jsk_pepper_startup/README.md] add trobleshooting about the error related to ROS-Driver-Audio

jsk_naoqi_robot/jsk_pepper_startup/README.md
You may encounter the getting started wizard on Pepper's tablet when you turn on the robot.
If it appears, it may be better to turn it off because some functions are blocked.
However, sometimes you cannot deactivate it by just pressing "X" mark on the tablet. 
So, I added some tips to deactivate it.
ペッパーの電源をつけた時に，タブレットに設定画面が出ることがあります．
これは，いくつかのコマンドを無効化するため，消した方が良いのですが，タブレットのバツマークを押しても消えないことがあります．その時の消し方のコツを書きました．
=> [jsk_pepper_startup/README.md] add some tips to deactivate the getting started wizard on Pepper's tablet

jsk_hand/softhand_ros/README.md, jsk_hand/softhand_ros/launch/softhand_left.launch, jsk_hand/softhand_ros/launch/softhand_right.launch, jsk_hand/softhand_ros/launch/softhand_v2_left.launch, jsk_hand/softhand_ros/launch/softhand_v2_right.launch
this PR fixes udev file name error in #1522 
in #1522, I changed udev file name from `lhand-e151` to `lhand-e160`, but I forgot to change it in launch.
https://github.com/jsk-ros-pkg/jsk_robot/commit/954e0bfc186d16023a56fc84e2e50351c42f3cdf
this PR changes the udev device name in launch.
I also fix typo in readme, too.
=> [softhand_ros] fix device file name and readme for softhand

jsk_hand/softhand_ros/euslisp/dynamixel-hand-interface.l
I tested with `eus10`, but `eus9` causes segmentation fault at `subscriber` in `let` scope.
I avoid the issue by using `lambda-closure`.
cc. @Affonso-Gui
=> [softhand_ros] use lambda-closure for subscriber

jsk_robot_common/jsk_robot_startup/CMakeLists.txt, jsk_robot_common/jsk_robot_startup/euslisp/email-topic-client.l, jsk_robot_common/jsk_robot_startup/euslisp/sample-email-topic-client.l, jsk_robot_common/jsk_robot_startup/msg/Email.msg, jsk_robot_common/jsk_robot_startup/msg/EmailBody.msg, jsk_robot_common/jsk_robot_startup/scripts/email_topic.py
This PR supports sending embed image with email_topic.py. (Discussion in #1463)
------
TODO
---------
- sample code
```python
#!/usr/bin/env python
import rospy
import time
from jsk_robot_startup.msg import Email
from jsk_robot_startup.msg import EmailBody
def main():
rospy.init_node('embed_image_test')
pub = rospy.Publisher("email", Email, queue_size=10)
msg = Email()
content_1 = EmailBody()
content_1.type = 'text'
content_1.message = 'こんにちは．\n'
content_2 = EmailBody()
content_2.type = 'img'
content_2.file_path = '/home/tsukamoto/Pictures/spotkinova_attachment.jpg'
content_4 = EmailBody()
content_4.type = 'img'
content_4.file_path = '/home/tsukamoto/Pictures/boston_template.png'
content_5 = EmailBody()
content_5.type = 'text'
content_5.message = '\n 今日はSpotで遊んだよ\n'
content_6 = …
```
=> [jsk_robot_startup] Support embed image in email_topic.py

jsk_fetch_robot/jsk_fetch_startup/README.md
Currently, we cannot see app icons on http://tork-a.github.io/visualization_rwt/rwt_app_chooser.
This is because recent browsers (e.g. chrome, firefox) have become more secure.
I added the alternate URL to REDAME.
=> [jsk_fetch_startup] Add alternate rwt_app_chooser URL

.travis.rosinstall.kinetic, jsk_fetch_robot/jsk_fetch_startup/config/fetch_analyzers.yaml, jsk_fetch_robot/jsk_fetch_startup/config/sanity_targets.yaml, jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch, jsk_fetch_robot/jsk_fetch_startup/package.xml
This is refined version of https://github.com/jsk-ros-pkg/jsk_robot/pull/1460
Copied from https://github.com/knorth55/jsk_robot/pull/222
This depends on https://github.com/jsk-ros-pkg/jsk_common/pull/1727
I want fetch to indicate that topic has not come or node does not exist.
For example, I want to check existence of `/audio` or `/insta360`, whose publisher does not publish `/diagnostics`.
What I did in this PR is as follows:
- Change diagnostics aggregator prefix according to node name change.
- Add node to publish /diagnostics
=> [jsk_fetch_startup] Publish diagnostics for important topics and nodes

jsk_robot_common/jsk_robot_startup/lifelog/active_user.l
Fix the problem reported in https://github.com/jsk-ros-pkg/jsk_robot/pull/1548.
Sometimes `active_user.l` fails to retrieve a username. This PR fix it.
=> [jsk_robot_startup] Fix username retrieval in active_user.l

jsk_baxter_robot/jsk_baxter_startup/README.md, jsk_baxter_robot/jsk_baxter_startup/baxter.launch, jsk_baxter_robot/jsk_baxter_startup/baxter_default.launch, jsk_baxter_robot/jsk_baxter_startup/baxter_softhand.launch, jsk_baxter_robot/jsk_baxter_startup/config/baxter_default.rviz, jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_description/baxter.urdf.xacro, jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_description/left_end_effector.urdf.xacro, jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_description/right_end_effector.urdf.xacro, jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_machine/baxter.machine, jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_machine/env.sh, jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/baxter_realsense_torso.launch, jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/baxter_spherical_kodak.launch, jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/baxter_spherical_stereo.launch, jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/elp_usb.launch, jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/kodak_pixpro.launch, jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/l515_torso_pose.yaml, jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/realsense.launch, jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/respeaker.launch, jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_udev/99-elp.rules, jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_udev/99-kodak.rules, jsk_baxter_robot/jsk_baxter_startup/package.xml
this PR is originally from [knorth55/eus_vive](https://github.com/knorth55/eus_vive/blob/master/launch/baxter/baxter.launch)
I'm moving the code from `eus_vive` to `jsk_robot`.
this PR updated `baxter.launch` to support current baxter-jsk-softhand.
this PR supports:
- New grippers 
- softhand
- softhand-v2
- New cameras
- Torso realsense
- Kodak Spherical camera
- Spherical stereo camera
- New microphone
- Torso respeaker
- Launch xdisplay
You can run this launch with following commands.
```bash
roslaunch jsk_baxter_startup baxter_default.launch
```
```bash
roslaunch jsk_baxter_startup baxter_softhand.launch
```
=> [jsk_baxter_startup] update baxter.launch to support current baxter-jsk-softhand

jsk_baxter_robot/jsk_baxter_startup/baxter_default.launch, jsk_baxter_robot/jsk_baxter_startup/baxter_softhand.launch
this is my mistake.
there is a typo in `baxter_softhand.launch` and `baxter_default.launch`.
=> [jsk_baxter_startup] fix typo: default -> value

jsk_robot_common/jsk_robot_startup/README.md, jsk_robot_common/jsk_robot_startup/package.xml, jsk_robot_common/jsk_robot_startup/scripts/smach_to_mail.py
add `jsk_robot_startup/scripts/smach_to_mail.py` which  sends smach message to `/email`, `/tweet`, etc...
based on @tkmtnt7000 's code https://github.com/k-okada/jsk_robot/pull/60#issuecomment-1194891312
This PR depends on https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/371
example SMACH examples can be found at  https://github.com/jsk-ros-pkg/jsk_robot/pull/1528
- https://github.com/k-okada/jsk_robot/blob/pepper_cross/jsk_naoqi_robot/jsk_pepper_startup/apps/meeting/scripts/meeting.l
- https://github.com/k-okada/jsk_robot/blob/pepper_cross/jsk_robot_common/jsk_robot_startup/lifelog/speaking-program-is-started-or-terminated.l
@mqcmd196 Can you add `_send_google_chat` function to this program ?
=> Smach to email/twitter

jsk_baxter_robot/baxtereus/baxter-softhand-interface.l
I change softhand mount, so I move the end-coords for softhand a little forward.
this mount is for softhand and softhand V2, so we can easily change the both two grippers.
=> [baxtereus] move end-coords for new softhand mount

jsk_robot_common/jsk_robot_startup/README.md, jsk_robot_common/jsk_robot_startup/scripts/shutdown.py
This is solution for `2A` https://github.com/jsk-ros-pkg/jsk_robot/pull/1561#issuecomment-1223862080
> 2-A) Modify [shutdown.py](https://github.com/jsk-ros-pkg/jsk_robot/pull/1426/files#diff-cf0bde4b686b024bc710bc3ca3c01e227134a66e783ccea5defe6a0c90eccc29) ,
I added `~input_condition` param to check `battery_state`.
=> [jsk_robot_startup] Enable input condition and added shutdown_unchecked

jsk_baxter_robot/baxtereus/baxter-interface.l, jsk_baxter_robot/baxtereus/baxter-softhand-interface.l
I add `allow-other-keys` for `baxter-init`.
this is useful to pass all args with `&rest args` from your custom `baxter-init` function.
=> add allow-other-keys in baxter-init

jsk_robot_common/jsk_robot_startup/README.md
I have written a readme about the work that needs to be done before using `email_topic.py`.
We have to configure a smtp server to use `email_topic.py`
If there is a better position to put this, please tell me.
=> [jsk_robot_startup] Update Readme; configuring a smtp server

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_warning/cable_warning.l
If L1 is pressed, `/joy_vel` is selected and cable_warning node speaks "電源ケーブルを抜いてください。".
It is undesirable when we want to command torso up (L1+△)/torso down (L1+×) with PR2 connected to the cable. 
- [PR2 teleoperation](https://github.com/jsk-ros-pkg/jsk_robot/tree/master/jsk_pr2_robot#teleoperation)
- [JSK safe teleop system](https://github.com/jsk-ros-pkg/jsk_robot/tree/master/jsk_robot_common/jsk_robot_startup#launchsafe_teleoplaunch)
- [pr2_teleop_general_joystick.cpp](https://github.com/PR2/pr2_apps/blob/melodic-devel/pr2_teleop_general/src/pr2_teleop_general_joystick.cpp)
=> [jsk_pr2_startup/cable_warning.l] No warning for zero velocity

jsk_fetch_robot/jsk_fetch_startup/config/config.bash, jsk_fetch_robot/jsk_fetch_startup/supervisor_scripts/jsk-fetch-startup.conf
Related to #1551 
We replaced the fetch1075 speakers as a trial.
To automatically select a speaker, we need to set the `AUDIO_DEVICE` environment variable.
So, this PR set the variable in config.bash
=> [jsk_fetch_startup] Set AUDIO_DEVICE environment variable to select peaker

jsk_pr2_robot/pr2_base_trajectory_action/include/pr2_base_trajectory_action/math_spline.h, jsk_pr2_robot/pr2_base_trajectory_action/include/pr2_base_trajectory_action/pr2_base_trajectory_action_controller.h, jsk_pr2_robot/pr2_base_trajectory_action/src/pr2_base_trajectory_action_controller.cpp, jsk_pr2_robot/pr2_base_trajectory_action/src/pr2_base_trajectory_action_controller_node.cpp, jsk_robot_common/jsk_robot_startup/include/jsk_robot_startup/lightweight_logger.h, jsk_robot_common/jsk_robot_startup/include/jsk_robot_startup/message_store_singleton.h, jsk_robot_common/jsk_robot_startup/src/joint_states_throttle_node.cpp, jsk_robot_common/jsk_robot_startup/src/lightweight_logger_nodelet.cpp, jsk_robot_common/jsk_robot_startup/src/message_store_singleton.cpp
There has always been a TYPO in the SOFTWARE LICENSE AGREEMENT.
This is not good because the users copy here and make a node.
=> Fixed typo of Software License Agreement. and/o2r to and/or

jsk_robot_common/jsk_robot_startup/scripts/email_topic.py, jsk_robot_common/jsk_robot_startup/scripts/smach_to_mail.py
In this PR, both `smach_to_mail.py` and `email_topic.py` stop using yaml file to set email config.
`email_topic.py` has been used for some months, so it is deprecated rather than completely dropping yaml config.
=> [jsk_robot_startup] Not using yaml file to set email config like receiver mail address

jsk_hand/softhand_ros/README.md
Dynamixel motor's max torque is set in volatile memory (RAM) only when roslaunch is called.
When we disconnect dynamixel while roslaunch is running, the max torque value in non-volatile memory (EEPROM) is used, and its default value is `1023` (Max torque).
In this section, we set the max torque value in non-volatile memory (EEPROM) as `0`.
The effect is that the max torque will be set as `0` and the motor does not move, when we disconnect dynamixel motor while roslaunch is running.
So, users need to stop and re-launch the roslaunch again to set correct max torque.
I applied this modification to baxter's softhand, to avoid motor burn.
@soonhyo @pazeshun @tohirose @YUKINA-3252 
see https://www.besttechnology.co.jp/modules/knowledge/?Dynamixel%20MX-28#y4bb6b9b for more information about …
=> [softhand_ros] zero torque limit instruction to avoid max torque use

jsk_unitree_robot/cross/install.sh
split from https://github.com/k-okada/jsk_robot/pull/69
Is this for MacOS ??? @iory
=> [jsk_unitree_startup/cross] Use sshpass instead of /usr/bin/sshpass

jsk_fetch_robot/jsk_fetch_startup/supervisor_scripts/jsk-switch-wifi-73b2.conf, jsk_fetch_robot/jsk_fetch_startup/supervisor_scripts/jsk-switch-wifi-outside.conf
this PR adds `jsk-switch-wifi-outside` and `jsk-switch-wifi-73B2` supervisor conf.
you can press the button on supervisor GUI, and you can change the network configuration.
In the conf, the follwing command runs.
```bash
nmcli c up sanshiro-73B2
nmcli c up sanshiro-outside
```
cc. @nakane11
=> [develop/fetch] add jsk-switch-wifi supervisor conf

jsk_fetch_robot/jsk_fetch.rosinstall.melodic, jsk_fetch_robot/jsk_fetch_startup/apps/go_to_kitchen/go_to_kitchen.app, jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
This PR needs https://github.com/ros-visualization/executive_smach_visualization/pull/46
I add `smach_image_publisher` and record `smach` transition video.
You can find video in the following e-mail
`Fetch kitchen patrol demo: 2022/09/30 (23:30:36)`
https://user-images.githubusercontent.com/9300063/193293228-af16723b-0947-407b-a310-5987cf7fb149.mp4
=> [develop/fetch][jsk_fetch_startup] record smach transition in go_to_kitchen app

jsk_fetch_robot/jsk_fetch_startup/CMakeLists.txt, jsk_fetch_robot/jsk_fetch_startup/config/.gitignore, jsk_fetch_robot/jsk_fetch_startup/config/email_topic.yaml.in, jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
This change depends on https://github.com/jsk-ros-pkg/jsk_robot/pull/1588 .
We use rosparam instead of yaml file to set email information.
=> [jsk_fetch_startup] Use email address instead of yaml for smach_to_mail

jsk_fetch_robot/jsk_fetch_startup/apps/go_to_kitchen/go_to_kitchen.app, jsk_robot_common/jsk_robot_startup/scripts/smach_to_mail.py
This PR enables us to set the same email title between `smach_to_mail.py` and `app_manager_utile/mail_notifier_plugin`.
We can receive the same demo emails as one thread.
app_managerで管理されているデモのうち，プラグインからメール通知が行くものに関して，smach_to_mail側が同じタイトルに合わせられるようにした変更です．
=> [jsk_robot_startup] [jsk_fetch_startup] Use /email_topic/mail_title for email title in kitchen-demo

jsk_pr2_robot/jsk_pr2_startup/pr2_gazebo.launch
pr2.launch starts pr2_gdrive_server.launch by default from https://github.com/jsk-ros-pkg/jsk_robot/pull/1392, but I don't think it is needed for simulation.
If `client_secrets.json` is not placed, the nodes keep respawning.
=> [jsk_pr2_startup] disable gdrive_server in pr2_gazebo.launch

jsk_fetch_robot/README.md, jsk_fetch_robot/fetcheus/fetch-interface.l
this PR allow not to use `eus10` or `roseus_resume`.
We can load `fetch-interface` in `eus9` and not `roseus_resume` installed workspace.
I also updated the readme for installation.
=> [develop/fetch] [fetcheus] do not load roseus_resume when roseus_resume is not found

jsk_robot_common/jsk_robot_startup/scripts/smach_to_mail.py
This PR adds timeout section for smach notification.
If demo fails, smach notification is not sent. (Ideally, failure or timeout should be detected on the demo side and brought to the finish state as a state transition, but I think it's also good to support on the `smach_to_notification` side.)
And I also refactor getting rosparam.
=> [jsk_robot_startup] Add timeout for smach notification and refactor error handling

jsk_pr2_robot/jsk_pr2_startup/pr2_bringup.launch
this PR add `use_voice_text` arg in `pr2_bringup.launch`.
when we set `false` in `use_voice_text`, PR2 will use `aques_talk`.
=> [jsk_pr2_startup] add use_voice_text arg in pr2_bringup.launch

jsk_denso_robot/cobottaeus/cobotta-oss-interface.l
COBOTTA OSS publishes two types of joint_states (arm and gripper) to one topic:
```
$ rostopic echo /cobotta/joint_states 
header: 
seq: 140336
stamp: 
secs: 1665713626
nsecs: 996598999
frame_id: ''
name: [joint_gripper]
position: [0.011664775546719816]
velocity: []
effort: []
---
header: 
seq: 140113
stamp: 
secs: 1665713626
nsecs: 997815384
frame_id: ''
name: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
position: [-0.1776660274798269, -0.2001291276808761, 1.4076959332091423, 0.11033073128926771, -0.6619518902611218, -0.016595376969955465]
velocity: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
header: 
seq: 140337
stamp: 
secs: 1665713627
nsecs:    668648
frame_id: ''
name: [joint_gripper]
position: [0.011664775546719816]
velocity: []
effort: []
--- …
```
=> [cobottaeus][OSS] Change queue size of joint_states

jsk_pr2_robot/pr2_base_trajectory_action/config/pr2_base_link.yaml
https://github.com/jsk-ros-pkg/jsk_robot/pull/623 refactored `pr2_base_trajectory_action.cpp` and used `pr2_base_trajectory_action_controller.cpp` instead. Parameter names were changed at this time. 
The problem is that `pr2_base_link.yaml` still sets previous parameters, so I fixed it.
=> [pr2_base_trajectory_action] Fix parameter names in pr2_base_link.yaml

jsk_naoqi_robot/cross/repos/pepper.repos
https://github.com/PR2/app_manager/pull/59
がマージされたので，
`repos/pepper.repos`に書かれた`app_manager`のバージョンを変更しました。
以下のように`make user`が失敗します。
```
kochigami@kochigami-desktop:~/catkin_ws/src/jsk_robot/jsk_naoqi_robot/cross$ make user
./build_user.sh
+ mkdir -p i386_User/src/jsk_robot
+ rsync -avzh --delete --exclude 'jsk_naoqi_robot/cross*' --exclude nao.l --exclude pepper.l --exclude nao-simple.l --exclude pepper-simple.l ../../../jsk_robot i386_User/src/
sending incremental file list
jsk_robot/
jsk_robot/.gitignore
jsk_robot/.gitmodules
jsk_robot/.travis.rosinstall
jsk_robot/.travis.rosinstall.hydro
jsk_robot/.travis.rosinstall.indigo
jsk_robot/.travis.rosinstall.kinetic
jsk_robot/.travis.rosinstall.melodic
jsk_robot/.travis.rosinstall.noetic
jsk_robot/.travis.yml
jsk_robot/README.md
…（省略）...
+ …
```
=> [jsk_naoqi_robot/cross/repos] update app_manager version in pepper.repos

jsk_fetch_robot/jsk_fetch.rosinstall.melodic
in order to solve the issue #1665, we need the following PRs.
so this PR switches to use the develop branch `knorth55/fetch_ros@develop/fetch`.
=> [develop/fetch] use knorth55/fetch_ros@develop/fetch branch

jsk_robot_common/jsk_robot_startup/scripts/smach_to_mail.py
this PR diable `google_chat_ros` when `google_chat_space` param is not set.
currently, `fetch1075` does not send e-mail because of this.
=> [develop/fetch] diable google chat when google_chat_space is not set

jsk_robot_common/jsk_robot_startup/scripts/smach_to_mail.py
this PR disable`google_chat_ros` when `google_chat_ros` is not installed.
this is because `google_chat_ros` is not merged to `jsk_3rdparty`.
https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/323
=> [jsk_robot_startup] disable google_chat_ros in smach_to_mail.py

jsk_robot_common/jsk_robot_startup/scripts/smach_to_mail.py
`~google_chat_space` is necessary field for `smach_to_mail.py` if you want to use `Google Chat`
this PR check if `~google_chat_space` is set, and if not disable `Google Chat`.
=> [jsk_robot_startup] disable google chat when google_chat_space is not set

jsk_robot_common/jsk_robot_startup/scripts/smach_to_mail.py
this PR add missing import `os` in `smach_to_mail`
=> [jsk_robot_startup] add missing import in smach_to_mail

jsk_robot_common/jsk_robot_startup/scripts/smach_to_mail.py
currently, `:finish` and `:end` are supported for finish condition in `smach_to_mail`.
I add `:finish-success` and `:finish-failure` conditions.
=> [jsk_robot_startup] add finish-success and finish-failure in smach_to_mail

jsk_fetch_robot/jsk_fetch.rosinstall.indigo
this PR updates `jsk_fetch.rosinstall.indigo`.
`jsk_fetch.rosinstall.indigo` is copied from `origin/develop/fetch` branch
=> [jsk_fetch_robot] update jsk_fetch.rosinstall.indigo

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/pr2_microphone.launch, jsk_pr2_robot/jsk_pr2_startup/pr2.launch
This PR adds `respawn` flag for `respeaker_node`.
Also, in `pr2.launch` we set `respawn` `true` for `respeaker_node`.
=> [jsk_pr2_startup] add respawn to respeaker node

jsk_fetch_robot/jsk_fetch_startup/euslisp/navigation-utils.l
I added timeout for get-light-on function.
Without this PR, `get-light-on` hangs when head camera image does not publish.
=> [jsk_fetch_startup] Add timeout for get-light-on

jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/email_topic_client.py
When I tried `roslaunch jsk_robot_startup sample_email_topic.launch receiver_address:="my email address" use_eus:=false`, 
I got the following error because `Email.msg` is updated in https://github.com/jsk-ros-pkg/jsk_robot/commit/1993399f50bd4569c51e7700d46e2a863a469d2f
```
kanae@kanae-ThinkPad-T480s:~/catkin_ws/devel$ roslaunch jsk_robot_startup sample_email_topic.launch receiver_address:="my email address" use_eus:=false
... logging to /home/kanae/.ros/log/d410d19c-5ff4-11ed-a4b2-e86a6433c67f/roslaunch-kanae-ThinkPad-T480s-9441.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.
started roslaunch server http://192.168.97.182:42673/
SUMMARY
========
PARAMETERS
* /email_topic/email_info: …
```
=> [jsk_robot_startup/src/jsk_robot_startup/email_topic_client.py] update msg body format based on new Email.msg

jsk_robot_common/jsk_robot_startup/lifelog/common_logger.launch, jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/lifelog/action_logger.py, jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/lifelog/base_trajectory_logger.py, jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/lifelog/mongo_record.py, jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/lifelog/object_detection_logger.py, jsk_robot_common/jsk_robot_startup/src/jsk_robot_startup/lifelog/tf_logger.py, jsk_robot_common/jsk_robot_startup/src/lightweight_logger_nodelet.cpp
This PR supports launching multiple `common_logger.launch` .
Related to #1706 #1714
Use case:
- Divide database dependent on each demonstration. (kitchen demo, PR2 fridge demo, etc)
- Able to change database name and collection name.
cc: @knorth55
=> [jsk_robot_startup] Support manual setting of the name of mongodb database and collection

jsk_naoqi_robot/naoqieus/naoqi-interface.l
this PR enables us to move nao in kinematics simulator.
https://user-images.githubusercontent.com/9300063/202148997-2c35761b-dcfd-4117-894d-5a8afb210172.mp4
cc. @a-ichikura
=> [naoeus] use robot-move-base-interface for naoqi-interface

jsk_robot_common/jsk_robot_startup/scripts/smach_to_mail.py
WIth this PR, we use node status to send notification from smach when `end` state doesn't come.
Reflect comment https://github.com/jsk-ros-pkg/jsk_robot/pull/1695#pullrequestreview-1152269036
=> [jsk_robot_startup] Use checking node status for timeout

jsk_robot_common/jsk_robot_startup/CMakeLists.txt, jsk_robot_common/jsk_robot_startup/package.xml
-   jsk_robot_startup/CMakeLists.txt: install python code using catkin_install_python
-    jsk_robot_startup/package.xml: update to version 3, add python3-* packages to exec_depend
if you want to use jsk_robot_startup, specially `lifelog` with melodic environment compiled with `-DPYTHON_EXECUTABLE=/usr/bin/python3 `,  you need to instal following packages from source
```
#
- git:
local-name: mongodb_store
uri: https://github.com/strands-project/mongodb_store.git
version: noetic-devel
#
- git:
local-name: catkin
uri:     https://github.com/ros/catkin.git
version: 0.8.10
```
part of https://github.com/jsk-ros-pkg/jsk_robot/pull/1701
=> jsk_robot_startup: python3 support

jsk_fetch_robot/jsk_fetch_startup/apps/go_to_kitchen/go_to_kitchen.xml, jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch, jsk_fetch_robot/jsk_fetch_startup/launch/fetch_lifelog.xml, jsk_robot_common/jsk_robot_startup/lifelog/common_logger.launch, jsk_robot_common/jsk_robot_startup/lifelog/mongodb.launch, jsk_robot_common/jsk_robot_startup/src/lightweight_logger_nodelet.cpp
With this PR, we can store `images`, `speech_to_text`, `sound_play/goal` in kitchen-demo.
We can get these data from `jsk_robot_lifelog/go_to_kitchen` data collection
=> [jsk_fetch_startup] [jsk_robot_startup] Use demo-based mongodb logging in kitchen-demo

jsk_robot_common/jsk_robot_startup/lifelog/tweet_client_warning.l
This PR fixes a following bug.
`*speak-enable*` variable is set instead of `*speak*`, but the argument is not changed.
```lisp
[http://fetch1075:11311][133.11.216.83] tsukamoto@tsukamoto-desktop-ryzen ~/ros/fetch_ws/src/jsk-ros-pkg/jsk_robot/jsk_robot_common/jsk_robot_startup (develop/fetch *$%=) 
$ rosrun jsk_robot_startup tweet_client_warning.l _name:=warning_debug
configuring by "/home/tsukamoto/ros/fetch_ws/devel/share/euslisp/jskeus/eus//lib/eusrt.l"
;; readmacro ;; object ;; packsym ;; common ;; constants ;; stream ;; string ;; loader ;; pprint ;; process ;; hashtab ;; array ;; mathtran ;; eusdebug ;; eusforeign ;; extnum ;; conditions ;; coordinates ;; tty ;; history ;; toplevel ;; trans ;; comp ;; builtins ;; par ;; intersection ;; geoclasses ;; geopack ;; geobody ;; primt ;; …
```
=> [jsk_robot_startup] Fix variable name; *speak* -> *speak-enable*

jsk_fetch_robot/jsk_fetch_startup/euslisp/go-to-kitchen.l
Currently, Fetch records images in `SMACH_STATE` only when detects some objects. I want to record all images for processing them with Language model
=> [develop/fetch] [jsk_fetch_startup] [kitchen_demo] always store photo in smach

jsk_fetch_robot/jsk_fetch_startup/scripts/warning.py
this PR fixes typo in `warning.py` in `jsk_fetch_startup`.
=> [jsk_fetch_startup] fix typo in warning.py

jsk_robot_common/jsk_robot_startup/lifelog/auto_speak_volume_lower.l, jsk_robot_common/jsk_robot_startup/lifelog/auto_speak_volume_reset.l, jsk_robot_common/jsk_robot_startup/lifelog/auto_speak_volume_zero.l
this PR set `enable` and `speak_enable` to `nil` for `volume zero` app.
setting `volume` `0` means that robot speaks but no voice.
this causes interruption when other nodes speaks something.
this PR changes to set `enable` and `speak_enable` `nil`.
this change does not sent `sound_play` action, so it does't interrupt any other nodes.
=> [develop/fetch] use enable and speak_enable for volume control

jsk_naoqi_robot/cross/README.md
I fixed the following typos.
`pepepr_meshes` => `pepper_meshes`
=> [jsk_naoqi_robot/cross/README] fix typo

jsk_panda_robot/panda_eus/CMakeLists.txt
Another solution of #1749 
~~Currently, building `panda_eus` fails when `franka_description`'s version is less than 0.10.0.~~
Currently, building `panda_eus` fails when `franka_description`'s version is less than 0.10.0 or `xacro`'s version is less than 1.13.14.
This PR fixes it by skipping `dual_panda.l` generation.
=> [panda_eus] Skip generating dual_panda.l when franka_description or xacro is old to avoid build failure

jsk_fetch_robot/fetcheus/fetch-interface.l, jsk_fetch_robot/fetcheus/test/test-fetcheus.l
this PR enables to run `:go-pos-unsafe` in `kinematics simulation`
=> [fetcheus] :go-pos-unsafe for kinematic simulation

.travis.rosinstall, .travis.rosinstall.kinetic, .travis.rosinstall.melodic, .travis.rosinstall.noetic
In https://github.com/jsk-ros-pkg/jsk_robot/pull/1674, I’d like to include naoqi_apps programs such as `/launch/tablet.launch, basic_awareness.launch, background_movement.launch` to `jsk_pepper_startup.launch`,
which belong to https://github.com/kochigami/naoqi_bridge/tree/kochigami-develop and are not merged to https://github.com/ros-naoqi/naoqi_bridge because merging process of the repository is suspended.
Because these packages are not cloned when running travis test, I got the following errors. 
In the case of kinetic:
```
<testsuite errors="0" failures="1" name="roslaunch-check_jsk_pepper_startup__ROS_IP_10.68.0.2 NAO_IP_10.68.0.3 launch_dashboard_false.launch.xml" tests="1" time="1"><testcase classname="Results" name="test_ran" status="run" time="1"><failure message="roslaunch check …
```
=> [jsk_robot/.travis.rosinstall] update .travis.rosinstall.kinetic/melodic/noetic to install naoqi_bridge source (kochigami-develop)

jsk_robot_common/jsk_robot_startup/lifelog/tweet_client.l, jsk_robot_common/jsk_robot_startup/lifelog/tweet_client_tablet.l, jsk_robot_common/jsk_robot_startup/lifelog/tweet_client_uptime.l, jsk_robot_common/jsk_robot_startup/lifelog/tweet_client_warning.l, jsk_robot_common/jsk_robot_startup/lifelog/tweet_client_worktime.l
I moved `ROS` node codes from `tweet_client.l` to each nodes, and make the file loadable from non-ROS file.
this PR is useful if you want to use kinematics simulation.
if some file load `tweet_cline.l` in kinematics simulation, this part get stucks and wait `rosparam` forever.
=> [jsk_robot_startup] make tweet_client.l loadable  in simulation

jsk_baxter_robot/baxtereus/baxter-softhand-interface.l
this PR fix `&rest args` position.
```
12.irteusgl$ (defun fuga (&optional opt &key (arm nil) &rest args &allow-other-keys) (pprint args))
fuga
13.irteusgl$ (fuga 1 :arm t :wait t)
nil
nil
14.irteusgl$ (defun hoge (&optional opt &rest args &key (arm nil) &allow-other-keys) (pprint args))
hoge
15.irteusgl$ (hoge 1 :arm t :wait t)
(:arm t :wait t)
nil
```
=> [baxtereus] fix &rest args position

jsk_naoqi_robot/cross/build_user.sh, jsk_naoqi_robot/cross/startup_scripts/attach.sh
Based on https://github.com/jsk-ros-pkg/jsk_robot/pull/1583#issuecomment-1235043472,
I added `attach.sh` to attach session which we detached once.
I will add how to use this at https://github.com/jsk-ros-pkg/jsk_robot/pull/1767
=> https://github.com/jsk-ros-pkg/jsk_robot/pull/1767/commits/c75b14f22c3779dd10e8c286b9ec2bbe9da369ed
=> [jsk_naoqi_robot/cross] add attach.sh to attach session which you detached once

jsk_robot_common/jsk_robot_startup/scripts/smach_to_mail.py
this PR fix error in `python3` + `smach_to_mail.py`.
`x['MAIL']` is `bytes` object, so it should be decoded to `utf-8`.
=> [jsk_robot_startup] fix python3 decode error in smach_to_mail

jsk_fetch_robot/jsk_fetch.rosinstall.melodic
Currently, jsk_recognition remote branch that Fetch's internal workspace tracks (knorth55's `fisheye-vital-check`) has already deleted because https://github.com/jsk-ros-pkg/jsk_recognition/pull/2734 has merged.
And I fixed the comment about develop/fetch branch of jsk_robot.
If we should set another branch of jsk_recognition, please tell me.
=> [Fetch] Fix jsk_recognition branch in jsk_fetch.rosinstall.melodic

jsk_pr2_robot/jsk_pr2_startup/pr2_bringup.launch
Currently both `pr2.launch` and `pr2_bringup.launch` run virtual_force_publisher and the nodes are killed for `new node registered with same name` error.
This PR makes  `pr2.launch` stop launching the nodes.
=> [jsk_pr2_startup] Change launch_virtual_force arg to avoid dupulicated node error

jsk_robot_common/jsk_robot_startup/lifelog/tweet_client.l
advertise publisher needed for tweet in `tweet-string` when the publishers are not yet advertised.
with this change, we don't need to write `(ros::advertise "/tweet" ...)` in our script, and we can tweet by just runining `tweet-string`
=> [jsk_robot_startup] advertise when no tweet publisher is advertised yet

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_lifelog.xml, jsk_robot_common/jsk_robot_startup/lifelog/mongodb.launch
This is a develop/fetch version of of #1801 . 
I added arg replicate_on_write to search at replication database server.
=> [devlop/fetch] [jsk_robot_startup/lifelog] Add replicate_on_write arg to mongodb.launch to search at replication server

jsk_robot_common/jsk_robot_startup/lifelog/tweet_client_uptime.l
develop/fetch version 
This PR enables robot to tweet for random minutes instead of elapsed time since robot starts.
=> [jsk_robot_startup/lifelog] Tweet randomly from uptime

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_lifelog.xml
This PR is a master version of https://github.com/jsk-ros-pkg/jsk_robot/pull/1806.
`/robotsound_jp` is being saved at mongodb.
And I added additional commit left in develop/fetch branch about speech_logger. (52c671faf6ec4d2cdf71935f97ae3c03b109e92e, merged at https://github.com/jsk-ros-pkg/jsk_robot/pull/1728)
=> [jsk_fetch_startup] Logging /sound_play/goal and /speech_to_text

jsk_fetch_robot/jsk_fetch_startup/robots/head_l515.srdf.xacro
This PR fixes #1807.
I added disable_collision about head_pan link and l515.
=> [jsk_fetch_startup] Avoid collision between l515 and head_pan_link

jsk_fetch_robot/jsk_fetch.rosinstall.melodic
To reflect https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/495 until that is merged to master branch.
=> [Fetch] Switch branch of jsk_pr2eus to develop/fetch

jsk_robot_common/jsk_robot_startup/scripts/update_workspace_main.sh
This PR added dry run option of update_workspace.sh.
Now fetch and pr2 workspaces forcefully update at 3:00, but this function forcibly erases changes in the robot body, which was troublesome when, for example, we wanted to prepare a demonstration the day before a tour.
This PR avoids that situation.
豊島岡の見学会準備のフィードバックを受けての変更です．
毎朝3時にロボット体内の変更をすべて消し去るのはよくないのではないか，というところを反映しています．
今回の変更を適用するとFetchのwstool updateは手動で行うのがデフォルトになります．
=> [jsk_robot_startup][jsk_fetch_startup] Add dry run option of update_workspace.sh

jsk_fetch_robot/jsk_fetch.rosinstall.melodic
Since https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/495 has merged into master.
And refrect comment at https://github.com/jsk-ros-pkg/jsk_robot/pull/1820.
Revert "[Fetch] Fix comment develop/fetch --> master"
This reverts commit 1cddbe050e2e7832f9ae0fa5fd6e4ed37a0c8bcf.
Revert "[Fetch] Switch branch of jsk_pr2eus to develop/fetch"
This reverts commit b8041d2746767a8da5ddd2566f6a2510663ebd7e.
=> Revert "[Fetch] Switch branch of jsk_pr2eus to develop/fetch"

jsk_fetch_robot/jsk_fetch.rosinstall.melodic
Use https://github.com/sktometometo/esp_now_ros/releases/tag/v0.2.0 release
=> [jsk_fetch_robot] update esp_now_ros version to v0.2.0

jsk_fetch_robot/jsk_fetch_startup/euslisp/navigation-utils.l
Add enr_message_board feature to kitchen demo's trashcan capacity checking.
With this PR, Fetch write a message about trashcan occupancy to enr_message_board.
For string - byte array conversion, see https://github.com/euslisp/jskeus/issues/635 for detail.
=> Add enr_message_board capability to kitchen demo

jsk_fetch_robot/jsk_fetch.rosinstall.melodic
Reverts jsk-ros-pkg/jsk_robot#1832 as https://github.com/ros-visualization/executive_smach_visualization/pull/54 has merged.
=> Revert "[Fetch] Use bugfix branch of executive_smach_visualization"

jsk_fetch_robot/jsk_fetch.rosinstall.melodic, jsk_fetch_robot/jsk_fetch_startup/CMakeLists.txt, jsk_fetch_robot/jsk_fetch_startup/apps/time_signal/time_signal.app, jsk_fetch_robot/jsk_fetch_startup/cfg/TimeSignal.cfg, jsk_fetch_robot/jsk_fetch_startup/package.xml, jsk_fetch_robot/jsk_fetch_startup/scripts/time_signal.py, jsk_robot_common/jsk_robot_startup/lifelog/auto_speak_volume_lower.l, jsk_robot_common/jsk_robot_startup/lifelog/auto_speak_volume_reset.l, jsk_robot_common/jsk_robot_startup/lifelog/auto_speak_volume_zero.l
This PR enables us to change volume of `time_signal.py` from `volume_lower/volume_reset` app.
This change may help us avoid  Fetch's noisy information voice.
c.f. https://github.com/PR2/app_manager/pull/64
=> [jsk_fetch_startup] Use dynamicreconfigure to change speak volume of time_signal.py

jsk_robot_common/jsk_robot_startup/lifelog/mongodb.launch
This PR fixes rosparam `mongodb_replicate_on_write`.
I made a mistake about naming this parmeter when I added it.
If this parameter is true, we can search both robot internal mongo sever and replicateions server.
=> [jsk_robot_startup] Fix mongodb_replicate_on_write param

jsk_naoqi_robot/cross/build_user.sh
Related commit: 
https://github.com/kochigami/jsk_robot/commit/1a0cfe08e51421a2378bc2938ea3014b62e788fb
https://github.com/jsk-ros-pkg/jsk_robot/pull/1583
When I used ubuntu 20.04 + ROS noetic PC, `./build_user.sh` of pepper cross failed.
That is because this script tries to copy `/opt/ros/melodic/share/pepper_meshes/meshes/` forcefully.
`kochigami@kochigami-pc:~/catkin_ws/src/jsk_robot/jsk_naoqi_robot/cross$ ./build_user.sh`
```
.......
+ vcs import i386_User/src
.........
=== i386_User/src/app_manager (git) ===
Cloning into '.'...
=== i386_User/src/nao_interaction (git) ===
Cloning into '.'...
=== i386_User/src/nao_robot (git) ===
Cloning into '.'...
=== i386_User/src/naoqi_bridge (git) ===
Cloning into '.'...
=== i386_User/src/naoqi_bridge_msgs (git) ===
Cloning into '.'...
=== …
```
=> [naoqieus/cross] use $ROS_DISTRO instead of melodic when installing pepper_meshes to allow us to use ROS noetic for build cross environment

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
This PR set google_chat_ros receiving mode as `pubsub` because of the network problems these days.
=> [jsk_fetch_startup] Use pubsub mode in google chat ros

jsk_unitree_robot/cross/repos/unitree.repos, jsk_unitree_robot/unitree.rosinstall, jsk_unitree_robot/unitreeeus/.gitignore, jsk_unitree_robot/unitreeeus/go1-utils.l, jsk_unitree_robot/unitreeeus/package.xml, jsk_unitree_robot/unitreeeus/unitree-interface.l
Fix https://github.com/jsk-ros-pkg/jsk_robot/issues/1866#issuecomment-1751636386
To do this
- Update unitree-ros version to 5dee20c
- Both of `unitree.rosinstall` and `cross/repo/unitree.repos`
- Use go1-robot instead of go1_description-robot in unitreeeus
- Fix misc
- add go1-simple.l (which is automatically generated during catkin build) to .gitignre
- add unitree_legged_msgs to the dependencies of unitreeeus
=> Fix unitreeeus building

jsk_unitree_robot/README.md, jsk_unitree_robot/cross/README.md
Please ask @tkmtnt7000 for System/Users .tgz file. You can also use mars@/tmp/ros1-unitree-arm64v8.tar as saved docker image. If this works, please upload to google drive.
@tkmtnt7000 confirmed https://github.com/jsk-ros-pkg/jsk_robot/pull/1868 works, but in `install.sh` process, we need to enter password several times. I have made https://github.com/k-okada/jsk_robot/pull/101 which should fix this problem, but not confirmed on real robot. Please let me know if this fixed version works @sktometometo
=> README.md: use archive for docker, System, Users.

jsk_fetch_robot/jsk_fetch_startup/launch/fetch_lifelog.xml, jsk_robot_common/jsk_robot_startup/launch/interaction.launch, jsk_robot_common/jsk_robot_startup/launch/lifelog.launch, jsk_robot_common/jsk_robot_startup/launch/sample_database_talker.launch, jsk_robot_common/jsk_robot_startup/lifelog/lifelog_rgb_image.launch
This PR enables robot to record image topic to mongodb every time.
Original PR to master branch is https://github.com/jsk-ros-pkg/jsk_robot/pull/1792, and I adopted to fetch's enviroment.
=> [develop/fetch] [jsk_robot_startup] Record image topic to mongodb every time

jsk_robot_common/jsk_robot_startup/launch/smach_to_mail.launch
This PR fixes an argument name reveiver --> receiver to avoid the following error.
```bash
RLException: [smach_to_mail.launch] requires the 'email_reveiver_address' arg to be set
The traceback for the exception was written to the log file
```
=> [jsk_robot_startup] Fix arg name reveiver --> receiver

jsk_robot_common/jsk_robot_startup/CMakeLists.txt, jsk_robot_common/jsk_robot_startup/cfg/SmachNotificationReconfigure.cfg, jsk_robot_common/jsk_robot_startup/scripts/smach_to_mail.py
@tkmtnt7000 Please check if this PR works and that it incldues all commits related to smach_to_mail.py that is in develop/fetch branch.
If you have tested a new feature or fix a serious bug  on one robot and found it worth installing on othre robots, you may want to  I suggest you create new PR against master branch and ask other robots to rebase origin/master
Related PRs
- https://github.com/jsk-ros-pkg/jsk_robot/pull/1760
- https://github.com/jsk-ros-pkg/jsk_robot/pull/1737
- https://github.com/jsk-ros-pkg/jsk_robot/pull/1732
- https://github.com/jsk-ros-pkg/jsk_robot/pull/1667
- https://github.com/jsk-ros-pkg/jsk_robot/pull/1661
c.f. https://github.com/jsk-ros-pkg/jsk_robot/pull/1882
=> This PR added commits related to smach_to_mail.py that is in develop/fetch branch

jsk_fetch_robot/jsk_fetch.rosinstall.melodic, jsk_fetch_robot/jsk_fetch_startup/launch/fetch.launch
To solve https://github.com/jsk-ros-pkg/jsk_robot/issues/1876 .
@sktometometo did the work https://github.com/jsk-ros-pkg/jsk_robot/pull/1877 , but it causes some strange behavior in the real robot. So I want to adopt [the patch](https://github.com/cra-ros-pkg/robot_localization/pull/595) only for suppressing the warning. Upstream PR is https://github.com/cra-ros-pkg/robot_localization/pull/840
=> [develop/fetch] Suppress TF Duplicated stamp warning in noetic client PC

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/pr2_2dnav.launch, jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/publish_empty_cloud.py
This PR removed slashes from the first character of the topics for noetic tf2 compatibility.
Without this PR, tf is not solved and PR2 does not move with `move_base`  when we use `empty_cloud` in navigation that PR2 Subway demostration uses.
cc: Thanks to @pazeshun
=> [Bugfix] [jsk_pr2_startup] Remove a slash of the first character for noetic (tf2) in publish_empty_cloud.py

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_lifelog/rosbag_play.launch
Adding start_time, duration_time options for rosbag play like fetch1075
=> [jsk_pr2_lifelog] add time related options for rosbag_play

jsk_fetch_robot/jsk_fetch.rosinstall.melodic, jsk_fetch_robot/jsk_fetch_startup/euslisp/navigation-utils.l, jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch, jsk_fetch_robot/jsk_fetch_startup/udev_rules/80-arduino.rules
Update `esp_now_ros` to `v0.5.1` to support name changing to `smart_device_protocol`
=> Pr/develop fetch/change esp now ros to smart device protocol

jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_warning/battery_warning.py
I added a warning about the power cable connector, which has recently been causing problems, such as https://github.com/jsk-ros-pkg/jsk_robot/issues/1644.  
We found that there is a correlation between the temperature of the connector and the temperature of the battery, and that the connector begins to melt at around 45℃, so we have added a warning that is triggered by the battery temperature.
=> [jsk_pr2_startup] Add cable connector check warning

.github/workflows/config.yml
- fix CI, override node20. See actions/upload-artifact#616 (comment) c.f.
jsk-ros-pkg/jsk_control#790
``` Post job cleanup.
/usr/bin/docker exec
a73c1686824111e1103ab64b9f540a586c9548c53a8213840c21206b2f17403a sh -c "cat
/etc/*release | grep ^ID" OCI runtime exec failed: exec failed: unable to
start container process: exec: "/__e/node20/bin/node": stat
/__e/node20/bin/node: no such file or directory: unknown
```
-  update .travis to 0.5.27
=> fix CI, override node20 directory.

jsk_panda_robot/panda_eus/euslisp/dual_panda-interface.l, jsk_panda_robot/panda_eus/euslisp/franka-common-interface.l, jsk_panda_robot/panda_eus/euslisp/panda-interface.l
This PR enables to move Panda like:
```
ROS_NAMESPACE=left_panda roslaunch jsk_panda_startup panda.launch robot_ip:=172.16.0.11
ROS_NAMESPACE=left_panda roseus panda-interface.l
```
to avoid node name collision with other robots (e.g., Cobotta)
=> [panda_eus] Support robots under ROS_NAMESPACE
